### ISSUE TITLE
Getting undefined objects

### ISSUE THREAD

**Issue by mjgonzalez6** [theoephraim/node-google-spreadsheet#103]
I am having a hard time running the example code snippet. I created a blank sheet, enabled API access, generated credentials, etc. When I run the example code, access to the sheet appears to work ok, but sheet operations fail and I am only getting the following:

```
C:\Users\MaríaJosé\Documents\MEAN\myApp\server_app\controllers>node test.js
Loaded doc: nodetest-testing by nao.amigurumis@gmail.com
sheet 1: Hoja 1 1000x26
Read 0 rows
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot set property 'colname' of undefined
    at C:\Users\MaríaJosé\Documents\MEAN\myApp\server_app\controllers\test.js:31:33
    at C:\Users\MaríaJosé\Documents\MEAN\myApp\node_modules\google-spreadsheet\index.js:303:7
    at C:\Users\MaríaJosé\Documents\MEAN\myApp\node_modules\google-spreadsheet\index.js:166:15
    at Parser.<anonymous> (C:\Users\MaríaJosé\Documents\MEAN\myApp\node_modules\google-spreadsheet\node_modules\xml2js\lib\xml2js.js:484:18)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Object.onclosetag (C:\Users\MaríaJosé\Documents\MEAN\myApp\node_modules\google-spreadsheet\node_modules\xml2js\lib\xml2js.js:445:26)
    at emit (C:\Users\MaríaJosé\Documents\MEAN\myApp\node_modules\google-spreadsheet\node_modules\xml2js\node_modules\sax\lib\sax.js:640:35)
    at emitNode (C:\Users\MaríaJosé\Documents\MEAN\myApp\node_modules\google-spreadsheet\node_modules\xml2js\node_modules\sax\lib\sax.js:645:5)
    at closeTag (C:\Users\MaríaJosé\Documents\MEAN\myApp\node_modules\google-spreadsheet\node_modules\xml2js\node_modules\sax\lib\sax.js:905:7)
```

What am I doing wrong?

My sheet looks like this (i.e., it is completely empty):

![test-issue](https://cloud.githubusercontent.com/assets/18425015/14681772/ef6b8ae2-06f8-11e6-86cd-5e50b7962be7.png)

And my code is the following:

``` javascript
    // spreadsheet key is the long id in the sheets URL
    var GoogleSpreadsheet = require("google-spreadsheet");
    var doc = new GoogleSpreadsheet('1-ezRN6qGVUbFUIDvhdJBDA3v_YcpwBDq55KN1GrCaGM');
    var async = require("async");
    var sheet;

    async.series([
        function setAuth(step) {
            // see notes below for authentication instructions!
            var creds = require('../../private/Prueba1-061c12afb573.json');
            doc.useServiceAccountAuth(creds, step);
        },
        function getInfoAndWorksheets(step) {
            doc.getInfo(function(err, info) {
                console.log('Loaded doc: '+info.title+' by '+info.author.email);
                sheet = info.worksheets[0];
                console.log('sheet 1: '+sheet.title+' '+sheet.rowCount+'x'+sheet.colCount);
                step();
            });
        },
        function workingWithRows(step) {
            // google provides some query options
            sheet.getRows({
                offset: 1,
                limit: 20,
                orderby: 'col2'
            }, function( err, rows ){
                console.log('Read '+rows.length+' rows');

                // the row is an object with keys set by the column headers
                rows[0].colname = 'new val';
                rows[0].save(); // this is async

                // deleting a row
                rows[0].del();  // this is async

                step();
            });
        },
        function workingWithCells(step) {
            sheet.getCells({
                'min-row': 1,
                'max-row': 5,
                'return-empty': true
            }, function(err, cells) {
                var cell = cells[0];
                console.log('Cell R'+cell.row+'C'+cell.col+' = '+cells.value);

                // cells have a value, numericValue, and formula
                cell.value == '1'
                cell.numericValue == 1;
                cell.formula == '=ROW()';

                // updating `value` is "smart" and generally handles things for you
                cell.value = 123;
                cell.value = '=A1+B2'
                cell.save(); //async

                // bulk updates make it easy to update many cells at once
                cells[0].value = 1;
                cells[1].value = 2;
                cells[2].formula = '=A1+B1';
                sheet.bulkUpdateCells(cells); //async

                step();
            });
        },
        function managingSheets(step) {
            doc.addWorksheet({
                title: 'my new sheet'
            }, function(err, sheet) {

                // change a sheet's title
                sheet.setTitle('new title'); //async

                //resize a sheet
                sheet.resize({rowCount: 50, colCount: 20}); //async

                sheet.setHeaderRow(['name', 'age', 'phone']); //async

                // removing a worksheet
                sheet.del(); //async

                step();
            });
        }]);
```

**Comment by theoephraim** [comment]
What is it that you are trying to do?

My example is really just to show some of the things you could do with the module.

If you want to read rows, the row based API requires that the first row have values in it. They are used to be the object "keys" for the rest of the rows.

**Comment by mjgonzalez6** [comment]
I was just hoping to use the code example as a tutorial and run it with an empty sheet, but failed as you can see. I think my use scenario is simpler than the example. I need to read regular rows from a sheet in an iterative fashion. The first row of my sheet contains header columns, and from the second row onwards, there is data. I will consume and process the data in an express.js application. Is there any possibility you can point me to an example that reads rows iteratively from a sheet and outputs them to the console? Thanks a heap for your time

**Comment by theoephraim** [comment]
Just throw some test data in your sheet (column names in first row, data in next rows)
and call `getRows` as in the example!

**Comment by cytronn** [comment]
Hi there, I get the same Issue, even when I just have 
`async.series([
  function setAuth(step) {
    // see notes below for authentication instructions! 
    var creds = require('./secret.json');
    // OR, if you cannot save the file locally (like on heroku) 
    // var creds_json = {
    //   client_email: 'yourserviceaccountemailhere@google.com',
    //   private_key: 'your long private key stuff here'
    // }
 
    doc.useServiceAccountAuth(creds, step);
  },
  function getInfoAndWorksheets(step) {
    doc.getInfo(function(err, info) {
      console.log('Loaded doc: '+info.title+' by '+info.author.email);
      sheet = info.worksheets[0];
      console.log('sheet 1: '+sheet.title+' '+sheet.rowCount+'x'+sheet.colCount);
      step();
    });
  }
]);`

Really frustrating, I believe what I am doing wrong !

**Comment by DaBlitzStein** [comment]
Same here. This it looks like library it's not working right now.

**Comment by rustanacexd** [comment]
having problem with bulkUpdateCells too throwing ```Cannot read property '$' of undefined
    at self.updateValuesFromResponseData``` error

**Comment by josh-renton** [comment]
I am having a similar issue (callstack from longjohn below).

My use of your API (which has been vastly useful btw, thanks alot!) is to regularly update cells in a spreadsheet from various information sources.

I use the cell-based API.

In my initial implementation it would re-auth the spreadsheet and grab the cells every time the server was triggered. This error NEVER occurred then.

However, now I only auth and grab the cells during server startup. This error has started to appear very intermittently and unpredictably, even at the end of the server run after a bulkUpdate() has been called.

----- Callstack -----

/home/ubuntu/server/aws_server/node_modules/google-spreadsheet/index.js:539
var input_val = _data['gs:cell']['$']['inputValue'];
^
TypeError: Cannot read property '$' of undefined
at SpreadsheetCell.self.updateValuesFromResponseData (/home/ubuntu/server/aws_server/node_modules/google-spreadsheet/index.js:539:37)
at /home/ubuntu/server/aws_server/node_modules/google-spreadsheet/index.js:640:12
at Request._callback (/home/ubuntu/server/aws_server/node_modules/google-spreadsheet/index.js:170:18)
at Request.self.callback (/home/ubuntu/server/aws_server/node_modules/request/request.js:188:22)
at emitTwo (events.js:106:13)
at Request.emit (events.js:191:7)
at Request.<anonymous> (/home/ubuntu/server/aws_server/node_modules/request/request.js:1171:10)
at emitOne (events.js:96:13)
at Request.emit (events.js:188:7)

at Request.init (/home/ubuntu/server/aws_server/node_modules/request/request.js:191:10)
at new Request (/home/ubuntu/server/aws_server/node_modules/request/request.js:130:8)
at request (/home/ubuntu/server/aws_server/node_modules/request/index.js:54:10)
at request (/home/ubuntu/server/aws_server/node_modules/google-spreadsheet/index.js:145:9)
at /home/ubuntu/server/aws_server/node_modules/google-spreadsheet/node_modules/async/lib/async.js:718:13
at Immediate.iterate (/home/ubuntu/server/aws_server/node_modules/google-spreadsheet/node_modules/async/lib/async.js:262:13)
at runCallback (timers.js:672:20)
at tryOnImmediate (timers.js:645:5)
at processImmediate [as _immediateCallback] (timers.js:617:5)

**Comment by lucasfogliarini** [comment]
put it on init of method.
```js
function getInfoAndWorksheets(step) {
    doc.getInfo(function(err, info) {
    if (err) {
        throw err;
        }
      //process
    });
  },
```

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020). **YOU MUST MIGRATE IF YOU ARE STILL USING THIS PACKAGE!**

**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

I do believe the new interface should be cleaner. Please test it out and if you find that there is still a problem, reopen the issue.

Thanks! 😄

**Comment by kintut4** [comment]
Hey ive been tearing my hair out over this api... 
two things.. 
var doc = new GoogleSpreadsheet('1Ogo76qK2_gE0nDlv_DhOd6Q14ZNjEPqMa1mpJ4XE0vI');
doc.useServiceAccountAuth(creds)
    const todo = async ()=>{
    await doc.loadInfo();
    const sheet = await doc.sheetsByIndex[1];
    ops = []  
    const rows = await sheet.getRows({});
    console.log(rows);
if you try to map rows with a for loop trying to simply get all the ['_rawData'] you just simply get the first value from the table repeated by the number of items... if you just get them through a for loop, you then get a string you can do fuck all with..
however, the above code works although if i add:
const cell = await sheet.loadCells();
console.log(cell)
then thats undefined... whytf?
if i try something else it says the cell hasnt loaded yet... wtf (jackie chan).. for real.. help please?????

**Comment by theoephraim** [comment]
@kintut4 check out the docs. There are some examples that should help.

If you are using the row based methods, it assumes your sheet is structured like a database, with the first row containing header values. For example in a table of people, the first row may contain "id", "firstName", "lastName", ...
When you load the rows, youll get objects that would then have those headers as property names. For example `row.firstName`. See https://theoephraim.github.io/node-google-spreadsheet/#/?id=working-with-rows

In the cell-based methods, loading the cells loads a range of cells into a cache. So first you trigger the loading of the cells, and then you can access them by A1 address or row and column index. See https://theoephraim.github.io/node-google-spreadsheet/#/?id=working-with-cells
