### ISSUE TITLE
TypeError: cb is not a function

### ISSUE THREAD

**Issue by chrisalcantara** [theoephraim/node-google-spreadsheet#105]
Keep getting this error every time I try to update a cell value or use any functions (del, bulkUpdate, etc) for that matter. 

```
doc.getInfo(function(err, info) {

    sheet = info.worksheets[10];

    sheet.getCells({
        'min-row': 2,
        'max-row': 5,
        'return-empty': false
    }, function(err, cells) {
        var cell = cells[0];
        cell.value = 'test';
        cell.save();
    });
});
```

**Comment by theoephraim** [comment]
cell.save is expecting a callback!
usually wise even if you just log it so you can see if there are any errors happening

**Comment by tablekat** [comment]
While I personally feel like cell.save shouldn't fail if not given a callback, if that is the case then the README may need to be updated because it shows `cell.save();` without one.

**Comment by awb99** [comment]
@theoephraim the demos show save without a calllback. You should upate the demos!

**Comment by peter-mouland** [comment]
interesting PR, but i think because it is async, allowing callbacks to be omitted would be more mis-leading to the user.  It would give the impressions that those calls are sync.

Although, the lack of callbacks in the example on the readme tripped me over, it was mentioned that the callbacks had been missed for berevity.  However, i think including `, cb` on those functions would be a better way to give the examples.

Happy to do a PR if you're happy to accept?

**Comment by tablekat** [comment]
I think it's still unintuitive considering most other asynchronous libraries do not require a callback for things like `.save()` where you don't always need to get a result. Some notable ones are [mongoose](http://mongoosejs.com/docs/api.html) (`.save()` doesn't require a callback), [requestjs](https://github.com/request/request), and even in standard es6 promises you can call `.then()` and not pass anything to it.

**Comment by theoephraim** [comment]
FYI - I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020). **YOU MUST MIGRATE IF YOU ARE STILL USING THIS PACKAGE!**

**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

The new version is promise based and should be much cleaner.

Thanks! 😄
