### ISSUE TITLE
reading only first row from spreadsheet

### ISSUE THREAD

**Issue by charithvalluru** [theoephraim/node-google-spreadsheet#112]
I have 20 rows in my spreadsheet, and i have used the same method as suggested in the code. But when i console log the data, only the first row is displayed.

And also, can i know what is the use of step();

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020). **YOU MUST MIGRATE IF YOU ARE STILL USING THIS PACKAGE!**

**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

Thanks! 😄
