### ISSUE TITLE
Auth not working

### ISSUE THREAD

**Issue by coloradude** [theoephraim/node-google-spreadsheet#117]
``` js
var creds = {
    client_email: 'human-design@gentle-edition-132120.iam.gserviceaccount.com',
    private_key: '-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBg.......etc'
}

var doc = new GoogleSpreadsheet('1V_0tozz6NmiuFV5BK0WAqRR0rOIB_GVnkI6f1rVx3Uw')

doc.useServiceAccountAuth(creds, (err, token) => {
    doc.getInfo( res => {
        console.log(res)
    })
})
```

This returns undefined. What am I doing wrong?

**Comment by manasouza** [comment]
Maybe it's by misinterpretation on creds, that must be a String, as saw at #110. In my case I was getting undefined when passing the service account json file as is, loaded by require. 
After doing JSON.stringify(credentials) could get the content of **err**

**Comment by morrislaptop** [comment]
doc.getInfo((err, res) => {
        console.log(res)
    });

**Comment by theoephraim** [comment]
FYI - I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020). **YOU MUST MIGRATE IF YOU ARE STILL USING THIS PACKAGE!**

**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

Thanks! 😄
