### ISSUE TITLE
Add which API version this module uses to README

### ISSUE THREAD

**Issue by objectiveSee** [theoephraim/node-google-spreadsheet#119]
The current API version for Google Spreadsheets is now 4.0. It is unclear which version of the API this module uses. Could you add that to the README somewhere?

https://developers.google.com/google-apps/spreadsheets/worksheets
https://developers.google.com/sheets/guides/migration
https://developers.google.com/sheets/

**Comment by spryce** [comment]
+1 Do we know what version of the API this is for. I am totally new to Google Sheets and am just starting a new project.

**Comment by theoephraim** [comment]
My how time flies - only took me 4 years :)

I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020). **YOU MUST MIGRATE IF YOU ARE STILL USING THIS PACKAGE!**

**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

Thanks! 😄
