### ISSUE TITLE
Finished Callbacks?

### ISSUE THREAD

**Issue by mamarilmanson** [theoephraim/node-google-spreadsheet#122]
Are there any call backs for when google spreadsheets finish loading? I need for presentation purposes to load a loading screen... thanks... :)

**Comment by theoephraim** [comment]
What do you mean finished loading? Every call has callbacks!

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020). **YOU MUST MIGRATE IF YOU ARE STILL USING THIS PACKAGE!**

**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

The new API is promise based and should be more clear.

Thanks! 😄
