### ISSUE TITLE
Can't add data with addRow

### ISSUE THREAD

**Issue by urre** [theoephraim/node-google-spreadsheet#123]
I can access my spreadsheet correctly (using service account method), but wondering why i can't add a new row. Would be thankful for some input:

my code:

```javascript
var GoogleSpreadsheet = require('google-spreadsheet');
var async = require('async');

var doc = new GoogleSpreadsheet('1DfcW1M4D4qyJr7WZw13AACeXaE-wCyus6cnC1I5SSZM');
var sheet;

var newrow = {
    title: 'banana',
    type: 'fruit',
    url: 'http://example.com'
};

async.series([
  function setAuth(step) {
    var creds = require('./fruits.json');
    doc.useServiceAccountAuth(creds, step);
  },
  function getInfoAndWorksheets(step) {
    doc.getInfo(function(err, info) {
      console.log('Loaded doc: '+info.title+' by '+info.author.email);
      sheet = info.worksheets[0];
      console.log('sheet 1: '+sheet.title+' '+sheet.rowCount+'x'+sheet.colCount);
      step();
    });
  },
  function addStuff(step) {
    // Add data
    doc.addRow({
      worksheet_id: 1,
      new_row: newrow,
    }, function( err, rows ){
      step();
    });
  }
]);
```

output:

```bash
Loaded doc: fruits by hejurban@gmail.com
sheet 1: Sheet1 1000x26
```

**Comment by urre** [comment]
@CRFullStack hey! yes i did. Do you have problems with this also?

**Comment by bartholomej** [comment]
```js
function addStuff(step) {
  doc.addRow(1, newrow, function (err, rows) {
    step();
});
```
cc @CRFullStack 

BTW: If you find out any solution it's always better to share it with others instead of just closing issue silently ;)

**Comment by reptily** [comment]
there was a solution?, I have the same problem

**Comment by bartholomej** [comment]
@reptily and have you tried my solution? Just above your comment ;)

**Comment by reptily** [comment]
> @reptily and have you tried my solution? Just above your comment ;)

Yes, it did not help.
but I found a solution
first set header

```
_sheet.setHeaderRow(['id','name','body'],()=>{
//call
});
```
but it still did not help, then I started looking for a problem in the module, and it was discovered that the array is not read correctly and made changes.
[fix](https://github.com/theoephraim/node-google-spreadsheet/compare/master...reptily:patch-1)
and now everything works great

```
_sheet.addRow({
      worksheet_id:1,
      new_row:{
       id:1,
      name:'Test',
      body:'ZZZZzzz'
    }
    },()=>{
//call
});
```
