### ISSUE TITLE
Prepend a row to top spreadsheet

### ISSUE THREAD

**Issue by Connor-Knabe** [theoephraim/node-google-spreadsheet#127]
First off thank you so much for making this wonderful module! 

Currently .addRow() appends the row to the first empty space in the sheet.  I was wondering if there is a way to have it prepend the first empty row? So if I have a blank space at the top of my sheet it would fill data there and then the next row it adds would be above that.  I've played with inserting empty rows but the API doesn't seem to recognize rows inserted by itself as empty.  Now if I go to my sheet and manually hit delete on a row then the API will insert it above that cleared out row.

Any ideas? 
I looked into issue #49 but that seemed quite a bit more complicated than this.

**Comment by theoephraim** [comment]
AFAIK, the api for adding rows only lets you append to the bottom. And I don't think there are any other API methods for inserting empty rows. So you would have to actually use the bulk cell update methods to move all the content down a row, and then fill in the first row.

Not really worth it IMO.

However, it could be that there are new methods in the v4 of the API! I haven't looked yet.

**Comment by theoephraim** [comment]
FYI - I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020). **YOU MUST MIGRATE IF YOU ARE STILL USING THIS PACKAGE!**

**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

There may be a way to do this using the new v4 api calls?
Let me know if it's still an issue.

Thanks! 😄
