### ISSUE TITLE
SpreadsheetCell.save doesn't save newlines properly

### ISSUE THREAD

**Issue by yfp** [theoephraim/node-google-spreadsheet#128]
When working with cells, it's not possible to save strings with linefeeds (`\n`). New lines are being removed from the cell values.

Cause: function `xmlSafeValue` doesn't escape linefeeds.

**Comment by theoephraim** [comment]
FYI - I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020). **YOU MUST MIGRATE IF YOU ARE STILL USING THIS PACKAGE!**

**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

Thanks! 😄
