### ISSUE TITLE
Google Sheets api v4

### ISSUE THREAD

**Issue by peter-mouland** [theoephraim/node-google-spreadsheet#132]
i've been looking through the code and it seems like this is using a deprecated version of the API (v3), is this correct?

Have you any plans to migrate to v4 or would you be will to accepts PR's to help achieve this?

see https://developers.google.com/sheets/guides/migration
and https://developers.google.com/sheets/

**Comment by theoephraim** [comment]
no plans to migrate in the near-term myself, as I have a few other projects on the go.
Happy to accept PRs though.

The last big chunk of work I did on this was to build up a complete testing suite so we can make changes like this with some confidence.

**Comment by peter-mouland** [comment]
great - test do make PR's much easier!
hopefully i'll get a chance to play with v4 soon (after i've finished my home DIY!)
