### ISSUE TITLE
Bulk add rows functionality

### ISSUE THREAD

**Issue by odub** [theoephraim/node-google-spreadsheet#135]
Is there any hope of a `bulkAddRows` in future to save having to implement synchronous solutions like #40?

**Comment by peter-mouland** [comment]
i wrote a helper which uses the bulkAddCells (so you don't get the timeout issues like #40 - and it's much much faster)

I call a custom addRowsBulk function:

```js
addRowsBulk(createRows(data), createRowOptions(data))
```

the `createRows` just creates and array of rows containing an arrow of cells.
i.e. if you have a _normal_ json object, an array (rows) containing objects (cells)), then you could do the same:

```js
const createRows = (rows) => rows.map((cells) => {
//first cell is null... not sure why
  return [null].concat(Object.keys(cells).map(key => cells[key]))
})
```

the `createRowOptions` just return some options based on the data length:

```js
const createRowOptions = (data) => ({
  'return-empty': true,
  'min-row': 1 + 1,
  'max-row': data.length + 1
});
```

```js

function addRowsBulk(worksheet, rows, opts) {
   getCells(worksheet, opts)
        .then((cells) => {
          cells.forEach((cell, i) => {
            try {
              cell.value = String(rows[cell.row - 2][cell.col]); // eslint-disable-line
            } catch (e) {
              log(`NOT FOUND ${i} : R${cell.row} C${cell.col} rows:${rows.length}`);
            }
          });
          log('Updating Cells...');
          return bulkUpdateCells(worksheet, cells);
        });
    });
};
```

this uses a promised version of `getCells`

```js
const getCells = (doc, opts) => new Promise((resolve, reject) => {
  doc.getCells(opts, (err, cells) => {
    if (err) reject(err);
    resolve(cells);
  });
});
```

**Comment by theoephraim** [comment]
So this module is using the v3 API. There is nothing in the docs about bulk adding rows, although maybe it would work...?

Otherwise you would have to use the bulk cells edit as explained above.

Happy to take a PR! :D

**Comment by odub** [comment]
V3 API docs: https://developers.google.com/google-apps/spreadsheets/data

> **Important:** Only the cells feed supports batching requests.

Seems like the helper function approach is the way to go. Thanks for the code sample.

**Comment by theoephraim** [comment]
if one of you guys wants to turn that helper above into a PR (with some tests) I'll very happily merge it in. I'm sure lots of people have this need.

**Comment by theoephraim** [comment]
FYI - I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020). **YOU MUST MIGRATE IF YOU ARE STILL USING THIS PACKAGE!**

**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

I think it should be pretty easy to make a bulk add rows method with the new API.
I'll add to the to-do list now that I'm working on this package again.

Thanks! 😄
