### ISSUE TITLE
Any way to change color? 

### ISSUE THREAD

**Issue by sithumc** [theoephraim/node-google-spreadsheet#137]
Is it possible to change font or background color of a cell ? 
If it is possible, How? 
It it is yet to be implemented, When?

**Comment by olegs-codefresh** [comment]
@sithumc , did you managed that ?

**Comment by KryptoCrash** [comment]
@sithumc have you found a way to do this?

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020). **YOU MUST MIGRATE IF YOU ARE STILL USING THIS PACKAGE!**

**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

The new api can handle formatting with the cell-based methods.

Thanks! 😄
