### ISSUE TITLE
How to deal with very large sheets?

### ISSUE THREAD

**Issue by stringbeans** [theoephraim/node-google-spreadsheet#140]
Hi!

I am trying to fetch and parse data from a very large sheet (over 50000 rows). When I try to fetch all those rows into memory my node process will die due to memory allocation issues. Is there any way we can stream the data in? Or do you have any other ideas around how to process a very large spreadsheet? 

Thanks!

**Comment by mastef** [comment]
Yeah also running into this - one way is to call it with e.g. `$ node --optimize_for_size --optimize-for-size --max-old-space-size=4096 my-script.js`

But e.g. in AWS Lambda you have max. 1500 mb and that will already be reached when loading up 5000 rows. Would be good to have a memory efficient way to load big sheets into memory.

**Comment by mastef** [comment]
Another way to cycle through large sheets is to split the calls based on max-columns per call. It gives you a semi-buffer solution.

```js
// define this somewhere before calling async, so it's in the global namespace
var all_cells = [];
// we want everything from row 4 on
var curRow = 3; 
```

```js
function loadCellsInBatches(step) {
  var colsPerRequest = 300;
  
  if(curRow < sheet.rowCount) {
    var maxRow = (curRow+colsPerRequest);
    if(maxRow > sheet.rowCount) maxRow = sheet.rowCount;

    sheet.getCells({
      'min-col': 1,
      'max-col': 14,
      'min-row': (curRow+1),
      'max-row': maxRow,
      'return-empty': true
    }, function(err, cells) {

      if(err) {
        console.log(err);
        return step(err);
      }

      while(cells.length > 0) {
        curRow = cells[0].row;
        all_cells.push(cells.shift());
      }

      loadCellsInBatches(step);
    });

  }else{
    // we're done with loading all cells, continue to the next step
    step();
  }
}
```

**Comment by theoephraim** [comment]
I think a solution like what @mastef has provided makes sense. This library could certainly be optimized to use a lot less memory, but regardless it will break down at some number of rows/cells. It is very common to be in a situation like this with node where you are dealing with too much data at once and have to start breaking it up to deal with in chunks. The other option is to use streams, but this requires having a stream based api and introduces a whole other set of issues to deal with.

Perhaps the examples section in the readme is starting to break down and we should add an examples folder with different scenarios. Something like this would be an excellent example.

Pull requests welcome :)

**Comment by mastef** [comment]
#183 also helps with memory, it reduced +1,5gb memory consumption down to 600mb
