### ISSUE TITLE
set auth for multiple docs?

### ISSUE THREAD

**Issue by dgolant** [theoephraim/node-google-spreadsheet#142]
My use case is extracting, transforming, and inserting data from one doc to another (and it has to be another doc unfortunately :/ )

When I try to set auth for two separate docs, I try to not use a callback ex:

```
doc1.useServiceAccountAuth(creds_json);
doc2.useServiceAccountAuth(creds_json, step);
```

but I get an error.  Is there any way to set auth for 2 different docs in one method like the `setAuth()` method in the readme? 

Great tool btw, making my life better 💯

**Comment by theoephraim** [comment]
FYI - I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020). **YOU MUST MIGRATE IF YOU ARE STILL USING THIS PACKAGE!**

**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

Thanks! 😄
