### ISSUE TITLE
Impersonate users

### ISSUE THREAD

**Issue by bassamseif** [theoephraim/node-google-spreadsheet#143]
Is there a way to impersonate users when authenticating with a service account using this library?

**Comment by theoephraim** [comment]
Should be easy to add, and it's on my todo list for next steps now that I'm actively working on the project again.

FYI - I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020). **YOU MUST MIGRATE IF YOU ARE STILL USING THIS PACKAGE!**

**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

Thanks! 😄
