### ISSUE TITLE
addWorksheet only if it does not exists

### ISSUE THREAD

**Issue by yamsellem** [theoephraim/node-google-spreadsheet#150]
Using `addWorksheet` when it already exists throw the error `Error: HTTP error 400 (Bad Request) - A sheet named ".." already exists`.

So, is there a way to check if a sheet with a given name already exists? Or, even better, is there an option for `addWorksheet`, to create the sheet only if it does not exist yet.

Thanks.

And a HUGE thanks for the credentials step by step explanations, I imagine it saves me hours (even days) on the google interfaces & co.

**Comment by theoephraim** [comment]
FYI - I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020). **YOU MUST MIGRATE IF YOU ARE STILL USING THIS PACKAGE!**

**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

You can just fetch the sheets using `doc.getInfo()` and check the existing titles

Thanks! 😄
