### ISSUE TITLE
var mySheet = new GoogleSpreadsheet always returns empty

### ISSUE THREAD

**Issue by dylanh724** [theoephraim/node-google-spreadsheet#155]
var mySheet = new GoogleSpreadsheet('mySheetId');

The id was pulled fresh and attempted in plaintext, just for testing - copy and paste. It returns null everytime, resulting in a bind err (Cannot read property 'bind' of undefined)

**Comment by theoephraim** [comment]
More info for a repro? Tests, which are making real calls to sheets, are all looking normal.

**Comment by PEZO19** [comment]
I have the same issue. It is a public sheet and is published to web.

Even if I try to use another sheet from an existing project it fails (returns empty).

@dylanh724  what was your solution to this?

**Comment by theoephraim** [comment]
FYI - I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020). **YOU MUST MIGRATE IF YOU ARE STILL USING THIS PACKAGE!**

**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

Please test it out and if you find that there is still a problem, reopen the issue.

Thanks! 😄
