### ISSUE TITLE
AddRow adds 2 blank rows between existing rows and new row

### ISSUE THREAD

**Issue by jonnycraze** [theoephraim/node-google-spreadsheet#156]
I'm at a bit of a loss regarding what is happening.

When I add a row with sheet.addRow, it is adding 2 empty rows, and then the row I am passing along. I removed all my test data from my spreedsheet minus the first row, and it still did it.

Here is my current code:

```javascript
exports.sheets = function(doc, registration, cb){
  var sheet;
  async.series([
    function setAuth(step) {
      // OR, if you cannot save the file locally (like on heroku)
      var creds_json = {
        client_email: '-----',
        private_key: "-----"
      };
      doc.useServiceAccountAuth(creds_json, step);
    },
    function getInfoAndWorksheets(step) {
      doc.getInfo(function(err, info) {
        console.log('Loaded doc: '+info.title+' by '+info.author.email);
        sheet = info.worksheets[0];
        console.log('sheet 1: '+sheet.title+' '+sheet.rowCount+' rows, '+sheet.colCount + ' columns');
        step();
      });
    },
    function AddRow(step) {
      var _register = {
        firstname: registration.nameFirst,
        lastname: registration.nameLast,
        email: registration.email
      };

      sheet.getRows({
        offset: 1,
        limit: 500,
        orderby: 'email'
      }, function( err, rows ){
        for (var key in rows){
          console.log(rows[key].email);
          if(rows[key].email === registration.email){
            return cb(false);
          }
        }

        console.log(_register);
        sheet.addRow(_register, function(err, data) {
          console.log('added');
          return cb(true);
        });
        step();
      });
    }
  ]);
}
```

**Comment by theoephraim** [comment]
hmm very strange - tests (which are making real calls to a sheet) are all passing.
When you log the rows that you've just fetched, does it look normal? Does the `sheet.rowCount` make sense when you get it from `getInfo`?

**Comment by theoephraim** [comment]
FYI - I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020). **YOU MUST MIGRATE IF YOU ARE STILL USING THIS PACKAGE!**

**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

I do believe this issue should be fixed in the new version.
Please test it out and if you find that there is still a problem, reopen the issue.

Thanks! 😄
