### ISSUE TITLE
ReferenceError: GoogleSpreadsheet is not defined

### ISSUE THREAD

**Issue by petetimp** [theoephraim/node-google-spreadsheet#160]
Hello, I am having an issue with this library (code below)

var googleSpreadsheet = require("google-spreadsheet");
// spreadsheet key is the long id in the sheets URL
var doc = new GoogleSpreadsheet('1RsaiHU5cIHjjcJ3DoFq3w_4ht0gg7lL11xxEz12r6UU');
var sheet;

doc.getRows( 1, function(err, row_data){
 console.log( 'pulled in '+row_data.length + ' rows ')
});

I've been battling with this script for quite some time now and usually don't have issues like this.

Link to code
https://runkit.com/petetimp/59645364d639ad0011fc523a

**Comment by amenadiel** [comment]
You are importing the library with camelCase notation:

```js
var googleSpreadsheet = require("google-spreadsheet");
```

Then instancing it as 

```js
var doc = new GoogleSpreadsheet('1RsaiHU5cIHjjcJ3DoFq3w_4ht0gg7lL11xxEz12r6UU');
```
You see, there's a case mismatch. You should import it with the same name as the constructor.

```js
var GoogleSpreadsheet = require("google-spreadsheet");
```

**Comment by petetimp** [comment]
Thanks for your response amenadiel.  Just tried it out and it works .  I can't believe I spent 2 hrs+ trying to figure this out lol.

**Comment by theoephraim** [comment]
Thanks guys

FYI - I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020). **YOU MUST MIGRATE IF YOU ARE STILL USING THIS PACKAGE!**

**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

Thanks! 😄
