### ISSUE TITLE
Error: invalid_grant on domain, but in localhost works!

### ISSUE THREAD

**Issue by huesoamz** [theoephraim/node-google-spreadsheet#163]
I have a issue, My app works good in localhost but in a public domain like xxx.com doesnt work!, I debug and I find this error:

![image](https://user-images.githubusercontent.com/3308717/28589466-afa12a44-7154-11e7-9a57-6ad5c6b2a1cc.png)

Also I add the domain on 

![image](https://user-images.githubusercontent.com/3308717/28589595-2dad765e-7155-11e7-9921-9446ed3e7b83.png)

I want to say that my email part of a G Suite and I'm not the admin, but I was able to add the domain, that's matter?

Thanks in advance

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020).
**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

Not sure I understand your question fully, but please reopen the issue and add more details if it's still a problem.

Thanks! 😄
