### ISSUE TITLE
403 on all methods :-(

### ISSUE THREAD

**Issue by timdiacon** [theoephraim/node-google-spreadsheet#164]
I'm requiring JSON creds from a service worker and using useServiceAccountAuth
When I call isAuthActive() it returns true but is I try anything else like getInfo() I just get a 403 returned in the error object in the callback

**Comment by theoephraim** [comment]
Maybe you are auth-ing correctly but you don't have access to the sheet?
Did you make sure to follow step 5?
```Share the doc (or docs) with your service account using the email noted above```
Is there any more info in the error returned?

**Comment by timdiacon** [comment]
Oh wow. How did I read the instructions so many times and miss that every time?!

Shared with email and working like a charm. Apologies for being a nob... and thanks for replying so quickly 👍
