### ISSUE TITLE
Error, breaking: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by cdcv** [theoephraim/node-google-spreadsheet#167]
The module is crashing our server with the following error:

/app/bundle/programs/server/npm/node_modules/google-spreadsheet/index.js:318
var entries_xml = new_xml.match(/<entry[^>]*>([\s\S]*?)<\/entry>/g);
TypeError: Cannot read property 'match' of undefined
TypeError: Cannot read property 'match' of undefined
/app/bundle/programs/server/npm/node_modules/google-spreadsheet/index.js:318:32
Request._callback (/app/bundle/programs/server/npm/node_modules/google-spreadsheet/index.js:170:18)
Request.self.callback (/app/bundle/programs/server/npm/node_modules/google-spreadsheet/node_modules/request/request.js:188:22)
emitTwo (events.js:87:13)
Request.emit (events.js:172:7)
Request.<anonymous> (/app/bundle/programs/server/npm/node_modules/google-spreadsheet/node_modules/request/request.js:1171:10)
emitOne (events.js:77:13)
Request.emit (events.js:169:7)
IncomingMessage.<anonymous> (/app/bundle/programs/server/npm/node_modules/google-spreadsheet/node_modules/request/request.js:1091:12)
IncomingMessage.g (events.js:260:16)
emitNone (events.js:72:20)
IncomingMessage.emit (events.js:166:7)
endReadableNT (_stream_readable.js:923:12)
nextTickCallbackWith2Args (node.js:511:9)
process._tickCallback (node.js:425:17)

It's not entirely clear what call led to this.  It's likely one of:
getInfoAndWorksheets(step) {
            doc.getInfo(function (err, info) {
sheet.getRows({
rows[0].save();

Thanks for your help

**Comment by digitaljohn** [comment]
Same issue here.

**Comment by tleite** [comment]
I have a script that is downloading records and writing into a Google Sheet. I get this error when there are too many records, like over 150...

FYI, I am throttling the inserts in order to maintain the Google Sheet API limit of 1 transaction per second in 100s per user, but this error still occurs.  (https://developers.google.com/sheets/api/limits)

My solution right now is to do 100 records at a time.

Something seems to be timing out.

**Comment by quesurifn** [comment]
Same issue here @theoephraim Do you have any suggestions?

**Comment by vityas-off** [comment]
@quesurifn i fixed this with throwing an error in problem place https://github.com/vityas-off/node-google-spreadsheet/blob/master/index.js#L316
and using code like this
```js
   const addRow = async (sheet: any, data: object) => {
    for (;;) {
      try {
        await sheet.addRow(data); // this is original method wrapped with Promise
        break;
      } catch (err) {
        await new Promise(r => setTimeout(r, 1000));
      }
}````
in production with big datasheets without any issues.

**Comment by quesurifn** [comment]
@vityas-off Thank you. Why is this in an infinite loop?

**Comment by vityas-off** [comment]
@quesurifn  break if no error and wait 1 second and retry if there was an error

**Comment by quesurifn** [comment]
@vityas-off Thank you! Duh, didn't have my coffee yet.

**Comment by quesurifn** [comment]
@theoephraim One more question and I'll be done bugging you for a while. We occasionally have requests not completely go through. When I use `addRow`, I and log the rows from the callback, the request seems successful in that it give us a non error response back from google with the links and everything, but the row wasn't actually added in sheets. Do you have any ideas as to why this is?

**Comment by theoephraim** [comment]
not 100% sure but I would guess its just google's API. I've definitely noticed some odd occasional behaviour over the years while using it. Perhaps if you're adding many rows at once it could be an concurrency issue? Maybe adding each row more slowly could help?

Also the bulkupdatecells stuff works better for large updates, but it's much more awkward to use than the row-based interface.

**Comment by vityas-off** [comment]
> Perhaps if you're adding many rows at once it could be an concurrency issue?
Nope, I tested and this is just random and very rare.
But with retry workaround I'm generating ~10k rows report without any issues every day from Dec 2018 .

**Comment by quesurifn** [comment]
@vityas-off How do you know id the sheet never wrote properly?

**Comment by vityas-off** [comment]
@quesurifn i forked repo and changed code a bit to throw an error in correct place, see https://github.com/theoephraim/node-google-spreadsheet/issues/167#issuecomment-469814611 (sorry, accidentally saved file with prettier so diff not very helpful, but it's just 2 additional checks)

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020).
**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

I do believe this issue should be fixed in the new version.
Please test it out and if you find that there is still a problem, reopen the issue.

Thanks! 😄
