### ISSUE TITLE
is node-js-google-spreadsheet allow private sheet ?

### ISSUE THREAD

**Issue by zackfalcon** [theoephraim/node-google-spreadsheet#168]
Can i have access to a private spreadsheet Thanks again for your answer ?

**Comment by jwhiteaei** [comment]
Yes, as long as the credentials that are used to authenticate belong to a user to whom the private sheet is shared with. 

I've shared all my private sheets to a service worker account, and am passing those JSON credentials to node-google-spreadsheet.

Example of JSON creds:
{
  "type": "service_account",
  "project_id": "yourappName",
  "private_key_id": {your pkid here},
  "private_key": "-----BEGIN PRIVATE KEY-----{your key here}-----END PRIVATE KEY-----\n",
  "client_email": "xxx@yourappName.iam.gserviceaccount.com",
  "client_id": "111234567890000000",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/yourappName.iam.gserviceaccount.com"
}
Then pass them:
import creds from '../../creds/creds.json';
doc.useServiceAccountAuth(creds, function (err) { ... })

**Comment by theoephraim** [comment]
FYI - I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020).
**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

Thanks! 😄

**Comment by jwhiteaei** [comment]
Yes! It is fixed, thank you.

When I download the new v4 from NPM, it gives me 2.09?
I can only get 3.0 from GitHub, and it does not appear to be working anymore… I rewrote code based on new docs, but keep getting
Unhandled Rejection (TypeError): google_spreadsheet__WEBPACK_IMPORTED_MODULE_3___default.a is not a constructor

Thanks!
Jacob.

**Comment by theoephraim** [comment]
hm i just installed via npm and it seemed to work ok. Try `npm i google-spreadsheet@latest --save`

Ah I made one typo in the readme - will update now.
To import, do `const { GoogleSpreadsheet } = require('google-spreadsheet');`

**Comment by jwhiteaei** [comment]
Thank you so much!

I was able to get the latest from npm with that command.

One other thing I did have to change from the new docs is
FROM
await doc.loadInfo();
TO
await doc.getInfo();

Thanks,
Jacob.

**Comment by jwhiteaei** [comment]
Also,

Do you have any advice on CORS as it relates to this package?

I am using a service account to authorize. It was working before on localhost using Moesif CORS chrome plugin, and no problems on live site.
Now however, no such luck.

Thank you very much,
( Great job on this package BTW! And thanks for the update to V4! )
Jacob.

**Comment by theoephraim** [comment]
Good catch - please let me know if you find anything else! I was in a hurry
to finish up and publish this morning.

**Comment by theoephraim** [comment]
Hmm, I have not encountered any CORS issues at all, so I'm not really sure. Where are you getting an error?

**Comment by jwhiteaei** [comment]
OK, thanks. I’ll keep plugging away at it then. Thanks again for your help!
Jacob.

Access to XMLHttpRequest at 'https://sheets.googleapis.com/v4/spreadsheets/{mysheet}/values/{sheetname}!A1:AE1' from origin 'https://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

[cid:image002.jpg@01D5DB31.EF907580]

**Comment by jwhiteaei** [comment]
It turns out the CORS issues was a red herring.
The sheet I was reading had a forward slash in it – I renamed it, changed the slash to a hyphen, and now the CORS error is gone.

One last question –
Have you seen this before? I’m running basic code to get rows and am coming up with this error:

const doc = new GoogleSpreadsheet(googleKeys.aeipos);
await doc.useServiceAccountAuth(creds);
await doc.getInfo();
const sheet = doc.sheetsByIndex[tabNum];
const rows = await sheet.getRows();

[cid:image001.jpg@01D5DB41.71B08A50]

**Comment by theoephraim** [comment]
Hm the image isn't loading. Upload again on github directly

**Comment by jwhiteaei** [comment]
![Capture](https://user-images.githubusercontent.com/42450757/73763464-0c199d00-4737-11ea-84e7-b17a0ba503ed.PNG)

https://user-images.githubusercontent.com/42450757/73763464-0c199d00-4737-11ea-84e7-b17a0ba503ed.PNG

**Comment by theoephraim** [comment]
What are the headers in the sheet you are using

**Comment by jwhiteaei** [comment]
po	order Date	ordered By	vendor 	items received	acct PO status	description	auto fills AEI Part #		Unit & Description	category	qty	cost per unit pre-tax	calculated total per line	notes

**Comment by theoephraim** [comment]
can you share the doc temporarily with `service-account-not-exposed@future-linker-96920.iam.gserviceaccount.com` and I'll take a look

**Comment by theoephraim** [comment]
oh and email the sheet ID to `theozero@gmail.com`

**Comment by jwhiteaei** [comment]
Absolutely. Thank you -- I made a copy of the Sheet, and sent you the ID via email.

**Comment by theoephraim** [comment]
Ok so the issue is the header values are not unique. In this case it's just blank cells.
I'll add some more code to skip the blanks and to warn if there are duplicate values, but to prevent this from happening for right now, if you just put a unique header in each column, you should be ok. So those blank headers, just put a,b,c,d,e... so there is something in there.

**Comment by jwhiteaei** [comment]
Awesome! Thank you very much. It is up and working again. Thanks again!
