### ISSUE TITLE
A way to create new cells and save them or add them to bulkUpdate?

### ISSUE THREAD

**Issue by Udik** [theoephraim/node-google-spreadsheet#170]
I'm looking for a way to  allow a user to download a whole sheet, modify and add cells to it, and then save all the changes at the end (possibly with a bulk operation) to the source sheet. However I couldn't find an obvious way to create a new cell and (for example) add it to a bulkUpdateCells operation (or just call its save method). Am I missing something obvious, is there any way to do this?

**Comment by theoephraim** [comment]
You would have to fetch a larger area of the sheet that includes the currently empty cells. So lets say you have data just in a 10x10 cell area - if you can live with the limitations of modifying a 100x100 cell area, you could fetch that whole area. Then make your changes and save all the cells in a bulk operation.
