### ISSUE TITLE
Formulaes don't work when adding rows

### ISSUE THREAD

**Issue by mpcool** [theoephraim/node-google-spreadsheet#172]
I know you can add a formula to a cell, but when trying to add one to a row using just text, it doesn't work. For instance, if I try to add to the url keyword, and use
`url: "=HYPERLINK(\"http://twitter.com\", \"twitter\")"`
it doesn't work. Is there a solution to this?

**Comment by theoephraim** [comment]
Nope! The row-based API (for the version of the sheets API this module uses) does not allow editing of formulas.

I'm not sure if the newer version of the google API allows it, but when I last looked, I don't even remember seeing a "row-based" API anymore...
