### ISSUE TITLE
Troubles with Oauth

### ISSUE THREAD

**Issue by lgiraudel** [theoephraim/node-google-spreadsheet#173]
Hello,

I'm trying to create a client-side web app but I have troubles with authentication.

I followed the Authentication part from the Readme file: I created credentials for Drive API on Google Developers Console, downloaded the json file.
But when I use it in my client-side app, I have an error:
```
Fetch API cannot load https://accounts.google.com/o/oauth2/token. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

In fact it's only working when I use a plugin which adds `Allow-Control-Allow-Origin: *` in response headers (for instance: https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi)

According to Google documentation [here](https://developers.google.com/identity/protocols/OAuth2UserAgent#overview), for client-side web application I need to create an OAuth client ID instead of a Service account like mentioned in Readme file. This step allows to specify a list of domain origins.
 But this solution doesn't return a client_email + private_key I can use but returns a clientId + apiKey.

My question is: how could I use this clientId + apiKey to authenticate my requests to my spreadsheet?

Thanks for your help.

**Comment by alexkorsun** [comment]
Hi! I was wondered that this lib supports only service accounts auth. I've created PR with support of auth flow by preconfigured OAuth client with refresh token. You can take a look if you want.
https://github.com/theoephraim/node-google-spreadsheet/pull/180

**Comment by lgiraudel** [comment]
Thanks @alexkorsun, I will :)

**Comment by theoephraim** [comment]
Adding client-side oauth support and an example is on my to-do list, should get to it soon.

FYI - I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020).
**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

Thanks! 😄
