### ISSUE TITLE
row.save() strips formulas

### ISSUE THREAD

**Issue by lukedanielson** [theoephraim/node-google-spreadsheet#176]
Not sure If I'm doing it properly, but I am getting a row, saving a value in cell C2, based on it's header key ('testname'), yet the formula in R2 gets stripped and leaves just flat text value.

```js

sheet.getRows({
  offset: 1,
  limit: mylimit,
  orderby: 'testname'
}, function( err, rows ){
  console.log('Read '+rows.length+' rows');
  var row = rows[0];
  row.testname = 'test'; // 'testname' is header in column C
  row.save();
});

// Cell R2's simple formula: =P2-Q2 gets stripped
```

Any idea on the issue?  Thanks.

**Comment by theoephraim** [comment]
Unfortunately, I believe that is just how the row-based API works :(
It definitely does not support formulas, and it is extremely picky about messing with the XML.

I would recommend either using the cell-based API for the other updates, or wrap the whole thing in something that resets the formula cell (using the cell based api)after the row update
