### ISSUE TITLE
Module Parse failes

### ISSUE THREAD

**Issue by dsharu** [theoephraim/node-google-spreadsheet#178]
I just added a simple import statement 
import GoogleSpreadSheet from 'google-spreadsheet'

My compilation failed with following errors. What am I missing?

and I get a quite a few compiler error like this...

WARNING in ./~/google-spreadsheet/index.js
Critical dependencies:
59:16-30 the request of a dependency is an expression
 @ ./~/google-spreadsheet/index.js 59:16-30

WARNING in ./~/google-spreadsheet/UNLICENSE
Module parse failed: C:\personal\ReactInventory\node_modules\google-spreadsheet\UNLICENSE Unexpected token (1:5)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:5)
    at Parser.pp$4.raise (C:\personal\ReactInventory\node_modules\webpack\node_modules\acorn\dist\acorn.js:2221:15)
    .....

WARNING in ./~/google-spreadsheet/README.md
Module parse failed: C:\personal\ReactInventory\node_modules\google-spreadsheet\README.md Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '#' (1:0)
    at Parser.pp$4.raise (C:\personal\ReactInventory\node_modules\webpack\node_modules\acorn\dist\acorn.js:2221:15)
.....

WARNING in ./~/google-spreadsheet/package.json
Module parse failed: C:\personal\ReactInventory\node_modules\google-spreadsheet\package.json Unexpected token (2:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:9)
    at Parser.pp$4.raise (C:\personal\ReactInventory\node_modules\webpack\node_modules\acorn\dist\acorn.js:2221:15)
.....

**Comment by theoephraim** [comment]
Seems like an issue with your webpack setup.

FYI - I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020).
**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

Thanks! 😄
