### ISSUE TITLE
How to get Header Rows of Sheet?

### ISSUE THREAD

**Issue by joshuaquek** [theoephraim/node-google-spreadsheet#179]
Hello, how do I get the header rows of a sheet? Hope to hear from you soon!

**Comment by theoephraim** [comment]
Assuming there is some data in the sheet, you could just fetch a row and then look at the keys. Otherwise you could fetch the first row `getCells` to fetch the first row using the "cell based" api.

**Comment by joshuaquek** [comment]
Yeap, I used the cell API in the end. Thanks!
