### ISSUE TITLE
Sorry, it is not possible to delete all non-frozen rows

### ISSUE THREAD

**Issue by EdmundMai** [theoephraim/node-google-spreadsheet#186]
Clearing a sheet does not work:
```

      ctx.sheet.clear(err => {
        console.log("CLEAREDDDDDDDDDD: ", err);
      });
```
```

info: CLEAREDDDDDDDDDD:  Error: HTTP error 400 (Bad Request) - Sorry, it is not possible to delete all non-frozen
 rows.

```

**Comment by leogaldioli** [comment]
Have you solved this problem?

**Comment by dreftymac** [comment]
following

**Comment by muhammadzklugo** [comment]
any update on this? I am also facing same issue

**Comment by boutdemousse** [comment]
Faced the very same problem today but there is nothing wrong with this library.

Same behavior in the Spreadsheet UI : you must keep a non-frozen row right after the frozen one.
Solution : insert a new row then delete the previous one.

**Comment by theoephraim** [comment]
Yep - sounds like a google sheets issue.

FYI - I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020).
**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

Thanks! 😄
