### ISSUE TITLE
How to detect change on spreadsheet?

### ISSUE THREAD

**Issue by artofspeed** [theoephraim/node-google-spreadsheet#187]
Is there a way to detect when the spreadsheet is changed?

**Comment by theoephraim** [comment]
I think it's possible if you set up webhooks, which is outside the scope of this project, as it is not part of the sheets API.

FYI - I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020).
**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

Thanks! 😄
