### ISSUE TITLE
Callbacks for del() and save() 

### ISSUE THREAD

**Issue by joshuaquek** [theoephraim/node-google-spreadsheet#189]
Would it be possible to add completion callbacks for the del() and save() functions?

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020).
**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

The new api is promise based, so this should no longer be a problem.

Thanks! 😄
