### ISSUE TITLE
Find a row based on a predicate

### ISSUE THREAD

**Issue by Vadorequest** [theoephraim/node-google-spreadsheet#192]
If there is any way to find a specific raw (find) or group of rows (filter) using one (or several) of the attribute(s) (ID) as a predicate it would be very useful.

**Comment by JulienD** [comment]
Hi,

Before adding new values I needed to search if the value was already in the spreadsheet. I used the [structured query filter](https://developers.google.com/google-apps/spreadsheets/data#send_a_structured_query_for_rows) (that do not exist anymore in v4) 


See `workingWithRows` in the function `sheet.getRows` where I define the `query` param with some param. 

You can use `>`, `<` and `=` for you criteria.

```javascript
var GoogleSpreadsheet = require('google-spreadsheet');
var async = require('async');

// spreadsheet key is the long id in the sheets URL
var doc = new GoogleSpreadsheet('<spreadsheet key>');
var sheet;

async.series([
  function setAuth(step) {
    // see notes below for authentication instructions!
    var creds = require('./google-generated-creds.json');
    // OR, if you cannot save the file locally (like on heroku)
    var creds_json = {
      client_email: 'yourserviceaccountemailhere@google.com',
      private_key: 'your long private key stuff here'
    }

    doc.useServiceAccountAuth(creds, step);
  },
  function getInfoAndWorksheets(step) {
    doc.getInfo(function(err, info) {
      console.log('Loaded doc: '+info.title+' by '+info.author.email);
      sheet = info.worksheets[0];
      console.log('sheet 1: '+sheet.title+' '+sheet.rowCount+'x'+sheet.colCount);
      step();
    });
  },
  function workingWithRows(step) {

    let query = "firstname=foobar AND lastname=barbaz"

    // google provides some query options
    sheet.getRows({
      offset: 1,
      limit: 1,
      orderby: 'col2',
      query: '(' + query + ')'
    }, function( err, rows ){
      console.log('Read '+rows.length+' rows');

      // the row is an object with keys set by the column headers
      rows[0].colname = 'new val';
      rows[0].save(); // this is async

      // deleting a row
      rows[0].del();  // this is async

      step();
    });
  }
], function(err){
    if( err ) {
      console.log('Error: '+err);
    }
});
```

**Comment by Vadorequest** [comment]
@JulienD thanks for the example, I also found out about the structured query filter but couldn't make it work, (lack of example ?) even though my request was quite simple.

I eventually ended up loading all results and .find them to find my row and update it. I'll give it another try, thanks!

**Comment by theoephraim** [comment]
FYI - I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020).
**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

The new v4 api does not include support for structured queries, so your approach of fetching everything and then checking is the only way.

Thanks! 😄

**Comment by lsbyerley** [comment]
@theoephraim sorry to comment on a closed issue but I didn't want to open a new one for just a question. My question is in regards to your comment of "fetching everything and then checking". I need to load around 6000 cells and then find an ID in one of the cells. How do I load all the cells into an array? I realize I can load all the cells like so:

```
await someBigSheet.loadCells('A1:A5248');
```

But how would I load those into an array?

**Comment by StErMi** [comment]
I'm also looking for a solution like this

**Comment by theoephraim** [comment]
so you can only access cells that you have loaded. If you load `A1:A100` you can loop through grabbing A1, A2, etc... and you should only get an error if you hit a cell that was not actually loaded.

Otherwise if you want to just go over the loaded cells, you could potentially loop over `worksheet._cells`
Its a sparse array of arrays with cells zero-indexed by row/column.
Perhaps adding a new getter which handles this logic and just returns a single array of loaded cells would be helpful?

Should be pretty easy to implement. I think `_.compact(_.flatten(worksheet._cells))` might even do it. (flatten combines the nested arrays, compact removes empty values)

**Comment by StErMi** [comment]
How viable is this solution if you need to search for a value in more than 150k rows?
