### ISSUE TITLE
[help] download as csv

### ISSUE THREAD

**Issue by bretthadley** [theoephraim/node-google-spreadsheet#194]
Is there a way to just bulk grab entire sheet so I can construct a csv file to save?

**Comment by MaksimKiselev** [comment]
I researched this question and found this workaround https://stackoverflow.com/a/51235960/2445656

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020).
**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

You should be able to grab the whole sheet by just calling `sheet.loadCells()`

Thanks! 😄

**Comment by crushton-qg** [comment]
Hi @theoephraim, I know this is an old issue, however sheet.loadCells() returns undefined.

I am trying to load the sheet data into an object so I can convert it to CSV format. I can't find anything in the docs that suggests this is possible already, can you enlighten me?

Thanks

**Comment by theoephraim** [comment]
Look closely at the examples. loadCells doesn’t return the cells it loads, but it populates a cache managed by the sheet object. You can get individual cells after loading them by calling sheet.getCell

**Comment by theoephraim** [comment]
Looking at the stackoverflow link above, it looks like there could be a nice way to export as Csv directly rather than fetching the data and building it yourself. I may add that functionality soon ( and open to PRs)

**Comment by theoephraim** [comment]
@crushton-qg  - just released a new version with export methods, for example:
- https://theoephraim.github.io/node-google-spreadsheet/#/classes/google-spreadsheet-worksheet?id=fn-downloadascsv
