### ISSUE TITLE
Creating a sheet?

### ISSUE THREAD

**Issue by dmead** [theoephraim/node-google-spreadsheet#197]
Is there an example on creating a new sheet?

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020).
**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

`doc.addSheet()` is available and should be clear in the new docs.
Please test it out and if you find that there is still a problem, reopen the issue.

Thanks! 😄
