### ISSUE TITLE
when a new version planned?

### ISSUE THREAD

**Issue by Shemesh** [theoephraim/node-google-spreadsheet#203]
hi @theoephraim 

currently there are 11 open pull requests that awaiting a merge.
+ the current version was released a long time ago.

when is a new version planned to be released?

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020).
**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

Thanks! 😄
