### ISSUE TITLE
Please upgrade your google-auth-library for security reasons

### ISSUE THREAD

**Issue by FranciscoG** [theoephraim/node-google-spreadsheet#205]
https://snyk.io/test/npm/google-spreadsheet/2.0.4?severity=high&severity=medium&severity=low

> **MEDIUM SEVERITY**
> ### Uninitialized Memory Exposure
> **Vulnerable module:** tunnel-agent
> **Introduced through:** google-spreadsheet@2.0.4 › google-auth-library@0.9.10 › request@2.74.0 › tunnel-agent@0.4.3
> **Remediation**: Upgrade to google-auth-library@0.10.0.

**Comment by josh-renton** [comment]
+1

**Comment by jpike88** [comment]
@theoephraim this is extremely important, can you please say whether or not you're going to attend to this? Otherwise I'm going to fork

**Comment by jpike88** [comment]
https://github.com/theoephraim/node-google-spreadsheet/pull/208

@theoephraim I made this easy for you, all you have to do is npm publish

**Comment by josh-renton** [comment]
Isn't it worth moving to v 1.x ? Does the move to 0.10.0 actually cover all
the security issues with google-auth-lib?

**Comment by jpike88** [comment]
@theoephraim you're active on Github... can you just pass contributor/npm status onto someone who will put in the 5 mins of effort to publish an update?

**Comment by theoephraim** [comment]
My bad guys. For some reason I had notification emails off.
I will fix this ASAP.

**Comment by jpike88** [comment]
you're a legend, thanks!

**Comment by FranciscoG** [comment]
no worries!!  Thanks for updating.

**Comment by josh-renton** [comment]
Thanks so much for this.
