### ISSUE TITLE
Is there a way to exclude empty columns from counting ?

### ISSUE THREAD

**Issue by muayyadayesh** [theoephraim/node-google-spreadsheet#207]

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020).
**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

The new api has `sheet.cellStats.nonEmpty` which can tell you about non-empty cells.
Please test it out and if you find that there is still a problem, reopen the issue.

Thanks! 😄
