### ISSUE TITLE
Authentication using Application Default Credentials

### ISSUE THREAD

**Issue by anantakrishna** [theoephraim/node-google-spreadsheet#215]
Hello.

Trying to authenticate GoogleSpreadsheet with an application default credentials as described here: 
https://github.com/googleapis/google-auth-library-nodejs#application-default-credentials

Here is my code:
```
    const auth = await google.auth.getClient({
      scopes: ["https://www.googleapis.com/auth/spreadsheets"]
    });

    const doc = new GoogleSpreadsheet(
      "MY_SPREADSHEET_ID",
      auth
    );
```

And getting `Error: Sheet is private. Use authentication or make public. (see https://github.com/theoephraim/node-google-spreadsheet#a-note-on-authentication for details)`. This link does not clarify on the app default credentials.

**Comment by theoephraim** [comment]
Thanks - this is on my to-do list.

but just FYI - I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020).
**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

**Comment by tomashejatko** [comment]
This will help a lot with how we use GCP in our company. Also this enables to decouple users' from SA access control to Sheet

**Comment by theoephraim** [comment]
this is done - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication?id=adc
