### ISSUE TITLE
getRowBy(sheetId) or getRowBy(sheetName) or getSheet(byId) or getSheet(byName) because I have more than 15 Sheet in on Single spreadsheet

### ISSUE THREAD

**Issue by momin96** [theoephraim/node-google-spreadsheet#219]
Hi, 
I have more than 15 sheets in the single spreadsheet & frequently modify the order of these sheets, 
It looks like I dont have any options to get a signle sheet by Name of Id

```
sheet.getRows(2, function(error, rows) {
                console.log(rows)
            })
```

**Comment by phong-et** [comment]
> Hi,
> I have more than 15 sheets in the single spreadsheet & frequently modify the order of these sheets,
> It looks like I dont have any options to get a signle sheet by Name of Id
> 
> ```
> sheet.getRows(2, function(error, rows) {
>                 console.log(rows)
>             })
> ```

have you solved your problem yet ?

**Comment by fabrizio5680** [comment]
You can do something similar to this below, where title can be id or whichever property and in the find predicate change the condition
```
function getByName(title) {
	return new Promise((resolve) => {
		doc.getInfo(function(err, info) {
			if (err) {
				return reject(err);
			}
	      	sheet = info.worksheets.find(w => w.title === title);
	      	return resolve(sheet)
	    });	
    })
}
```

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020).
**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

You can use the new `doc.sheetsById` property to get a specific sheet using the id.
Please test it out and if you find that there is still a problem, reopen the issue.

Thanks! 😄
