### ISSUE TITLE
No ability to resize columns

### ISSUE THREAD

**Issue by jakexconniff** [theoephraim/node-google-spreadsheet#222]
Wondering if there has been any thought given to adding the ability to resize the height/width of invidual columns to this project.

**Comment by theoephraim** [comment]
I dont believe the v3 api has any ability to change formatting or anything like that. Not sure if the new version of the API does.

**Comment by FunctionDJ** [comment]
We can now in v4 🎉 https://stackoverflow.com/a/49971230
