### ISSUE TITLE
reading another sheet by identifier not index?

### ISSUE THREAD

**Issue by dcsan** [theoephraim/node-google-spreadsheet#23]
is there a way to specify a tab (a sheet within the document) by identifier?

// # is worksheet id - IDs start at 1

since tabs get shifted around it would be better to use the gid param like '1095636746' than a simple left to right ID. I tried to pass that and it currently errors out.

**Comment by slavafomin** [comment]
+1

**Comment by theoephraim** [comment]
So I believe you can pass in the sheet's ID _or_ the index. It's the ID you get when fetching the sheets, not necessarily what you see in the URL while using the google sheets web interface.

But either way, it may just make more sense to call `getInfo` first to get all the sheets, find the one you want using the title or the ID, and then work on the sheet object directly!

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020). **YOU MUST MIGRATE IF YOU ARE STILL USING THIS PACKAGE!**

**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

New version has `doc.sheetsById` that you can use

Thanks! 😄
