### ISSUE TITLE
Is there a way to copy a sheet to another worksheet?

### ISSUE THREAD

**Issue by CyrisXD** [theoephraim/node-google-spreadsheet#230]
Looking to copy a sheet as is, to a different worksheet. Currently working on copying cells but there might be an easier way?

**Comment by theoephraim** [comment]
not that I know of. A bulk cell update should be able to do it pretty easily though, no?

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020).
**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

The new api does have this available
check it out https://theoephraim.github.io/node-google-spreadsheet/#/classes/google-spreadsheet-worksheet?id=fn-copytospreadsheet

Thanks! 😄
