### ISSUE TITLE
500 errors?

### ISSUE THREAD

**Issue by coffenbacher** [theoephraim/node-google-spreadsheet#231]
Is anyone else getting 500 errors today? I have monitoring set up, so I can say this is a rare occurrence whatever it is, but the Google feeds endpoint just seems dead today.

Edit: starring this issue might be the most helpful thing -> https://issuetracker.google.com/issues/131613284

**Comment by leopangan** [comment]
Yes I am getting 500 errors too

**Comment by creazy231** [comment]
Same here using `google-spreadsheet-to-json` module /:

**Comment by maxigimenez** [comment]
Same here, also using `google-spreadsheet-to-json`

**Comment by UnbearableBear** [comment]
I am getting a 500 on ALL my attempts today :(

**Comment by keysdota2ru** [comment]
same problem

**Comment by Lapinou42** [comment]
Same here !

**Comment by takwing** [comment]
same here!!

**Comment by theoephraim** [comment]
Hey everyone - looks like this is a wider issue that has been reported. Hopefully they will fix soon
https://issuetracker.google.com/issues/131613284

**Comment by theoephraim** [comment]
Closing this now, as I'm hearing things are resolved. Although it may take some time for whatever fix they deployed to roll out across their entire infrastructure.

**Comment by jjhesk** [comment]
same here!!
