### ISSUE TITLE
cant get image url

### ISSUE THREAD

**Issue by BrunoPuccio** [theoephraim/node-google-spreadsheet#233]
is it possible to get the url of an image that is inside the cell?
when i print the row the cell that haves the image is shown empty

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020).
**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

If you use the cell-based methods, you should be able to get all of the info about the cell.
Please test it out and if you find that there is still a problem, reopen the issue.

Thanks! 😄
