### ISSUE TITLE
setHeaderRow is not a function?

### ISSUE THREAD

**Issue by AncientYears** [theoephraim/node-google-spreadsheet#234]
![image](https://user-images.githubusercontent.com/32402548/57974333-7bcfd800-79ae-11e9-994f-cc463a69f602.png)

    doc.useServiceAccountAuth(credSecret, function (err0) {
        doc.getRows(1, function (err2, rows) {

            doc.getCells(1, function (err1, cells) {
                for (i = 2; i <= rows.length + 2; i++) {
                    doc.setHeaderRow(['name', 'age', 'phone']);    
      
                    doc.addRow({"product": "Product example", "product_id": 5 }, function(err, row) {
                      console.log("err", err);
                    });
              
                    console.log(discordID)
                }
            })
        })
    })

Some temporary testing...

**Comment by dimkir** [comment]
Hello, I am trying to get better understanding of your question. Indeed there seem to exist some limitations of how `addRow()` works (see screenshot of README below).  Especially when adding rows with columns which were originally not present on the header row...

![image](https://user-images.githubusercontent.com/3438798/58338581-e4e89d00-7e3f-11e9-8bb0-02b135ffee51.png)


It would be helpful if you can clarify your intention. I tried to make few guesses myself, but can't decide on which one applies the most to you:
 - edit/append the header row of the existing sheet 
 - add header row to the blank new sheet
 - check if the header row is set (any sheet)
 - adding new row with columns which are not originally present in the header row

**Comment by AncientYears** [comment]
Whilst writing this problem I was indeed trying to add a new header row to a blank new sheet @dimkir 

However, on another note:

`
                                                        doc.addRow(1, { DiscID: "1234", USER: "Test", RobloxID: "1234"}, function (err, rows) {
                                                            if (err) console.log(err);
                                                        })
`

This does work about 50% of the time, however, it also errors with access denied the other 50% of the time... The Google service account does have edit access to the document as well.

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020).
**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

The new docs should make this all a bit clearer I hope.

Thanks! 😄
