### ISSUE TITLE
addWorksheet method fails: this.isAuthActive is not a function

### ISSUE THREAD

**Issue by xhalo32** [theoephraim/node-google-spreadsheet#235]
Running the following code on Node.js v10.16.0:
```javascript
const Gss = require('google-spreadsheet');
const { promisify } = require('util');
const creds = require('./client_secret.json');

const main = async () => {
  const sheetId = '<sheet id>';
  const doc = new Gss(sheetId);
  await promisify(doc.useServiceAccountAuth)(creds);

  const sheet = await promisify(doc.addWorksheet)({
    title: 'test',
  });
};

main();
```
fails with
```
(node:13279) UnhandledPromiseRejectionWarning: TypeError: this.isAuthActive is not a function
    at GoogleSpreadsheet.addWorksheet (/home/niklash/standup-query-bot/bot/node_modules/google-spreadsheet/index.js:225:15)
```
google-spreadsheet version is: 2.0.7

**Comment by xhalo32** [comment]
Seems to be a problem while promisifying `doc.addWorksheet` function. Using callbacks works fine.

**Comment by xhalo32** [comment]
Calling `.apply(doc, options)` on the promisified function solved my problem.

**Comment by amrshakya** [comment]
@xhalo32 can you share your code how it worked for promisify? i tired still not working.

**Comment by amrshakya** [comment]
@xhalo32 .call() worked thanks. but can you explain a bit how it worked?

**Comment by xhalo32** [comment]
The issue was that the promisified method did not have `this` bound which the function requires, i.e. I was trying to use the method like a static class method. Thus when I bound the doc as `this` using `.call` it worked like an ordinary non-static method call.
I suppose `doc.useServiceAccountAuth` does not use `this` and that's why it worked without the bound context. Classic javascript

**Comment by baruchiro** [comment]
@amrshakya can you share your code how it worked for `.call`? i tired still not working.

**Comment by baruchiro** [comment]
I think:
Before:
```node
promisify(doc.addWorksheet)(options)
```
After:
```node
promisify(doc.addWorksheet).call(doc, options)
```
