### ISSUE TITLE
addRow sends malformed requests

### ISSUE THREAD

**Issue by xhalo32** [theoephraim/node-google-spreadsheet#236]
I have inserted `console.log(data_xml)` in index.js after line 323.
When I run
```javascript
worksheet.addRow({
  'data:with>xml<lol': 'test',
})
```
I can see from the console that it creates the following element
```xml
<gsx:data:with>xml<lol>test</gsx:data:with>xml<lol>
```
Which then causes a bad request to trigger in Google's API which I can see in the error that `addRow` throws.

**Comment by vinodhreddygs** [comment]
How do I use trim function in query to read data from spread sheet?
please comment here if you know answer.

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020).
**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

The new API is json based so you can put whatever xml stuff you want in there.
Please test it out and if you find that there is still a problem, reopen the issue.

Thanks! 😄
