### ISSUE TITLE
can't get credentials to work

### ISSUE THREAD

**Issue by bryanrasmussen** [theoephraim/node-google-spreadsheet#238]
Is the project handling of credentials out of date? 

I made a private worksheet at https://docs.google.com/spreadsheets/d/19BPO0NxyMebE1MqH3uhCfQRlNycSDQNS-wm0ldOPVS4/

created my spreadsheet with new GoogleSpreadsheet("19BPO0NxyMebE1MqH3uhCfQRlNycSDQNS-wm0ldOPVS4");

I went and generated the credentials for the google drive api, but the properties in the json do not look like the example creds_json you were using in the code example, my json has properties like 
type
project_id
private_key_id
private_key
client_email
client_id
auth_uri
token_uri
auth_provider_x509_cert_url
client_x509_cert_url

your code example only has the client_email and the pviate_key properties. 

another question, the property of client email was autogenerated when I imported the drive api into my project, is this is what is going wrong (that is to say I should use my email, but then why does it autogenerate? ) or should I perhaps be able to log in to a drive account with that client_email now - but if so what would the password be?

**Comment by bryanrasmussen** [comment]
if I put my email in instead of the autogenerated one it gives the error
Error: Error: invalid_grant: Robot is missing a project number.

**Comment by manasouza** [comment]
The `client_email` attribute on credentials is the related service account.
Check for **service account** concepts and how it works into Google Platform

**Comment by jasonhargrove** [comment]
Very easy to miss this instruction (I did myself):

`Share the doc (or docs) with your service account using the email noted above`

**Comment by MichaelCastelbuono** [comment]
I was having the same problem and this tip helped. Thanks.

**Comment by theoephraim** [comment]
Thanks folks. I'll try to make sure it's clear in the docs.
