### ISSUE TITLE
Date field returns formatted date rather than date object

### ISSUE THREAD

**Issue by danielharrison** [theoephraim/node-google-spreadsheet#239]
A date type field returns what's visible to the user in the sheet rather than a date/time object, which would be preferable as the human readable date is nice to have on the sheet but annoying to use in an app, and vice versa.

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020).
**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

If you use the cell-based methods, you can read the actual value and the formatted value separately, which it sounds like is what you want. The row based methods use google's simpler API endpoints which just return a single formatted value.

Thanks! 😄
