### ISSUE TITLE
Asynchronous Maybe

### ISSUE THREAD

**Issue by NohSeungWon** [theoephraim/node-google-spreadsheet#245]
Hi i`m a beginner. i have a little problem (currently solved)
I am not good at English, so I am not sure if it will be delivered well.
anyway

my code 
``` javascript
cell[0].value = '=spreadSheet funtion';
cell[1].value = '=spreadSheet funtion';

await cell.[0].save();
await cell.[1].save();
```

The spreadsheet has been updated with the code above.
I'll call you back to the next code.
``` javascript
// i expect 
await getCells() // => result : ['1','2','3','4']
// result 
await getCells()  // => result : ['loding..', 'loding'.., '1', '2'];
```

Even if I checked that the spreadsheet was updated, it was the same.
The same is true of executing the code in five seconds.
after a long thought
``` javascript
cell[0].value = '=spreadSheet funtion';
cell[1].value = '=spreadSheet funtion';
sheet.bulkUpdateCells(cells); 
```
As I wrote it in the above code, I got the expected result.

so, Did I write the wrong code?
or Is it related to sync of save function?

thank you

**Comment by theoephraim** [comment]
You didn't do anything wrong. The old version of this module was callback based, so async/await did not work.

But, I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020).
**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

Please test it out and I think you'll find it easier to use.

Thanks! 😄
