### ISSUE TITLE
Sheets v4 API upgrade

### ISSUE THREAD

**Issue by jbskies** [theoephraim/node-google-spreadsheet#246]
Google warn that the API in use is Sheet v3.  It will be retired on March 3, 2020.
Can someone please upgrade to the new API v4?

----
Hello Sheets Developer,

We're writing to let you know that Google Sheets v3 API will be shut down on March 3, 2020.

What do I need to know?
The Sheets v4 API, launched in 2016, opened new doors to custom development with programmatic access to critical features like conditional formatting, charts and pivot tables. Since then, we’ve continually improved version 4 by supporting new Sheets features and introducing developer metadata.

As part of the migration to the Sheets v4 API, we will shut down the Sheets v3 API on March 3, 2020.

What do I need to do?
To ensure projects originally built on the Sheets v3 API continue working long after it is gone, please migrate your projects (listed below) to the Sheets v4 API before March 3, 2020.

You can review this migration guide which provides tips on how to transition your apps, including a mapping of operations in Sheets v3 API to operations in Sheets v4 API and some ideas for using the new functionality to your advantage.

Note that the Sheets v4 API does not provide the “List spreadsheets for the authenticated user" operation. However, this operation can be replicated via the Drive API Files.list method.
We have identified that the following projects have used the Sheets v3 API in the past 30 days:

google-sheet-access (stalwart-kite-221020)
Need help?
Additional documentation is available to help you get started on a new project or leverage the content and appearance controls not available in previous versions.
Please bear in mind that after March 3, 2020, the Sheets v3 API will no longer be supported.

Thanks for being a valued Sheets Developer.

Sincerely,

The Sheets API team

**Comment by manasouza** [comment]
There's already a discussion at [#193](https://github.com/theoephraim/node-google-spreadsheet/issues/193)

**Comment by kumur** [comment]
Please let me know your NPM 'google-spreadsheet' is using Google Sheets v3 API or Google Sheets v4 API

**Comment by yamsellem** [comment]
@kumur you may take a look at #193, in short, `google-spreadsheet` is using Google Sheets v3 API.
