### ISSUE TITLE
Add formatting to rows

### ISSUE THREAD

**Issue by Slyke** [theoephraim/node-google-spreadsheet#252]
This has been annoying me for ages.
I'm trying to place in a ISO8601 type string into a cell. For some reason google spreadsheets is changing `2019-10-26 20:06:46` to `2019-10-26 0:06:46`, it's also doing other weird stuff, like making the first part of the date swap the months and days around.

This is because the field is set to Automatic type, and any new rows that are added do not inherit their  predecessor's format.

I also tried lots of things like putting spaces around the ends, multiple spaces in the middle and that too. It's either stripped out, or just formatted weirdly.

**Comment by Slyke** [comment]
Seems like it's doable:
https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/batchUpdate

https://developers.google.com/sheets/api/guides/formats

**Comment by boutdemousse** [comment]
While having trouble with phone numbers, adding a single quote force a string type casting. 
You could try inserting `'2019-10-26 20:06:46`, it should work.

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020).
**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

This new version has the ability to edit the formatting for the cells.
Please test it out and if you find that there is still a problem, reopen the issue.

Thanks! 😄
