### ISSUE TITLE
doc.getInfo working on MacOS but not on Windows

### ISSUE THREAD

**Issue by nooxx** [theoephraim/node-google-spreadsheet#253]
Hi,

I've got a script pulling content from a google-sheet and it's working totally fine on mac os but not on windows 10.

Here's what my script looks like:

```
#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const GoogleSpreadsheet = require('google-spreadsheet');

const doc = new GoogleSpreadsheet('...');

const credentialsJSON = {
    ...
};

doc.useServiceAccountAuth(credentialsJSON, () => {
    console.log("Inside doc.useServiceAccountAuth");
    doc.getInfo((err, info) => {
        console.log("Inside doc.getinfo");
        if (err) {
            return console.error(err);
        }

        ...
    });
});
```
On windows, the code stops inside useServiceAccountAuth and only logs "Inside doc.useServiceAccountAuth" without logging any error.

I use the latest version of the package.
Node version: 12.13.0
NPM: 6.12.0

Any idea?

Thanks

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020).
**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

Please test it out and if you find that there is still a problem, reopen the issue.

Thanks! 😄
