### ISSUE TITLE
Row update clears the formulas in the cells of the row

### ISSUE THREAD

**Issue by rajavijayavendan** [theoephraim/node-google-spreadsheet#257]

**Comment by rajavijayavendan** [comment]
Row update clears the formulas in the cells of the row even though I update a cell which doesn't possess a formula. Is it a bug?

**Comment by theoephraim** [comment]
This was not a bug, it is a limitation of using the "row-based" api interactions with google.
If you want to use formulas and update cells, you must use the cell-based methods.

I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020).
**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

This is still the case with the new version as the row-based calls use a simpler API endpoint where google only returns you the value without any formula info.

Thanks! 😄
