### ISSUE TITLE
[Question] Can I update row with new header?

### ISSUE THREAD

**Issue by baruchiro** [theoephraim/node-google-spreadsheet#259]
Say I have this worksheet:

| header1 | header2 |
| -- | -- |
| value1 | value2 |

Now, I want to add value to my row:

```js
console.log(row[0].header1) // value1
console.log(row[0].header2) // value2
row[0].header3 = 'value3
row[0].save()
```
And I want the worksheet will be:

| header1 | header2 | header3 |
| -- | -- | -- |
| value1 | value2 | value3 |

Is it possible?

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020).

Docs available here - https://theoephraim.github.io/node-google-spreadsheet

Yes, you can set a new header row using the `sheet.setHeaderRow()` function

Thanks! 😄

**Comment by baruchiro** [comment]
Oh, It might be good, but I just finished to replace your old version with my implementation with `v4`.
