### ISSUE TITLE
getInfo returning undefined

### ISSUE THREAD

**Issue by antoniop-lm** [theoephraim/node-google-spreadsheet#260]
Since the email from Google warning about the Sheets v4 API upgrade, every time I try to access a spreadsheet the `getInfo` method returns undefined. No changes made to my code that worked perfectly before.

It may be a problem with my credentials or someone had this problem too?
I'm using Service Account authentication.

**Comment by jasonhargrove** [comment]
I am trying this library for the first time and that method does return null. It must be modifying the doc object because it works.

```
  const util = require('util');
  const auth = {
    client_email: xxxxx,
    private_key: xxxxxxxx
  };
  const sheet_id = xxx;
  const GoogleSpreadsheet = require('google-spreadsheet');
  const doc = new GoogleSpreadsheet(sheet_id);
  await util.promisify(doc.useServiceAccountAuth)(auth);
  const info = await util.promisify(doc.getInfo)();
```

(Note I am using util promisify to defeat the very oldschool callbacks, no bearing on issue.)

**Comment by antoniop-lm** [comment]
Sorry, actually when I was writing the issue I was thinking about other method and explained all wrong. The function that is returning undefined is getInfo after validating it. Error returns "incorrect header check".

**Comment by antoniop-lm** [comment]
Issue #220 had the solution to this.
