### ISSUE TITLE
Some empty rows causes getRows() to return 0 results for entire sheet

### ISSUE THREAD

**Issue by jasonhargrove** [theoephraim/node-google-spreadsheet#261]
Some empty rows causes `getRows` to return an empty array, despite there being data on 2 of 4 rows.

- rows 2 and 3 were empty, with data on rows 1 and 4, resulting in no data being returned
- removing rows 2 and 3 resulted in data being returned

Opinion: Workaround is not a solution
- people use empty rows
- API user may not have ability to remove empty rows, even if they wanted to

Duplicate issue: https://github.com/theoephraim/node-google-spreadsheet/issues/184 (Opened new issue because the other's title is unclear, and the issue is years old)

**Comment by gsrp-tristen** [comment]
+1

**Comment by leonrustmeier** [comment]
+1 I have the same problem in my project so now i have to change the sheet :/

**Comment by theoephraim** [comment]
This was always an issue with google's row-based interface :(

BUT - I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020).

Docs available here - https://theoephraim.github.io/node-google-spreadsheet

And the new module uses their new api which no longer has this issue and empty rows will be fetched. Please test it out and if you find that there is still a problem, reopen the issue.

Thanks! 😄
