### ISSUE TITLE
Property rowCount issue

### ISSUE THREAD

**Issue by vinodhreddygs** [theoephraim/node-google-spreadsheet#262]
In the SpreadsheetWorksheet object, property rowCount includes the empty rows of spread sheet as well. Is there any way to get rowCount where rows are not empty?

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020).

Docs available here - https://theoephraim.github.io/node-google-spreadsheet

The `rowCount` as defined by google is the entire sheet.
With the new api, you can fetch the rows and then filter out the empty ones as you see fit.
Please test it out and if you find that there is still a problem, reopen the issue.

Thanks! 😄

**Comment by vinodhreddygs** [comment]
Hi,

To set formulas to the cell from programmatically, we should need the index
of the row.
Can we able to get a record/row with it's row index? Please let me know in
this thread.

Thanks,
Vinodh Kumar G S
