### ISSUE TITLE
While setting formula to the cell, how to get index of that row in which the cell present.

### ISSUE THREAD

**Issue by vinodhreddygs** [theoephraim/node-google-spreadsheet#265]
To set formula we should know the index to mention in the formula.
Ex: If I want to add a columns data( from T to V) in the 3rd row. I need to set cell formula as: 
       =SUM(T3:V3)
To do so, how should I get rowIndex of that cell?

Thanks in advance.

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020).

Docs available here - https://theoephraim.github.io/node-google-spreadsheet

You can access the a1 style row and column info for the cell fairly easily using `cell. a1Row` and `cell.a1Column`
Please test it out and if you find that there is still a problem, reopen the issue.

Thanks! 😄
