### ISSUE TITLE
Easy way of getting the serial number for the inserted row

### ISSUE THREAD

**Issue by vinodhreddygs** [theoephraim/node-google-spreadsheet#268]
Hi,

I don't want to call getRows() function and then calculate the rows length each time, while inserting the rows to the spread sheet.

Is there any easy way to find the index of the newly inserted row?.

Thanks in advance.

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020).

Docs available here - https://theoephraim.github.io/node-google-spreadsheet

While google does not provide an ID number, the new API does provide a `rowIndex` associated with the new row.

Thanks! 😄
