### ISSUE TITLE
SpreadsheetCell Class Help

### ISSUE THREAD

**Issue by samperlmutter** [theoephraim/node-google-spreadsheet#27]
This may not be the appropriate place to post this and if it isn't please direct me to the place that is, but I'm having trouble understanding how I can edit the value of a spreadsheet's cell and from what I can see there seems to be very little documentation on the module as a whole. I'm trying to set the data in one of the spreadsheet's rows to an array, i.e. cell A2 is array[0], B2  is array[1], etc., but the only thing I've been able to do successfully is add rows and I want to be able to do 
```
for (var i = 0; i < rowData[rowData.length - 1].length; i++) {
    spreadsheet.addRow(1, {columnName[i]:rowData[rowData.length - 2][i]});
}
```
except instead of adding a row with one cell with data like this does, I want to be able to add one row and fill it with all the elements of the last element of `rowData[][]`. Once again if this is not the appropriate place to post this please let me know and point me to the correct place. Thanks!

**Comment by theoephraim** [comment]
You lost me... Are you trying to add a new row, or edit an existing row?

**Comment by samperlmutter** [comment]
Sorry, I have a 2-dimensional array called `rowData[rowNumber][rowData]` and I have a 1-dimensional array for the names of the rows (the strings in the first row) called `headers[]`. I want to add one row that has all the data in the second dimension of rowData, but what I've ended up doing is creating a loop that adds 42 rows (because headers and rowData's second dimension have a length of 42).

**Comment by theoephraim** [comment]
so this is designed to be used with a sheet that has meaningful column headers. So for example, if your sheet looked like 
```
name   | age
theo   | 27
bob    | 22
```

you can add a new row by doing something like

`sheet.addRow(1, { name: 'sally', age: 32 })`

Or to edit an existing row you would do something like:
```
sheet.getRows(1, function( err, rows ){
  rows[0].name = 'theodore';
  rows[0].save();
});
```
So you see you have to build an object with the keys being the row headers and then call addRow passing the entire object.

```
var lastRow = rowData[rowData.length - 1];
var rowObject = {};
for (var i=0; i<lastRow.length; i++){
  rowObject[ headers[i] ] = lastRow[i];
}
spreadsheet.addRow( 1, rowObject );
```


ALSO SIDENOTE: In these cases, the "1" in those calls is telling it to use the first worksheet (tab) in your spreadsheet. However you can also get a reference to the worksheet itself and then omit the index in your calls. For example:
```
spreadsheet.getInfo( function( err, sheet_info ){
  var sheet1 = sheet_info.worksheets[0];
  sheet.getRows(...);
  sheet.addRow(...);
});
```
