### ISSUE TITLE
Insert rows one by one when multiple requests comes at the time time

### ISSUE THREAD

**Issue by vinodhreddygs** [theoephraim/node-google-spreadsheet#271]
Hi,

How to achieve synchronicity in google sheet npm when multiple requests comes at a given time.
**Example**: 
- If two orders are comes at the same time
- put them in a queue
- check for google sheet running processes
- wait till that is clear, start inserting order
- once that is done, move on to next order and remove the previous order from queue

Thanks in advance.

**Comment by theoephraim** [comment]
Sorry, I'm not sure I understand your question, but yes it sound like you may want to use a queue for this and it's outside the scope of this project. I recommend https://www.npmjs.com/package/bull

Cheers
