### ISSUE TITLE
Header Row Data Not Populated

### ISSUE THREAD

**Issue by rcldesign** [theoephraim/node-google-spreadsheet#280]
In the following code snippet, headerValues is not being defined, and row objects do not have keys associated with the expected header row values. 

From the automated testing, it seems that all of the tests start by creating a new sheet locally, but when simply pulling data from a sheet in the cloud, the header data is not populated.

` 
    const doc = new GoogleSpreadsheet(spreadSheetId);
    await doc.useServiceAccountAuth(creds);
    logger.debug('Authentication with Google Sheets complete');

    await doc.loadInfo();
    logger.debug(`Received workbook metadata for ${doc.title} (${doc.sheetsByIndex.length} worksheets)`);

    let analyticsIndex = -1;
    if (doc.sheetsByIndex.length > 0) {
        for (let i = 0; i < doc.sheetsByIndex.length; i += 1) {
            if (doc.sheetsByIndex[i].title === 'Analytics') {
                analyticsIndex = i;
            }
        }
    } else {
        logger.warn('No worksheets were returned');
    }

    if (analyticsIndex < 0) {
        logger.error('Unable to find "Analytics" sheet in workbook');
        return {};
    }

    // update the sheet data
    const skuAnalyticsSheet = doc.sheetsByIndex[analyticsIndex];

    logger.debug(skuAnalyticsSheet.headerValues);
`
This logging statement spits out 'undefined', meaning the headerValues property of the sheet is undefined

`
    await skuListSheet.loadHeaderRow();
    const rows = await skuListSheet.getRows();

    logger.debug(`Read ${rows.length} rows`);
    if (rows.length > 0) {
        logger.debug(`Row Object Keys: ${Object.keys(rows[0])}`);
    }`

Here, the rows.length value is as expected (~1000 rows in my case), but the keys for a row, which are expected to be the properties from the header row, is instead _sheet, _rowNumber, and _rawData

**Comment by theoephraim** [comment]
So as you found, you can either call `sheet.loadHeaderRow()` or when you call `sheet.getRows()` it will call it for you if the headers have not been loaded yet. After that, you can use `sheet.headerValues` to see what the headers are.

As for using Object.keys to figure out what the keys are on a row, it looks like that wont work. I'd have to do some research about defining dynamic properties via `Object.defineProperty` and how that interacts with `Object.keys` to figure out the best way forward there. I think it may be that I implement a `.toObject()` function that just spits out a raw object with the keys and values.

**Comment by theoephraim** [comment]
I also added `enumerable: true` on the dynamic property definitions so they will appear in `Object.keys(row)` now.

Please take a look at the latest and let me know if it's working ok for you

**Comment by rcldesign** [comment]
Confirmed that this works for me (both returning the header values as keys on the row objects and seeing the headerValues populated _after_ calling getRows() or loadHeaderRow().

One thing I'd like to confirm - this version of the library returns header names as they are on the sheet, but v2.x would lowercase and remove spaces and special characters. For example, if the sheet has "Money & Business" as a header value, v2.x would return "moneybusiness" and v3.x returns "Money & Business". Can I assume that this will be the case going forward?

**Comment by theoephraim** [comment]
Yep - that was the google v3 API messing with the header keys in the row-based calls so I had no control. Now I use the actual value - although I do pass it through `.trim()`
