### ISSUE TITLE
Workbook sheetCount is undefined

### ISSUE THREAD

**Issue by rcldesign** [theoephraim/node-google-spreadsheet#281]
After connecting to a document successfully, the sheetCount property is undefined. Using sheetsByIndex.length is however working correctly.

This works:
`    const doc = new GoogleSpreadsheet(spreadSheetId);
    await doc.useServiceAccountAuth(creds);
    logger.debug('Authentication with Google Sheets complete');

    await doc.loadInfo();
    logger.debug(`Received workbook metadata for ${doc.title} (${doc.sheetsByIndex.length} worksheets)`);`

This returns undefined for the sheetCount:
`    const doc = new GoogleSpreadsheet(spreadSheetId);
    await doc.useServiceAccountAuth(creds);
    logger.debug('Authentication with Google Sheets complete');

    await doc.loadInfo();
    logger.debug(`Received workbook metadata for ${doc.title} (${doc.sheetCount} worksheets)`);`

**Comment by theoephraim** [comment]
Thats a bug (and a missing test). Thanks for catching - will fix shortly.

**Comment by theoephraim** [comment]
fixed!

**Comment by sorxrob** [comment]
Hi @theoephraim. Still undefined with version 3.0.4.

**Comment by theoephraim** [comment]
🤔 working for me. make sure you have the latest version and nothing is getting cached in case you have any build system. If still not working, post a code example here please.

**Comment by sorxrob** [comment]
@theoephraim  posted a new issue with a question regarding getting sheet headers. Thank you.
