### ISSUE TITLE
Sheet basic document properties are undefined

### ISSUE THREAD

**Issue by sorxrob** [theoephraim/node-google-spreadsheet#282]
Version: ^3.0.4

All of these properties are undefined except the title.

- spreadsheetId
- locale
- timeZone
- autoRecalc
- defaultFormat
- spreadsheetTheme
- iterativeCalculationSettings

Here is my sample code:

```javascript

     const doc = new GoogleSpreadsheet('abcdefg');
     doc.useApiKey(process.env.GOOGLE_API_KEY);

	async someFun() {
		try {
			await doc.loadInfo();
			const sheet = doc.sheetsByIndex[0];
			console.log(sheet.spreadsheetId); // undefined
                        console.log(sheet.title); // works
		} catch (e) {
			console.log(e);
		}
	}
```

Even tried removing node_modules, and reinstall again.

Also, is there a way to get sheet headers? Something like

```javascript
await doc.loadInfo();
const sheet = doc.sheetsByIndex[0];
console.log(sheet.headers) // Array of sheet headers
```

Thank you.

**Comment by theoephraim** [comment]
Looks like youre trying to access document properties from the sheet.
ie `doc.spreadsheetId` exists, while for a sheet its `sheet.sheetId`

As for headers, if you call `await sheet.loadHeaderRow()` then you can access `sheet.headerValues`. (or if you call `sheet.getRows()` it will call loadHeaderRow for you if it hasn't already been loaded)
