### ISSUE TITLE
TypeError: Cannot read property '0' of undefined at GoogleSpreadsheetWorksheet.loadHeaderRow

### ISSUE THREAD

**Issue by JorgedeJesusRD01** [theoephraim/node-google-spreadsheet#284]
Hey
Although it seems a little counterproductive you should contemplate the option that the sheet may be empty and prevent it from exploding

![image](https://user-images.githubusercontent.com/50022863/73948631-9a288b80-48cf-11ea-917e-9947f550978d.png)

```
 TypeError: Cannot read property '0' of undefined
    at GoogleSpreadsheetWorksheet.loadHeaderRow (/home/intellisys/Desktop/metricas/functions/src/node_modules/google-spreadsheet/lib/GoogleSpreadsheetWorksheet.js:283:35)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

**Comment by theoephraim** [comment]
Yeah I did notice that today as well. To be fair, I would still throw an error in this case, as it doesn't make sense to `getRows` without any headers set, but at least I can make the error message a bit more helpful.

**Comment by theoephraim** [comment]
just published a new version with better checks for empty row headers and better error messaging
