### ISSUE TITLE
is there any impact on continuing using  the old npm version

### ISSUE THREAD

**Issue by vinodhreddygs** [theoephraim/node-google-spreadsheet#285]
Hi @theoephraim ,

I'am currently using **node-google-spreadsheet version ^2.0.7** and coded accordingly,  in our web based application.
Will **old version code works fine** in the future (or) need to update with the latest version, and then need to change the code accordingly?
If so, please tell what changes I need to be done to my code to work fine in the future without any issues,
It will be good if you share what new features has been added/updated  in new npm version .

Thanks in advance

**Comment by theoephraim** [comment]
No. Google is deprecating their old API on March 3 so you must upgrade to the newer version of this module which uses the newer API. 

Look at the docs, the new version is slightly different but it’s pretty easy to use
