### ISSUE TITLE
error when running addRows

### ISSUE THREAD

**Issue by svanderw** [theoephraim/node-google-spreadsheet#29]
I'm currently having problems any time I attempt using the addRows functionality.
I've attempted using both forms (using sheet index, and using a sheet instance) of the method without success.
I'm getting a 404 when it attempts to make the remote call.
running the unit tests gives me all passes except for the 
- node_google_spreadsheet - basic_write_and_read
- node_google_spreadsheet - check_newlines_read
tests.
In my code, I'm using an authenticated, private spreadsheet, and I can read and save successfully, but cannot add new rows.

**Comment by theoephraim** [comment]
any more info you can give me? what error is being returned?

**Comment by svanderw** [comment]
The response from the request is
statusCode 404,
the body is 'No such entry'

I did a bunch more investigating, and it turns out that I was getting 404's because the content that I was attempting to add was empty.  ie the xml data contained nothing but the columns to add into (no content for the row)

It is working now :)

**Comment by theoephraim** [comment]
great :)
I definitely need to put some better error messaging in.
