### ISSUE TITLE
save() for GoogleSpreadsheetCell.js does not work 

### ISSUE THREAD

**Issue by ERT-Kim** [theoephraim/node-google-spreadsheet#290]
Following error when calling _save()_ for _GoogleSpreadsheetCell_.
I think there is typo in that line (it should be _saveCells_, not _updateCells_)

TypeError: this._sheet.updateCells is not a function
  at GoogleSpreadsheetCell.save (/app/node_modules/google-spreadsheet/lib/GoogleSpreadsheetCell.js:173:23)

**Comment by theoephraim** [comment]
fixed, deploying shortly. Thanks!
