### ISSUE TITLE
`_handleAxiosErrors` Handle errors when no code

### ISSUE THREAD

**Issue by tbille** [theoephraim/node-google-spreadsheet#293]
For a reason I get this error:

```
(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property `code` of 'undefined' or 'null'.
    at GoogleSpreadsheet._handleAxiosErrors (/srv/node_modules/google-spreadsheet/lib/GoogleSpreadsheet.js:100:53)
    at <anonymous>:null:null
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

This is very hard for me to debug since I don't have this issue locally but only production which share the same environment (both run with the same docker configuration).

The main difference is the way I inject the environment variable as secret. My guess would be that one of those environments var is not well shaped, which doesn't seem to be the case.

It seems that `error.response.data` doesn't have all the time a code: https://github.com/theoephraim/node-google-spreadsheet/blob/master/lib/GoogleSpreadsheet.js#L100

**Comment by theoephraim** [comment]
have you been able to log the error itself to see any more info about what is happening?

**Comment by theoephraim** [comment]
Deploying an update shortly that should at least just throw the error without blowing up.
