### ISSUE TITLE
Getting rows on Querying is not working

### ISSUE THREAD

**Issue by vinodhreddygs** [theoephraim/node-google-spreadsheet#295]
Hi @theoephraim ,

I'am trying to get row/record on Querying with conditions.
i.e. I have number of records in a google sheet with header names **Emp Name, Emp ID, Emp Place**   etc.
 I'am trying to get the employee record and then, update  who's **Emp ID is 6258**. But its fails.

Please look in to below code snippets.
```
function getRecordToUpdate(empDetails, sheetInfo) {
    var options = { offset: 0 };
    options.query = 'Emp ID = '+empDetails.Employee_ID;   //here Emp ID is 6258
    return sheetInfo.getRows(options)
    .then((res) => res)
    .catch((err) => { throw err; })
}
```

                             (or)
```
function getRecordToUpdate(empDetails, sheetInfo) {
    var options = { offset: 0 };
    options.query = 'Emp ID = '+empDetails.Employee_ID;
    const response =await sheetInfo.getRows(options)
  
}
```
I'am getting all the records of the sheet instead of, the record with Emp ID is 6258.
Please help out with this.

Thanks in advance.

**Comment by theoephraim** [comment]
Querying rows doesn't work anymore because google discontinued their row-based calls in the v4 api. If you're not dealing with a massive amount of rows, you can just fetch them all and find the one you want to update.

**Comment by vinodhreddygs** [comment]
Hi @theoephraim ,

Iam dealing with massive amount of rows(i.e. in thousands) on daily basis from my node application.
So, do u have any suggestion to help me out?
What if I use directly google API's? will it solve my problems(using querying).

Thanks in advance.

**Comment by theoephraim** [comment]
No, unfortunately, that won't help. Google discontinued their row-based api which included the querying abilities. I recreated the row-based calls as best I could, but it can't do everything it used to. I recommend you try out https://airtable.com/invite/r/UnvfbjVY instead of google sheets.

**Comment by vinodhreddygs** [comment]
Hi @theoephraim ,

Can we able to get the **cell location** based on the cell values?
i.e. I want a cell location who's cell value is Emp ID = 6258. So that I can able to get row number of that cell and then, I can fetch all the cells of that row based on row number( **Using cell based API's**).
Is it possible? If so please provide me a **pseudo code** for this approach.

Thanks in advance.

**Comment by vinodhreddygs** [comment]
> No, unfortunately, that won't help. Google discontinued their row-based api which included the querying abilities. I recreated the row-based calls as best I could, but it can't do everything it used to. I recommend you try out https://airtable.com/invite/r/UnvfbjVY instead of google sheets.

Is Airtable supports google spread sheets? If so please suggest me a popular npm package to use it.

Thanks.

**Comment by theoephraim** [comment]
I don’t think it’s possible. Dig around in the google sheets docs directly.

Regardless, I suggest you try out airtable
-- 
--------------------
Theo Ephraim
*514.998.8436 | *theoephraim.com

**Comment by vinodhreddygs** [comment]
> I don’t think it’s possible. Dig around in the google sheets docs directly. Regardless, I suggest you try out airtable -- -------------------- Theo Ephraim *514.998.8436 | *theoephraim.com

Is Airtable supports google spread sheets? If so please suggest me a popular npm package to use it.

Thanks.

**Comment by vinodhreddygs** [comment]
Hi @theoephraim ,
Can we able to get the row by its row number? Instead of getting all rows and then, finding row by its index.
Please look into below code snippet for the reference:
```
function queryTogetRowsLen(sheetInfo) {
    return sheetInfo.getRows()
        .then((data) => {
        let rowIndex=455;     //let say row index=455
        return data[455];   
})
        .catch((err) => { throw err; })
}
```
