### ISSUE TITLE
TypeError: Cannot read property 'charAt' of undefined

### ISSUE THREAD

**Issue by nishadmenezes** [theoephraim/node-google-spreadsheet#296]
Getting this error when starting the server -

```
\node_modules\google-spreadsheet\node_modules\axios\lib\helpers\isURLSameOrigin.js:41
pathname: (urlParsingNode.pathname.charAt(0) === '/') ?
                                             ^

TypeError: Cannot read property 'charAt' of undefined
```
in file `isURLSameOrigin.js` line number 41.

**Comment by theoephraim** [comment]
hm - how have you initialized the doc? Since it seems to be something having to do with the URL, which is based on the document id, I think it probably is related. Can you copy paste your code where you set the doc up?

**Comment by theoephraim** [comment]
Closing this for now - please reopen and provide more details if you are still having issues.
