### ISSUE TITLE
Spaces in Headers

### ISSUE THREAD

**Issue by gsrp-tristen** [theoephraim/node-google-spreadsheet#303]
I have a header titled 'Join Date' and there doesn't seem to be a way to define that when searching through individual rows.

```
rows.some(function(row) {
                let name = row.NAME
                let callsign = row.CALLSIGN
                let joindate = row.JOINDATE

                if (name != 0 && name != '' && name != undefined && name != ' ') {
                    console.log(`Index: ${row.rowIndex}\nName: ${name}\nJoin Date: ${joindate}\n`)
                }
               
});
```

**Comment by gsrp-tristen** [comment]
This wasn't previously an issue but I recall reading that stripping the spaces so 'Join Date' could just be called as row.joindate wasn't actually supposed to be a feature, but it was a side effect of the old Google API version. Maybe I'm wrong in my recollection.

**Comment by theoephraim** [comment]
yep that's correct - the old google api automatically stripped and messed with the header columns, but it was somewhat unpredictable. In the new version I opted to just use the actual value - ie `row['Join Date']`
