### ISSUE TITLE
Is Version 3 API deprecating on Mar 3rd?

### ISSUE THREAD

**Issue by vinodhreddygs** [theoephraim/node-google-spreadsheet#309]
Hi @theoephraim ,

I'am migrating from version 3 API to version 4 API using your package. It takes till next week to complete.
But version 3 API code is in live for my application. If I don't push the version 4 API code before March 3rd, will my application breaks?

Thanks in advance.

**Comment by theoephraim** [comment]
It looks like google has extended their deprecation date to September. It was originally set as March 3. https://cloud.google.com/blog/products/g-suite/migrate-your-apps-use-latest-sheets-api

**Comment by CherryDT** [comment]
Oh wow, I didn't know... I also thought it'd be turned off now. I built [a wrapper](https://github.com/CherryDT/google-spreadsheet-v2v3-wrapper/) yesterday to hotfix apps that use the v2 version of your library - now it's actually not needed - there is enough time to properly fix it. Still leaving the link here in case it's useful to someone. (Maybe it will be an issue again in September^^)

**Comment by vinodhreddygs** [comment]
> It looks like google has extended their deprecation date to September. It was originally set as March 3. https://cloud.google.com/blog/products/g-suite/migrate-your-apps-use-latest-sheets-api

Hi @theoephraim ,

Thanks for your information.
Yes I can see in the docs that they are going to shutdown on Sep 30th, 2020.
Till then **If I use your old version code (**i.e. "google-spreadsheet": "^2.0.7"**) no issues right?**

Thanks.

**Comment by theoephraim** [comment]
yes.
