### ISSUE TITLE
Simply not working

### ISSUE THREAD

**Issue by iSuslov** [theoephraim/node-google-spreadsheet#31]
var my_sheet = new GoogleSpreadsheet('1OPx1v-S9-CcJUCJy689UYhbzWupgN_aQdZU4lu9mrBI');
my_sheet.setAuth('asddsfsdfsdf@gmail.com','111111111', function(err){
    my_sheet.getInfo( function( err, sheet_info ){
        if(err){
            console.error(err);
        } else {
            sheet_info.worksheets[0].addRow( 2, { colname: 'col value'} ) //here comes Error
        }
    })
})

throws exception

TypeError: Object.keys called on non-object
    at Function.keys (native)
    at addRow (/home/zuzel/Documents/node_modules/google-spreadsheet/index.js:98:14)
    at addRow (/home/zuzel/Documents/node_modules/google-spreadsheet/index.js:208:17)

**Comment by theoephraim** [comment]
It seems something broke recently. Perhaps changes with Google's API or with a recent update. I'll try to fix it ASAP.

**Comment by kaminskypavel** [comment]
seems like the '?alt=json' is now malfunctioning (spreadshets.js:28)
if you remove it from the queryString , google will return the data but in XML format.

**Comment by theoephraim** [comment]
Everything should be fixed now! Sorry for the trouble!
