### ISSUE TITLE
[ISSUE] Unhandled Promise rejection: Cannot read property 'values' of undefined 

### ISSUE THREAD

**Issue by elribonazo** [theoephraim/node-google-spreadsheet#311]
Hi guys,

I'm still capturing more information about the bug, but it looks i get this when calling addRow. But I'm not sure if its Google API returning something not expected or something in our side.

Anyway, it looks i could recover from this just if the promise.reject is returned, so at least here i see an issue.

Unhandled Promise rejection: Cannot read property 'values' of undefined ; Zone: <root> ; Task: null ; Value: TypeError: Cannot read property 'values' of undefined
    at GoogleSpreadsheetWorksheet.addRow (/var/app/current/node_modules/google-spreadsheet/lib/GoogleSpreadsheetWorksheet.js:373:41)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7) TypeError: Cannot read property 'values' of undefined
    at GoogleSpreadsheetWorksheet.addRow (/var/app/current/node_modules/google-spreadsheet/lib/GoogleSpreadsheetWorksheet.js:373:41)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)

**Comment by theoephraim** [comment]
Hello!
First off, make sure you are on the latest version of the module. From the error message you posted, it looks like you may not be, so the problem may be fixed already. If that doesn't fix the problem, please provide a short code sample and I'll take a look!

**Comment by elribonazo** [comment]
Hello @theoephraim ,

The error was in our side, we were sending incorrect headers thats why. 

Anyway don't u consider that the package should be able to troubleshoot that?

**Comment by theoephraim** [comment]
Yes in many cases I catch common problems and try to return meaningful/helpful error messages. But I can't handle every case and need help identifying issues.

Can you help provide more info about what you were sending that was causing this issue?

**Comment by theoephraim** [comment]
closing this - please do provide more info and I can see if it could make sense to add a better error message.

cheers
