### ISSUE TITLE
[Bug]  sheet.loadCells() exception when load multiple ranges (Google API error)

### ISSUE THREAD

**Issue by jbskies** [theoephraim/node-google-spreadsheet#312]
let cellRanges = [];
cellRanges.push('B1:K999');
cellRanges.push('M1:P999');
await sheet.loadCells(cellRanges);

throw exception below:
Google API error - [400] Unable to parse range: 'SHEETNAME'!B1:K999,M1:P999

**Comment by theoephraim** [comment]
thanks for reporting - I'll check this out.

**Comment by theoephraim** [comment]
deploying a fix right now - sorry it took a while!
