### ISSUE TITLE
Record insert in to the google sheet failed.

### ISSUE THREAD

**Issue by vinodhreddygs** [theoephraim/node-google-spreadsheet#313]
Hi @theoephraim ,

When I tried to insert a record or row in to the google sheet though API (**I'am using this module version 3.0.8**), I got the below error:

`Error : FetchError: request to https://www.googleapis.com/oauth2/v4/token failed, reason: Client network socket disconnected before secure TLS connection was established`

It happened only twice on inserting nearly 100 records in to  the sheet.
Please reply to this thread if you know the reason.

Thanks in advance.

**Comment by theoephraim** [comment]
use the `.addRows` method to add many rows at once, rather than making many requests.
Also, it looks like you are re-initializing the auth for each request. You should just initialize the auth for the document once on startup (or if connecting to many docs, the first time you see that doc)
