### ISSUE TITLE
Please fix copyToSpreadsheet method, circular JSON error

### ISSUE THREAD

**Issue by ogomez92** [theoephraim/node-google-spreadsheet#314]
Hello,
Please fix the copyToSpreadsheet method.
axios.post gives me a circular JSON error with the Google Spreadsheet object. Like this:
Hello, I get the following error when cpying a spreadsheet to another spreadsheet:
Code:
            sheet = await exports.archive.addSheet({ title: "Sheet for month " + new Date().getMonth() + " of " + new Date().getYear() + 100 })
        } catch {
            let length = exports.archive.sheetsByIndex.length - 1;
            sheet = exports.archive.sheetsByIndex[length]
        }
        console.log("Archive sheet found");
        let original = exports.findSheet(0) //returns the spreadsheet to be coppied from.
        await original.copyToSpreadsheet(sheet)
        console.log("Coppied!")
//        await original.resize({ rowCount: 2, columnCount: 20 });

Result:

Archive loaded
Archive sheet found

Converting circular structure to JSON
    --> starting at object with constructor 'GoogleSpreadsheetWorksheet'
    |     property '_spreadsheet' -> object with constructor 'GoogleSpreadsheet'
    |     property '_rawSheets' -> object with constructor 'Object'
    --- property '1204944981' closes the circle

Thank you!

**Comment by theoephraim** [comment]
Google's naming with this is certainly confusing... This method doesn't copy a worksheet to another worksheet, it copies the worksheet to a different spreadsheet document.


Look at the [method docs](https://theoephraim.github.io/node-google-spreadsheet/#/classes/google-spreadsheet-worksheet?id=fn-copytospreadsheet) - you are supposed to pass in another spreadsheet document ID

You may be able to pass in the same document id if you want to duplicate a worksheet?
