### ISSUE TITLE
await is only valid in async function

### ISSUE THREAD

**Issue by Chr1sCon** [theoephraim/node-google-spreadsheet#315]
When I run the example code, I get the error message below. This is my first node.js project, and I am struggling to figure out what is going on.

> await doc.useServiceAccountAuth(require('./credentials.json'));
> ^^^^^
> 
> SyntaxError: await is only valid in async function

Any idea what's going on?

Full code:
```
const { GoogleSpreadsheet } = require('google-spreadsheet');

// spreadsheet key is the long id in the sheets URL
const doc = new GoogleSpreadsheet('MY_ID');

// OR load directly from json file if not in secure environment
await doc.useServiceAccountAuth(require('./credentials.json')); //From GCP Console

await doc.loadInfo(); // loads document properties and worksheets
console.log(doc.title);

const sheet = doc.sheetsByIndex[0]; // or use doc.sheetsById[id]
console.log(sheet.title);
console.log(sheet.rowCount);
```

**Comment by Chr1sCon** [comment]
Searching online for changing to an async call, I came across this https://cmichel.io/how-to-access-google-spreadsheet-with-node/.

Trying to run the code:
```
const GoogleSpreadsheet = require('google-spreadsheet')
const { promisify } = require('util')

const credentials = require(`./credentials.json`) //From GCP Console

const SPREADSHEET_ID = `MY_ID`
async function accessSpreadsheet() {
    const doc = new GoogleSpreadsheet(SPREADSHEET_ID)
    await promisify(doc.useServiceAccountAuth)(creds)
    const info = await promisify(doc.getInfo)()
    console.log(`Loaded doc: ` + info.title + ` by ` + info.author.email)
    const sheet = info.worksheets[0]
    console.log(
        `sheet 1: ` + sheet.title + ` ` + sheet.rowCount + `x` + sheet.colCount
    )
}


accessSpreadsheet()
```

Gives me the error:

> "const doc = new GoogleSpreadsheet(SPREADSHEET_ID)"
> UnhandledPromiseRejectionWarning: TypeError: GoogleSpreadsheet is not a constructor


It's probably something dead simple, but I am officially stuck :upside_down_face:

**Comment by theoephraim** [comment]
That blog post is old and using an older version of this module, so dont follow that.

The issue is that when you're running script in node, you can't call await at the root level - it must be inside of an async function. I skipped over this in the examples since it would just add unnecessary bloat/confusion. Normally if for example you were using this within an express API or something, you'd be calling these methods within a function already.

If you're just trying to manually run a script like the example, I would suggest he following

```
const { GoogleSpreadsheet } = require('google-spreadsheet');

const doc = new GoogleSpreadsheet('MY_ID');

// just wrap your code in an async function that gets called immediately
(async function main() {
  await doc.useServiceAccountAuth(require('./credentials.json')); //From GCP Console
  await doc.loadInfo(); // loads document properties and worksheets
  ...
})();
```
