### ISSUE TITLE
How to get sheet by title

### ISSUE THREAD

**Issue by itsgauravjain22** [theoephraim/node-google-spreadsheet#317]
Kindly specify a way to get sheet by its title.

**Comment by itsgauravjain22** [comment]
Well, I used `doc._rawSheets[0]._rawProperties.title` for getting the title and comparing it with required Titltes sheet id. There should be a public function to get sheet by its title, as its the easy identifier on gui interface.

**Comment by theoephraim** [comment]
It's just looking through an array for the thing you want, so not sure a utility method would make much sense here... But those underscored properties are not meant to be used. Instead just look at the sheet titles.

After you calling `doc.loadInfo()`, you can just search search through the sheets.
For example, using lodash, `_.find(doc.sheetsByIndex, { title: 'titleToLookFor' })`

**Comment by itsgauravjain22** [comment]
Thanks @theoephraim for the solution. I already tried following function and it works
```
sheetsByTitle = (title) => {
    for (let i = 0; i < doc.sheetCount; i++) {
        if (doc.sheetsByIndex[i].title == title) {
            let sheetId = doc.sheetsByIndex[i].sheetId
            return doc.sheetsById[sheetId]
        }
    }
    return null
}
```

I was hoping to have similar kind of function available in default library.
