### ISSUE TITLE
addRow() replaced another row instead adding the at the bottom

### ISSUE THREAD

**Issue by vinodhreddygs** [theoephraim/node-google-spreadsheet#318]
Hi @theoephraim ,

I faced a weird issue with addRow() function. In my application I observed that, the latest inserted record/row have been replaced with the another row, instead adding at the bottom.
This is causing big issue in my project.
Is there any reason for this? Please let me know.

Thanks in advance.

**Comment by theoephraim** [comment]
The default behavior is to overwrite the first _empty_ row after content in the sheet that it finds, inserting a new row at the end if all rows are non-empty. Is it overwriting a non-empty row? If so I would guess it has to do with multiple calls being made at the same time. This is behaviour on google's side... Internally the addRow method is using https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/append

Maybe putting the rows to insert into some kind of queue could help, in which case you could batch multiple inserts together using `sheet.addRows()`

You can also try the [insert option on `addRow()`](https://theoephraim.github.io/node-google-spreadsheet/#/classes/google-spreadsheet-worksheet?id=fn-addrow) which rather than overwriting the latest empty row in the sheet inserts a new row into the sheet every time

**Comment by vinodhreddygs** [comment]
> The default behavior is to overwrite the first _empty_ row after content in the sheet that it finds, inserting a new row at the end if all rows are non-empty. Is it overwriting a non-empty row? If so I would guess it has to do with multiple calls being made at the same time. This is behaviour on google's side... Internally the addRow method is using https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/append
> 
> Maybe putting the rows to insert into some kind of queue could help, in which case you could batch multiple inserts together using `sheet.addRows()`
> 
> You can also try the [insert option on `addRow()`](https://theoephraim.github.io/node-google-spreadsheet/#/classes/google-spreadsheet-worksheet?id=fn-addrow) which rather than overwriting the latest empty row in the sheet inserts a new row into the sheet every time

Hi @theoephraim ,

If it is due to multiple calls at a time then it should replace the records which comes at a time but in my case it has been replaced by old record.
i.e. There are 4600 records are there at that moment, the newly inserted record has been replaced by the 4206th row(Non empty row).
These things happens when we have filters in our spread sheet?

Thanks.

**Comment by vinodhreddygs** [comment]
> The default behavior is to overwrite the first _empty_ row after content in the sheet that it finds, inserting a new row at the end if all rows are non-empty. Is it overwriting a non-empty row? If so I would guess it has to do with multiple calls being made at the same time. This is behaviour on google's side... Internally the addRow method is using https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/append
> 
> Maybe putting the rows to insert into some kind of queue could help, in which case you could batch multiple inserts together using `sheet.addRows()`
> 
> You can also try the [insert option on `addRow()`](https://theoephraim.github.io/node-google-spreadsheet/#/classes/google-spreadsheet-worksheet?id=fn-addrow) which rather than overwriting the latest empty row in the sheet inserts a new row into the sheet every time

**Comment by vinodhreddygs** [comment]
> The default behavior is to overwrite the first _empty_ row after content in the sheet that it finds, inserting a new row at the end if all rows are non-empty. Is it overwriting a non-empty row? If so I would guess it has to do with multiple calls being made at the same time. This is behaviour on google's side... Internally the addRow method is using https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/append
> 
> Maybe putting the rows to insert into some kind of queue could help, in which case you could batch multiple inserts together using `sheet.addRows()`
> 
> You can also try the [insert option on `addRow()`](https://theoephraim.github.io/node-google-spreadsheet/#/classes/google-spreadsheet-worksheet?id=fn-addrow) which rather than overwriting the latest empty row in the sheet inserts a new row into the sheet every time

Hi @theoephraim ,

I can see this issue, when any user who all access to the spread sheet applies filters, then any new rows comes then its overwrite/replaced other rows instead of adding at the end.

**Is there any way that serve(using this npm) should not consider the spread sheet filters while inserting a new row?**

**Comment by theoephraim** [comment]
Im not sure. This is just using google's api under the hood, so this sounds like an issue you'll have to look into with their API.

**Comment by jwd-dev** [comment]
I know this is stale but is there any news on native support for some kind of async operation on inserts? Dealing with the same issue here, multiple threads inserting into a google sheet and overwriting each other.

**Comment by theoephraim** [comment]
@jwd-dev - the  google api call under the hood should always be appending rows, so if their API truly overwrites data if they come in too quickly, then unfortunately there's nothing we can really do... But I'd be _very_ surprised if that was the case. Is your sheet using filters as mentioned above?
