### ISSUE TITLE
Is there any way to clear or ignore google sheet's applied filters before row insert?

### ISSUE THREAD

**Issue by vinodhreddygs** [theoephraim/node-google-spreadsheet#321]
Hi @theoephraim ,

If any filters applied in the spread sheet, then new inserted row/record is replacing the old record.
I**s there any way to clear or ignore google sheet filters before row insert?**
Example:
If spread sheet is shared with the many people, if any one of them applied the filters to the sheet then, everyone will see the same filters when they open sheet.                                           
**Is there any way to give filter options in the spread sheet on individual basis instead of globally?**

Thanks.

**Comment by theoephraim** [comment]
Yes there is a way to change filters programatically, but I do not believe I have implemented those calls yet. Feel free to open a PR - it should not be too hard.

Regarding having different users seeing different filters - sorry, but this is an issue with google sheets - not this package.

From the amount of issue you've had and what I understand about your usage, I'd strongly recommend taking a look at http://airtable.com as I think it will serve your purposes better.
