### ISSUE TITLE
New way to do getCells?

### ISSUE THREAD

**Issue by telgueta** [theoephraim/node-google-spreadsheet#322]
Im having a problem with the getCells function. Before i used:
const responsePromise = getCells({
    "min-row": 2,
    "min-col": 1,
    "max-col": 2,
  });
and i got all the cells i need, but now im doing it with the new way and it isnt working

**Comment by theoephraim** [comment]
Can you provide more details? What does the call look like? Are you getting an error?

**Comment by telgueta** [comment]
Before I usef the get cells inside a variable, so then I could use. Reduce on it. But Now when I assign the loadcells function to a constante, it return me undefined

**Comment by theoephraim** [comment]
Yes things changed in the newer version of the module.
Read the docs. You load a range of cells and can then access them.
