### ISSUE TITLE
useServiceAccountAuth always returns an error

### ISSUE THREAD

**Issue by jvlobo** [theoephraim/node-google-spreadsheet#325]
Hi there.

First of all, thank you for your work.
I wanted to start using this package but I haven't been able to get it to run.

Following the docs I've gotten Google credentials.json file and:
`await doc.useServiceAccountAuth(require('./credentials.json'));`
but I get `Error: No key or keyFile set.`

If I try with:
```
await doc.useServiceAccountAuth({
  client_email: 'myemail',
  private_key: 'mykey'
});
```
I get `Error: error:0906D06C:PEM routines:PEM_read_bio:no start line`

Is this supposed to work? Am I doing something wrong?

Thank you.

**Comment by theoephraim** [comment]
You may be using the wrong key/file. Can you copy paste your keyfile (obscuring some of the secure sensitive parts)

**Comment by jvlobo** [comment]
Thanks for the replay.

```
{
  "installed": {
    "client_id": "xxxxxxxxxxxxxxx.apps.googleusercontent.com",
    "project_id": "quickstart-XXXXXXXXXXXX",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_secret": "xxxxxxxxxxxxxxxx",
    "redirect_uris": ["urn:ietf:wg:oauth:2.0:oob", "http://localhost"]
  }
}
```

This is the json I got from Google.

**Comment by jvlobo** [comment]
My bad... I just saw that I was not getting the service account credentials... just got them and it works.

Thanks a lot.
