### ISSUE TITLE
How to interact Google Spreadsheets with Chatbots?

### ISSUE THREAD

**Issue by lai32290** [theoephraim/node-google-spreadsheet#327]
I'm using Service Account's to manipulate my own spreadsheet, I know my script is working because I've tried it direct by Node (running `node myScript.js`)

My script is like this:

```
const { GoogleSpreadsheet } = require('google-spreadsheet');

async function start() {
	const creds = require('./creds-from-google.json');
	const sheetID = 'my spredsheets URL id here';
	const doc = new GoogleSpreadsheet(sheetID);

	await doc.useServiceAccountAuth({
		client_email: creds.client_email,
		private_key: creds.private_key,
	});


	await doc.loadInfo(); // loads document properties and worksheets
	console.log(doc.title);

	const sheet = doc.sheetsByIndex[0];
	console.log(sheet.title);

	const data = {
        	'Title': 'my title here',
        	'Content': 'my content here'
	};
	return sheet.addRow(data);
}
start();
```

But when I execute this code by Telegram bot, it's getting 401 error.

Error message:

`Google API error - [401] Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.`

**Comment by theoephraim** [comment]
The issues is probably that the environment your bot is running in does not have the auth configured correctly. Going to close this but feel free to reopen if still an issue and you can post more context.
