### ISSUE TITLE
_fillCellData, just internal?

### ISSUE THREAD

**Issue by j2l** [theoephraim/node-google-spreadsheet#329]
Is there a way to fill a range of cells (A2:A100)?
I tried
```
await sheet.loadCells('A2:A100');
for (let i = 0; i < 98; i++) {
a[i] = sheet.getCell(i, 0);
           a[i].value = '';
        }
        (async function clean() {
            await sheet.saveUpdatedCells();
        })();
```
and a more brutal way
```
for (let i = 0; i < 98; i++) {
rows[i].pos = '';
(async function save() {
await rows[i].save();
})();
```
Without luck. No error but simply no update.
I guess it hits a query threshold limit at Google.
I searched in code and found there's an internal function. But I didn't dig more than that.

Is there a way to fill a range?
Thanks!

**Comment by theoephraim** [comment]
hm there shouldn't be any problem with updating a bunch of cells and then calling saveUpdatedCells. I would stick with the cell methods since that will make just one call, while the row methods would make one save call for each row.

Can you copy some more code, I think it must be some other issue about how you have things set up

**Comment by j2l** [comment]
Thank you @theoephraim 
OK, here's the working code (using rows) and commented non working code:
```
const { GoogleSpreadsheet } = require('google-spreadsheet');
var rows = {};
var visits =1;

const doc = new GoogleSpreadsheet('***);
(async function main() {
  await doc.useServiceAccountAuth(require('./***.json'));
  doc.resetLocalCache();
  await doc.loadInfo();
    sheet = doc.sheetsByIndex[1];
  rows = await sheet.getRows();
  //await sheet.loadCells('A2:A100');
})();

app.get('/update', function(req, res) {
  (async function main() {
    await doc.useServiceAccountAuth(require('./***.json'));
    doc.resetLocalCache();
    await doc.loadInfo(); // loads document properties and worksheets
      sheet = doc.sheetsByIndex[1]; // or use doc.sheetsById[id]
    rows = await sheet.getRows(); // can pass in { limit, offset }  
  })();
  res.send('OK');
});
app.post('/', function(req, res) {
    // if (visits == 0){
    //    // var a=[];
    //     for (let i = 0; i < 98; i++) {
    //         rows[i].pos = '';
    //         (async function save() {
    //             await rows[i].save();
    //         })();
        //    a[i] = sheet.getCell(i, 0);
        //    a[i].value = '';
        // }
        // (async function clean() {
        //     await sheet.saveUpdatedCells();
        // })();
    // }
    rows[visits].pos = '#';
    (async function save() {
        await rows[visits].save();
    })();
    visits++;
});
```

For now, I update a row at a time using `await rows[visits].save();` 
But I noticed that formulas are rewritten as values. As you can see I only update "pos", so I'd prefer to updateCell pos using "visit" row index and also be able to clean pos column (A2:A100) at the end of the day.

Our non-profit org helps anxious people in quarantine. They visit our web page and we assign a volunteer with a unique link (lien) to each.

Hope it makes sense.
Thank you again!

**Comment by j2l** [comment]
bump

**Comment by j2l** [comment]
any news?

**Comment by theoephraim** [comment]
Hi @j2l  - working through old issues now. Were you able to resolve this problem?
I think you should be able to just loop over the cells, updating the value, and then making a single call to saveUpdatedCells

**Comment by j2l** [comment]
8 months later?
No, I don't remember.
