### ISSUE TITLE
New method to do cells.forEach() ?

### ISSUE THREAD

**Issue by Gaby13627** [theoephraim/node-google-spreadsheet#330]
Hello,
Im having a problem with the cells.forEach function. 
With the old api I used :

> const doc = new GoogleSpreadsheet('sheet_id')
await promisify(doc.useServiceAccountAuth)(creds);
const info = await promisify(doc.getInfo)()
const sheet = info.worksheets[0];
const cells = await promisify(sheet.getCells)({
    'min-raw': 3,
    'min-col': 1,
    'max-col': 3,
 });
 cells.forEach(async cell => {
some code here
})

But now with the newest api:
> const sheet = doc.sheetsByIndex[0];
cells = await sheet.loadCells('A:A')
cells.forEach(t => {
    console.log(t.value)
    });

I'm getting this error when I try to run the code : Cannot read property 'forEach' of undefined

I've read the documentation but I didn't find any solution.
Can someone help me ?

**Comment by theoephraim** [comment]
check out the example in the docs - https://theoephraim.github.io/node-google-spreadsheet/#/?id=working-with-cells

With the new api, loadCells does not return the loaded cells. Rather it loads them into a cache that is then available to interact with by calling `getCell` or `getCellByA1`

**Comment by Gaby13627** [comment]
You answered me , but I don’t really understand your answer. How can I get multiple cell and do each function after getting cells? I know I must load cell.
For example if I get cells with this command: await sheet.loadCells(['A1:A50', 'G1:50'])
I would like to check for each cell, how can I do?

**Comment by lordsherman** [comment]
@Gaby13627 Any Chance you have found a solution to this?  I am currently trying to parse a massive column to check for duplicate entries when a user enters a name.

**Comment by Gaby13627** [comment]
I don’t know if this will make it possible to do what you want but for me it was enough to do what I wanted:

```
async function  Spreadsheet() {
    const doc = new GoogleSpreadsheet('');
    await doc.useServiceAccountAuth(creds);
    await doc.loadInfo()
    const sheet = doc.sheetsByIndex[0];
    await sheet.loadCells('A:A')
    number = sheet.cellStats.nonEmpty
    await sheet.loadCells(`A:A${number}`)
    for (let i = 1; i <= number; i++) {
        cellvalue = sheet.getCellByA1(`A${i}`)
        if (cellvalue.value === name) {
           //Your code here
        }
    }
}
```
