### ISSUE TITLE
sheet.loadCells(range) not working

### ISSUE THREAD

**Issue by daniloleemes** [theoephraim/node-google-spreadsheet#331]
When trying to load cells I get this error
```
(node:55723) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: Google API error - [401] Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
warning.js:18
(node:55723) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This is how I'm trying
```js
const { GoogleSpreadsheet } = require('google-spreadsheet');
const { googleApiKey, sourceSheetId } = require('./vars');
const { camelCase } = require('lodash');

const doc = new GoogleSpreadsheet(sourceSheetId);

exports.init = async () => {
    await doc.useApiKey(googleApiKey);
    await doc.loadInfo();

    const sheet = doc.sheetsByIndex[1];
    const { title, lastColumnLetter, rowCount } = sheet;
    const rows = await sheet.getRows();
    const keys = sheet.headerValues.map(key => camelCase(key));
    await sheet.loadCells(`A1:${lastColumnLetter}${rowCount}`)

    rows.length;
}
```

This is the spreadsheet https://docs.google.com/spreadsheets/d/1Hxrdp7oxtK-J5x9u1-rzChUpLtkv3t0_kNGdS6dtyWI/edit#gid=219336283

**Comment by TimeBandit** [comment]
I am seeing this too. Someone also raised this on [SO](https://stackoverflow.com/questions/60095462/google-spreadsheet-js-npm-read-only-access-to-cell-not-working-with-api-key)

**Comment by theoephraim** [comment]
Oh interesting - thanks for bringing this to my attention. It was a very subtle detail in the google docs that I missed, that the `getByDataFilter` endpoint does not work with read-only access.

I have just updated the loadCells method to default to the main `get` endpoint instead if using an API key for auth. It will throw an error if you try to pass in a gridRange object, as only A1 ranges are supported in the main endpoint.

Releasing new npm version shortly!
