### ISSUE TITLE
Encountered : Google API error - [429] Quota exceeded

### ISSUE THREAD

**Issue by vinodhreddygs** [theoephraim/node-google-spreadsheet#332]
Hi @theoephraim ,

Iam getting the below error. Please help me out with this.

`Error: Google API error - [429] Quota exceeded for quota group 'ReadGroup' and limit 'Read requests per user per 100 seconds' of service 'sheets.googleapis.com' for consumer 'project_number:210163281712'. `

Thanks.

**Comment by theoephraim** [comment]
This issue has nothing to do with this library.

Read the error - youre exceeding your api limit on google. Either reduce the number of calls youre making, or put them into a queue or something so you can rate limit.
