### ISSUE TITLE
Cannot loadCells using array of filter

### ISSUE THREAD

**Issue by VrTech** [theoephraim/node-google-spreadsheet#333]
According to this 
`https://theoephraim.github.io/node-google-spreadsheet/#/classes/google-spreadsheet-worksheet`

This is what I used
`sheet.loadCells(["A1:C1","K1:J1"])`

I only got the first 3 cells but not the other filter.
any ideas?

Also I use `loadCells` twice.
First with
`sheet.loadCells("A1:C1")`
then
`sheet.loadCells(["A1:C1","K1:J1"])`

Thank you!

**Comment by theoephraim** [comment]
HI @VrTech - is this still a problem? I just checked and I can load multiple ranges without any issues.

**Comment by VrTech** [comment]
i think it’s fixed 💯
