### ISSUE TITLE
Be able to override sheet last column to calculate range

### ISSUE THREAD

**Issue by jarstorm** [theoephraim/node-google-spreadsheet#337]
I have a spreadsheet with this header:

![image](https://user-images.githubusercontent.com/8057108/80100950-003cba80-8571-11ea-9bbc-e8851274d47c.png)

When I execute the method ```sheet.getRows()``` It calculates the data only for A column.

This is because the calculation about the number of columns is only depending on the header.

Could you please add a parameter "lastColumn" to options object in:

``` async getRows(options = {}) { ```

Thanks

**Comment by theoephraim** [comment]
In order to load the row data, you will need unique values in each header cell, as it uses those values as the keys for the data in each row. If you wish to just load cell data, you can use the cell based methods.
