### ISSUE TITLE
Getting "Spreadsheet key not provided." when I am providing the Key

### ISSUE THREAD

**Issue by martin-wiseweb** [theoephraim/node-google-spreadsheet#34]
I am trying to instantiate the spreadsheet object, but I keep getting an error saying I'm not passing a key.

    var googleAuth = new GoogleClientLogin( {
        email : 'me@myplace.ca',
        password : 'my-hard-to-guess-password',
        service : 'spreadsheets'
    } );
	var sheet = new GoogleSpreadsheet( "SkQBL762iVNw5Tugtfrgf94tMfTsiZI5KPvEPui6a_P3", googleAuth );

That code gives me the following error:

    throw new Error("Spreadsheet key not provided.");

Any ideas?

**Comment by theoephraim** [comment]
very strange! Are you sure you have the latest version?

**Comment by martin-wiseweb** [comment]
Yup. My package.json:

	{
	"name" : "xml-locale-maker",
	"version" : "0.0.1",
	"dependencies" : {
		"google-spreadsheets" : "latest",
		"googleclientlogin" : "latest",
		"xml" : "latest"
	}
}

**Comment by theoephraim** [comment]
I believe that `google-spreadsheets` is a different package.
Try running `npm install google-spreadsheet@latest --save`

**Comment by theoephraim** [comment]
see https://github.com/samcday/node-google-spreadsheets
