### ISSUE TITLE
Filters in the google sheet to retrieve specific data on conditions

### ISSUE THREAD

**Issue by maliknadeemshahzad** [theoephraim/node-google-spreadsheet#341]
const data = {
    request = {
        filters: {
            columnHeaderName: value,
            columnHeaderName1: value
        }
        operation: {
            type: or | and
        }
    }
}

**Comment by theoephraim** [comment]
This is not supported by the google API, so would not really make sense.
You could try to accomplish this using formulas though - have your source data in 1 sheet and your filtered data in another, and then fetch from the filtered data.
