### ISSUE TITLE
Module SpreadsheetApp missing in google-spreadsheet

### ISSUE THREAD

**Issue by Rednas83** [theoephraim/node-google-spreadsheet#344]
For some reason I am not able to find the **SpreadsheetApp** module referenced in the doc below. I am especially interested in the functions **getActiveSheet** and **getActiveRange**
![image](https://user-images.githubusercontent.com/25219229/80969234-95fe0280-8e19-11ea-8f7b-7e73d5da7178.png)

The only modules I can find are the ones below.
![image](https://user-images.githubusercontent.com/25219229/80969704-5388f580-8e1a-11ea-875b-8083776e3077.png)

Tried:
```
const app = require('google-spreadsheet')
const doc = new app.GoogleSpreadsheet(
  'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') // Replaced by dummy/non existing ID
)
console.log(SpreadsheetApp.getActiveSheet()) // Returns error "Undefined"
console.log(SpreadsheetApp.getActiveRange()) // Returns error "Undefined"
console.log(doc.getActiveSheet()) // Returns error "Not a function"
console.log(doc.getActiveRange()) // Returns error "Not a function"
```

Should I use a different package to make use of these functions?

**Comment by theoephraim** [comment]
Not sure where that screenshot is from, but doesn't look to be the right docs.
Take a look at the docs [here](https://theoephraim.github.io/node-google-spreadsheet/#/) for info on how to get started
