### ISSUE TITLE
Feature Request: Use automatic authentication with Google Cloud Functions?

### ISSUE THREAD

**Issue by adueck** [theoephraim/node-google-spreadsheet#345]
First of all thank you for this wonderful, well-documented tool. It's been a joy to use.

One little issue that I am having when trying to use this in a Google Cloud Function.

When running Google Cloud Functions it seems that the authentication can be taken care of automatically, as it says [https://cloud.google.com/functions/docs/securing/function-identity]:

> During function execution, Cloud Functions uses the service account `PROJECT_ID@appspot.gserviceaccount.com` as its identity. For instance, when making requests to Google Cloud Platform services using the Google Cloud Client Libraries, Cloud Functions can **automatically obtain and use tokens to authorize the services** this identity has permissions to use.

So instead of putting the private key etc. in our function environment variables, it would be wonderful if we could just leave out the auth, or pass an option to use the default Cloud Functions auth.

I tried deploying it to see if it would automatically obtain and use the functions, but unfortunately that wouldn't work.

```
Error: You must initialize some kind of auth before making any requests
    at GoogleSpreadsheet._setAxiosRequestAuth (/srv/node_modules/google-spreadsheet/lib/GoogleSpreadsheet.js:117:13)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

That was without any call to `doc.useServiceAccountAuth()`, so I tried just passing the `client_email`

```
doc.useServiceAccount({ client_email: "MY_PROJECT_ID@appspot.gserviceaccount.com" });
```

But then I get this error:

```
Error: No key or keyFile set.
    at GoogleToken.getTokenAsync (/srv/node_modules/gtoken/build/src/index.js:125:19)
    at GoogleToken.getToken (/srv/node_modules/gtoken/build/src/index.js:77:21)
    at JWT.refreshTokenNoCache (/srv/node_modules/google-auth-library/build/src/auth/jwtclient.js:156:36)
    at JWT.refreshToken (/srv/node_modules/google-auth-library/build/src/auth/oauth2client.js:143:25)
    at JWT.authorizeAsync (/srv/node_modules/google-auth-library/build/src/auth/jwtclient.js:139:35)
    at JWT.authorize (/srv/node_modules/google-auth-library/build/src/auth/jwtclient.js:135:25)
    at GoogleSpreadsheet.renewJwtAuth (/srv/node_modules/google-spreadsheet/lib/GoogleSpreadsheet.js:86:26)
    at GoogleSpreadsheet.useServiceAccountAuth (/srv/node_modules/google-spreadsheet/lib/GoogleSpreadsheet.js:81:16)
    at init (/srv/lib/dictionary-maker.js:25:19)
    at Object.<anonymous> (/srv/lib/dictionary-maker.js:32:3)
```

This would be a great feature to be able to take advantage of the Cloud Functions automatic credential fetching and auth. ([See Google docs on this issue](https://cloud.google.com/functions/docs/securing/function-identity))

**Comment by juliendorra** [comment]
Hi, I'm stumbling on the same issue…

what is the simplest way to authenticate with the package in a Google Cloud Function? Is it referencing a manually exported key for the given service account in an environment variable? 

@adueck, What did you end up doing? Did you find a way to use the automatic authentication with the package in the end?

**Comment by adueck** [comment]
@juliendorra, I ended up using the [environment variables](https://cloud.google.com/functions/docs/env-var) in Google Cloud/Firebase functions. I put a service account email and key in my Firebase functions environment variable (basically the same as Google Cloud functions) and accessed in in the code like this:

```js
await doc.useServiceAccountAuth({
    client_email: functions.config().serviceacct.email,
    private_key: functions.config().serviceacct.key,
});
```

**Comment by kannapoix** [comment]
I had same problem too.
My solution is to use `useRawAccessToken` with access token which is taken through auth library. 
[Document for useRawAccessToken](https://github.com/theoephraim/node-google-spreadsheet/blob/198e9c3aa6053f72f8a6e0da0f2019fcaa74f479/docs/classes/google-spreadsheet.md#userawaccesstokentoken-idfn-userawaccesstoken)
[getAccessToken](https://github.com/googleapis/google-auth-library-nodejs/blob/v7.10.2/src/auth/googleauth.ts#L813)


```js
const { GoogleSpreadsheet } = require('google-spreadsheet');
const { GoogleAuth } = require('google-auth-library');

const doc = new GoogleSpreadsheet('<the sheet ID from the url>');

const auth = new GoogleAuth({
  scopes: 'https://www.googleapis.com/auth/spreadsheets'
});
const token = await auth.getAccessToken();

if (token == null) {
  throw new Error("Failed to get access token")
}

await doc.useRawAccessToken(token);
```

**Comment by iamswain25** [comment]
> I had same problem too. My solution is to use `useRawAccessToken` with access token which is taken through auth library. [Document for useRawAccessToken](https://github.com/theoephraim/node-google-spreadsheet/blob/198e9c3aa6053f72f8a6e0da0f2019fcaa74f479/docs/classes/google-spreadsheet.md#userawaccesstokentoken-idfn-userawaccesstoken) [getAccessToken](https://github.com/googleapis/google-auth-library-nodejs/blob/v7.10.2/src/auth/googleauth.ts#L813)
> 
> ```js
> const { GoogleSpreadsheet } = require('google-spreadsheet');
> const { GoogleAuth } = require('google-auth-library');
> 
> const doc = new GoogleSpreadsheet('<the sheet ID from the url>');
> 
> const auth = new GoogleAuth({
>   scopes: 'https://www.googleapis.com/auth/spreadsheets'
> });
> const token = await auth.getAccessToken();
> 
> if (token == null) {
>   throw new Error("Failed to get access token")
> }
> 
> await doc.useRawAccessToken(token);
> ```

this is exactly what I was looking for except that I couldn't use default application credential from the `firebase login`.
you have to use the `service account`!
https://medium.com/google-cloud/google-oauth-credential-going-deeper-the-hard-way-f403cf3edf9d this medium post has perfect explanation.
