### ISSUE TITLE
using loadCells with GridRangeObject. Data inside GRO seems to get "lost"

### ISSUE THREAD

**Issue by christopherreay** [theoephraim/node-google-spreadsheet#347]
*** post complete ***

So I have trapped the uncaught error, and am writing this from the output:

the stack looks like (top at the top):
```
(anonymous)
arrayEach
forEach
_fillCellData
_updateOrCreateSheet
(anonymous)
arrayEach
forEach
loadCells
```

inside the loadCells frame, this is the value of `filtersArray`, defined on line 314 in GoogleSpreadsheet.js
```javascript
[
  {
    sheetId: 0,
    startRowIndex: 20,
    endRowIndex: 20,
    startColumnIndex: 0,
    endColumnIndex: 12
  }
]
```

by the time we arrive at `_fillCellData`, line 57, GoogleSpreadsheetWorksheet.js, we have this:

```javascript
_fillCellData(dataRanges) {
    _.each(dataRanges, (range) => {  // range = {startRow: 20, columnMetaData: Array(12)}
      const startRow = range.startRow || 0; // startRow = 20
      const startColumn = range.startColumn || 0; // startColumn = 0
// this next assignment causes an error:
      const numRows = range.rowMetadata.length; // rowMetadata = undefined
      const numColumns = range.columnMetadata.length;
```

**Comment by christopherreay** [comment]
OK, I worked out the bug.

`rowMetadata` is not loaded if there is only 1 row being loaded, using a `GridRangeObject`

I have changed my code to load 2 rows.

**Comment by theoephraim** [comment]
Hi @christopherreay - do you have any idea if this seemed to be an issue with the google API or this module?

**Comment by christopherreay** [comment]
No the faintest idea my friend :)

**Comment by theoephraim** [comment]
All good - I'll take a look. Thanks!

**Comment by theoephraim** [comment]
I can't reproduce this. If this is still an issue, please reopen with more details.
