### ISSUE TITLE
Can't change cells backgroundColor if it's not clean

### ISSUE THREAD

**Issue by Andreybest** [theoephraim/node-google-spreadsheet#353]
Title says it all. If the cells background color is not set (cleaned), it changes its color to the color that you written in your code, but if the cell that you edit already has background color, it will not change it.

Example code
```ts
import { GoogleSpreadsheet } from 'google-spreadsheet';

(async () => {
    const doc = new GoogleSpreadsheet('some id');

    await doc.useServiceAccountAuth(await import('./spreadsheets-api.json'));

    await doc.loadInfo();
    console.log(doc.title);
    const sheet = doc.sheetsByIndex[0];
    await sheet.loadCells('A1:E100')
    for (let i = 0; i < 10; i += 1) {
        const cell = sheet.getCell(i + 2, 2);
        cell.value = 'test';
        cell.backgroundColor = { alpha: 0, blue: 100, green: 100, red: 100 };
    }
    await sheet.saveUpdatedCells();
})();
```

**Comment by glister** [comment]
I'm experiencing exactly the same behaviour v3.0.11

**Comment by xse** [comment]
Encountered the same issue.
You can use `clearAllFormatting()` on multiple cells and save them all at once you don't have to save it every time.
As a side note, you're both using strange rgb values, those should be between 0 and 1.

**Comment by theoephraim** [comment]
Fix deploying shortly.
