### ISSUE TITLE
Heroku environment variable/auth issues

### ISSUE THREAD

**Issue by henryprescott** [theoephraim/node-google-spreadsheet#354]
Hi All, you're doing a great job!

I just wanted to offer up something I resolved myself today, that I thought could help with your documentation.

On the Authentication page there is a special mention for Heroku.  I was using the following and ran into issues myself:

`await doc.useServiceAccountAuth({`
`   client_email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,`
`  private_key: process.env.GOOGLE_PRIVATE_KEY,`
`});`

You mention about trying to replace `\n` with actual new lines. However, I found this solved the issue:

![image](https://user-images.githubusercontent.com/9204776/83311656-c57d1080-a207-11ea-8be3-855d53ad742f.png)

Hope this helps!

**Comment by codedpills** [comment]
@henryprescott Can you please explain why this works? That will be very helpful. Thanks in advance.

**Comment by henryprescott** [comment]
I assume it is because the "client_email" & "private_key" data is grabbed from the raw JSON file downloaded through the Google Developers console.

This means that if you copy those values into code as a string or using process.env some characters will be converted incorrectly.

However, if the raw values are parsed to JSON first (as above), this solves the problem.

**Comment by codedpills** [comment]
I can confirm that this works. I just wanted to understand why that is. Thanks a lot @henryprescott

**Comment by theoephraim** [comment]
thanks for leaving this note. Before I update the docs...
was there anything weird/special about what you did when _setting_ the config values on heroku?
It's been a while since I used heroku with this module but I recall you could set config vars from the command line and it would sometimes behave differently than when you do it from the browser.

**Comment by henryprescott** [comment]
> thanks for leaving this note. Before I update the docs...
> was there anything weird/special about what you did when _setting_ the config values on heroku?
> It's been a while since I used heroku with this module but I recall you could set config vars from the command line and it would sometimes behave differently than when you do it from the browser.

I set all the config vars through the settings section, so not sure about the command line issues you experienced, sorry.

**Comment by luisccode** [comment]
> Hi All, you're doing a great job!
> 
> I just wanted to offer up something I resolved myself today, that I thought could help with your documentation.
> 
> On the Authentication page there is a special mention for Heroku. I was using the following and ran into issues myself:
> 
> `await doc.useServiceAccountAuth({`
> ` client_email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,`
> ` private_key: process.env.GOOGLE_PRIVATE_KEY,`
> `});`
> 
> You mention about trying to replace `\n` with actual new lines. However, I found this solved the issue:
> 
> ![image](https://user-images.githubusercontent.com/9204776/83311656-c57d1080-a207-11ea-8be3-855d53ad742f.png)
> 
> Hope this helps!

Thank you @henryprescott  that works for me on AWS

**Comment by Maximization** [comment]
Thanks @henryprescott ! Also works for me with Netlify Functions

**Comment by sometimescasey** [comment]
I'll also add a link to this helpful comment https://github.com/theoephraim/node-google-spreadsheet/issues/373. tldr this also did the trick:

```
private_key: process.env.GOOGLE_PRIVATE_KEY.replace(/\\n/g, '\n'),
```

Following the instructions to replace newlines from the [auth docs](https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication) was not sufficient to get this working on Heroku:

![image](https://user-images.githubusercontent.com/16248601/117482523-80428200-af32-11eb-839e-27e24eab629a.png)

Thanks everyone!

**Comment by theoephraim** [comment]
I just added the other hint about replacing newlines to the docs, so hopefully that helps!
