### ISSUE TITLE
Strange addRow behaviour depending on contents of previous rows

### ISSUE THREAD

**Issue by brucem1976** [theoephraim/node-google-spreadsheet#355]
I have a 2 sheets of invoices (a and b), and I am using v3.0.11 of node-google-spreadsheet to write to these:
  `await a.addRow(invoice, { insert: true });`
and
  `await b.addRow(invoice, { insert: true });`

Strangely, everything added to 'a' has added properly, but each line in 'b' staggers - invoice 1 starts in column A, but then invoice 2 starts in column W, and then invoice 3 a further 22 columns later - column AS (there are 26 object memebers in an invoice - so invoice one occupies columns A-Z)

After much testing, I found that if I delete the pre-existing data in the sheet for all 'b' invoices (leaving the header row in row 1) it stops staggering on the writes. When I put it back, it starts staggering again. So somehow the existing data is having an effect on the writing of the row, and staggering it?!?!

I also tested with _addRow_ and _addRows_, and _{insert: true}_ present and absent, same issue.

If there is any more info I can supply, or testing I can do, please feel free to let me know,

**Comment by codedpills** [comment]
I faced a similar issue when I was trying to insert rows of data in  my sheet using
 `await sheet.addRow({firstItem: "some content", secondItem: "some other content"})`. 
Somehow with this method, the row added after a previous one always staggers. 

However, when i used `await sheet.addRow(["first item content", "second item content"])` 
the staggering stopped. Using this approach I think, keeps the original placement of the data in the columns based on the content of the header row which might look like this: `headerRow(["FirstHeader", "SecondHeader"])`. 
For instance "first item content" will be placed under the FirstHeader column, and so on.

This might not be totally related, but I thought that it will help.

**Comment by brucem1976** [comment]
Thanks @codedpills for this response - I changed it to use the ordered array you mention, and I get the same issue - strangely if I delete some of the existing data in the sheet, my code then works perfectly without staggering things, and as soon as a I put the deleted rows back it starts staggering again. So it's something to do with some of the existing data in the sheet?

**Comment by codedpills** [comment]
@brucem1976  Can you try recreating the header rows (using the ordered array), every time you append a new row? This might not be the most efficient way but it worked in my case. On every submission, I recreated the header row before appending a new row (also with the ordered array approach). Can you share your results after trying this? I'm curious.

**Comment by brucem1976** [comment]
@codedpills  I'll try find time to do this - however, the fact that I get the same stagger issue with an ordered array, only when I have a certain set of pre-populated data present, and it stops staggering once I remove the data (however, I don't remove the header row, so it can't be that it's the header row itself) shows that there's something wrong? I'm really curious as to why the staggering is specifically 22 rows each time, when the number of columns I add is 26....

**Comment by brucem1976** [comment]
@codedpills is the issue not possibly this - the Google examples include a range e.g.:
`POST https://sheets.googleapis.com/v4/spreadsheets/spreadsheetId/values/Sheet1!A1:E1:append
`
whereas node-google-spreadsheet has the sheet name but no range e.g.:
`POST https://sheets.googleapis.com/v4/spreadsheets/spreadsheetId/values/Sheet1:append`

Ref: https://developers.google.com/sheets/api/samples/writing#append_values

My understanding is that node-google-spreadsheet is not using the API to spec, and thus it could produce undefined behaviour?

**Comment by davidtraff** [comment]
Hi @brucem1976 . I am also having this issue. Did you come up with any solution?

**Comment by brucem1976** [comment]
@davidtraff unfortunately not, I am hoping my suggestion in https://github.com/theoephraim/node-google-spreadsheet/issues/355#issuecomment-640824996 could solve it.

**Comment by davidtraff** [comment]
@brucem1976 OK thanks for the quick reply. Will investigate a bit more too and post more if I find a fix.

**Comment by davidtraff** [comment]
I tried @brucem1976 's suggestion and changed the request to be in line with Google's examples, but that did not make a difference.

The only thing that worked for me was if I added the rows to a new sheet without a header (i.e a completely blank sheet). Having data above the inserted rows is what makes this weird stagger appear for some unknown reason.

But because this library requires a header to work I'll go with Google's own JS-implementation since I only need to create a new sheet and add some rows.

**Comment by brucem1976** [comment]
@davidtraff thanks for the feedback - glad to hear it is fairly easily reproducible by others.

**Comment by crstffr** [comment]
I just experienced a similar issue and identified that in my specific case, that the cell staggering was caused by having an empty cell in the last row prior to inserting a new row.

![Screen Shot 2020-06-25 at 12 48 16 PM](https://user-images.githubusercontent.com/44441/85772983-00794380-b6e3-11ea-9458-5ec806b6b8cf.png)

I am using the named column method for inserting the rows.

```javascript
const { rowNumber } = await sheet.addRow({
  Timestamp: timestamp,
  Name: name,
  Email: email
});
```

Perhaps others in this thread can confirm whether their dataset included empty cells in the last row prior to the offset row?

**Comment by brucem1976** [comment]
@crstffr yes mine also seems to have, and it also seems to determine by how many columns the staggering happens.

**Comment by davidtraff** [comment]
This wasn't the cause in my case. I tried replacing empty values but the staggering still happend.

**Comment by UtkarshChandel** [comment]
Yes same issue in my case when **having blank cells in the sheet**, Specially if the h**eaders are blank.**
The issue gets resolved once I **remove all the blank cells**...But I do require a few blank cells in my sheets sometimes.

**Comment by Impxrtant322** [comment]
Hey, is this issue solved yet? Im having the same problem lol.

**Comment by theoephraim** [comment]
Hey guys - so I think I have this solved. Basically the google API looks for the right "table" (continuous grid of data) to insert the data into and when there are gaps, some weird things can happen. By telling the endpoint to look for data starting at cell A1, it seems to operate as expected.

Deploying the fix shortly.

**Comment by brucelarasoft** [comment]
Great news @theoephraim - thanks so much!
