### ISSUE TITLE
row[id].save is not a function

### ISSUE THREAD

**Issue by hoangfuongduy** [theoephraim/node-google-spreadsheet#356]
I have a worksheet with 8 sheets
For each sheet, I would like to update the rows so I run on every sheet the same function
that is to loop throw the updated data I have and update the corresponding row[id] of the element by the content of that element.
But what I received is the error that said: row[id].save is not a function.
Please help if you know how to solve this problem.

**Comment by Pzkane** [comment]
I've noticed that you're using `row[id]` instead of `rows[id]`. If you need to save `row` in a loop (for, mapping), just use `row.save()`.

**Comment by theoephraim** [comment]
Happy to help, but I need more to go on. Feel free to open a new issue with more code.
