### ISSUE TITLE
Add row seems to succeed but row nowhere to be found

### ISSUE THREAD

**Issue by Tsopic** [theoephraim/node-google-spreadsheet#361]
I'm adding a row to table by using Headers as key-s.

It seems to be somewhat working, when I console.log out the result of `const row = sheet.addRow(data)`  it has all the properties about the sheet, and header values, and _rawData etc. 

Strange because on another sheet I use similar logic and everything works as expected.

I've seen issue of bot account not being able to access the spreadsheet due protection before, in that case, I get an error as expected. With this anomaly, there are 0 errors.

using v 3.0.11

**Comment by tomchambers2** [comment]
I had this issue because my data was incorrectly formatted, so the write succeeed but the values were undefined because I misread the docs which was a bit confusing as nothing seemed to have gone wrong until I put some logs in the module

I had
```
sheet
    .addRow({ rowValues: { user: "lala", text: "blah" } }, { insert: true })
```

which should have been
```
sheet
    .addRow({ user: "lala", text: "blah" }, { insert: true })
```

**Comment by theoephraim** [comment]
Seems like this is resolve? Can I close?

@tomchambers2  - Any suggestions about what would have made the docs clearer?

**Comment by Tsopic** [comment]
> Seems like this is resolve? Can I close?
> 
> @tomchambers2 - Any suggestions about what would have made the docs clearer?

I did not find any documentation about what the `insert : true` does, could you point me to right direction

**Comment by Tsopic** [comment]
https://theoephraim.github.io/node-google-spreadsheet/#/classes/google-spreadsheet-worksheet?id=fn-addrow 

Actually think we ok. I still need to test if it works. I'll close it myself 👍
