### ISSUE TITLE
Spreadsheet last modified date or version

### ISSUE THREAD

**Issue by briang123** [theoephraim/node-google-spreadsheet#364]
Is there a way to know whether the data I have in memory is stale? It would be helpful to provide sheet properties with a data version or last modified date so we know whether to requery the spreadsheet or can continue using the data we have locally. In my case, I'm using the sheets as a results db and don't need to query all the time if I don't have to.

**Comment by theoephraim** [comment]
Doesn't look like it's supported by the sheets API itself, but rather you'd have to fetch the updated timestamp from the Drive API. Might be useful, but it's starting to border on the edge of the scope of this module.

Feel free to dig in and see what it would look like though! If it's straightforward it could be a good addition, but not sure I'll have time to implement myself.

**Comment by theoephraim** [comment]
Going to close this for now, as I dont think I'll add this in unless adding a whole bunch of other drive API based calls.
