### ISSUE TITLE
Insert a row at a specific position in google sheet

### ISSUE THREAD

**Issue by vaideshshank** [theoephraim/node-google-spreadsheet#366]
Hi @theoephraim , I wanted to inserted a row at specific position (row number A,B,C,etc) in the sheet using add row function. I guess it always appends the row after the last filled row.

**Comment by theoephraim** [comment]
The addRows function internally uses sheets API [append](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/append) functionality which really is looking for a "table" of data  within you sheet and then appending to the end, so unfortunately it wouldnt work.

Looks like to add rows in the middle of the existing data, you'd need to use the [insertDimension](https://developers.google.com/sheets/api/samples/rowcolumn#insert_an_empty_row_or_column) api endpoint which I have not yet implemented.

PRs welcome!

**Comment by vaideshshank** [comment]
Sure , I'll try to find a solution for this. I was able to get a workaround to this problem some time ago for implementation in a project. I'll try to revisit this thing in some days.

**Comment by DanielBailey-web** [comment]
@theoephraim  , #428 Seems to have added insertDimension.
