### ISSUE TITLE
Single quotes being added to DATE at the beginning in spreadsheet

### ISSUE THREAD

**Issue by vinodhreddygs** [theoephraim/node-google-spreadsheet#367]
Hi @theoephraim ,

When **Dates** are added to the spreadsheet they are preceded with a ' but this should not happen. Is there any way to prevent by adding ' at the beginning of Dates?  
Please refer the below screen shot for the reference:

![image](https://user-images.githubusercontent.com/37541181/86109823-6bab8700-bae2-11ea-9f74-5c98e6179074.png)

Thanks.

**Comment by tsouza** [comment]
I got the same issue. Any workaround?

**Comment by vinodhreddygs** [comment]
> I got the same issue. Any workaround?

Still no luck!

**Comment by RobertSmith8** [comment]
My ugly workaround is to use a helper column like = A1*1
```
           rawData.getCell(min+j, 4).formula = '=F' + String(min+j+1)+'*1'
           rawData.getCell(min+j, 5).value = moment().format('YYYY-MM-DD HH:mm')
```

**Comment by Nemnon** [comment]
Correction is very necessary, otherwise you have to be perverted

**Comment by Nemnon** [comment]
USER_ENTERED or RAW method
if RAW, then ' - added

**Comment by antony** [comment]
It's because you're setting the date as a string. See https://github.com/theoephraim/node-google-spreadsheet/issues/363#issuecomment-1437308370

**Comment by theoephraim** [comment]
combining into #630
