### ISSUE TITLE
Support creating new spreadsheet document

### ISSUE THREAD

**Issue by StanleySathler** [theoephraim/node-google-spreadsheet#368]
Hey guys :v: 
Thanks for the awesome work! :star2: 

From what I understood, the `GoogleSpreadsheet` constructor expects a Sheet ID, which makes me think we should have an existent one before doing anything.

Is there any way to create a Sheet from scratch using this library? Just as if I was "uploading" a new Sheet file?

**Comment by theoephraim** [comment]
Looks like it should be possible but did not implement it yet. Will try to add in the next batch of updates.

**Comment by StanleySathler** [comment]
Can I do this? I could try in a few days.

**Comment by suryasarafe** [comment]
great library, hope this feature come soon..

**Comment by RCiv277** [comment]
This added functionality on my todo list how would you undertake adding it to the module

**Comment by theoephraim** [comment]
This is now supported - see https://theoephraim.github.io/node-google-spreadsheet/#/classes/google-spreadsheet?id=creating-a-new-document

**Comment by fosteman** [comment]
```
As this will create the document owned by the auth method you are using (which is often a service account), it may not be accessible to your google account. Therefore if it recommended to create documents ahead of time if possible rather than using this method.
```

Is there a way to change the sharing settings ? Or should we use oAuth2 method of creation instead ?
