### ISSUE TITLE
Setting a rich text cell value

### ISSUE THREAD

**Issue by andyli** [theoephraim/node-google-spreadsheet#369]
It's possible to use rich text cell value in Google spreadsheet. For example, parts of the cell text is applied with different colour or hyperlinked:

![docs google com_spreadsheets_d_1OXVTI1DsZK9tSulJmfXAD5-pUyRneIuM6zzwmIL_SJQ_edit](https://user-images.githubusercontent.com/103977/86510936-eba95800-be26-11ea-8cf4-3101c24bff41.png)

I cannot figure out how to do this with this package. Any pointer is appreciated.

**Comment by Impxrtant322** [comment]
You can use a cell formula code with the following formula: =HYPERLINK("LINK","TEXT")

To find a cell, go to this documentation:
https://theoephraim.github.io/node-google-spreadsheet/#/classes/google-spreadsheet-cell

**Comment by theoephraim** [comment]
thanks @Impxrtant322!
