### ISSUE TITLE
Finding a row based on row values

### ISSUE THREAD

**Issue by QkeleQ10** [theoephraim/node-google-spreadsheet#371]
Let's say I've got two rows:
name: "abc"
name: "xyz"

I don't know which row number the "abc" row belongs to. Is there any way to grab the row with name "abc"?

**Comment by QkeleQ10** [comment]
I figured it out, I had to use 
```
const rows = await sheet.getRows()
const resultRow = rows.find(r => r.name === "abc")
```
(you can replace _r._**name** and **"abc"** with your fields and terms)

**Comment by StErMi** [comment]
I don't think that this is a viable way if you have a lot (> 10k) records in the sheet
