### ISSUE TITLE
Writing into Cells

### ISSUE THREAD

**Issue by Sattishh** [theoephraim/node-google-spreadsheet#376]
I was wondering how I could write a data to a specific Cell.

Thanks in advance!!

**Comment by TheMastermindPT** [comment]
First you have to get the cell by loading them from the sheet.
 await sheet.loadCells('A1:D5');
Then you save the specific cell into a variable.
 const yourcell =  await sheet.getCellByA1('A1');
Then you can change the value.
 yourcell.value = 'The string you want to write'

**Comment by Sattishh** [comment]
Thank you!
