### ISSUE TITLE
Header rows being filled in and addRow filling in a row instead of adding a row

### ISSUE THREAD

**Issue by Impxrtant322** [theoephraim/node-google-spreadsheet#381]
With the new update, it introduces new problems. One of these problems is that if a header row is filled in from lets say, the A2 cell and onwards, instead of A1 cell, it will replace the header row with the information that is supposed to be in a new row. This issue is not present as long as the A1 cell or any empty cell behind the header row is filled in.

Expected:
![image](https://user-images.githubusercontent.com/63988752/90375767-a33ea600-e032-11ea-803c-279025a19ef4.png)

Reality:
![image](https://user-images.githubusercontent.com/63988752/90375817-b2255880-e032-11ea-8caf-fbd6d84963fb.png)
(Information is filled into the header rows if header cells to the left is empty)

addRow now fills in rows instead of adding rows in with information. 

EDIT: addRow issue can be fixed by adding {insert: true} to the options

Expected:
![image](https://user-images.githubusercontent.com/63988752/90375994-00d2f280-e033-11ea-9bfa-4e1a88bed1dc.png)

Reality:
![image](https://user-images.githubusercontent.com/63988752/90375958-f0bb1300-e032-11ea-983d-3e6b587ff4bc.png)
(fills in row instead of adding row)

Hope you can fix this! Thanks.

**Comment by zeritte** [comment]
use insert: true

`await sheet.addRow(values, { insert: true });`

**Comment by Impxrtant322** [comment]
Whoops, forgot to close this issue!

Ive found that solution already, thank you!
