### ISSUE TITLE
Doesn't work in IE11

### ISSUE THREAD

**Issue by HiroNoobs** [theoephraim/node-google-spreadsheet#382]
It occurred while confirming the operation with IE11.
Generated content
SCRIPT1010: Missing identifier.
Read part
/***/ "./node_modules/google-spreadsheet/index.js":
/*!**************************************************!*\
  !*** ./node_modules/google-spreadsheet/index.js ***!
  \**************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

eval("const GoogleSpreadsheet = __webpack_require__(/*! ./lib/GoogleSpreadsheet */ \"./node_modules/google-spreadsheet/lib/GoogleSpreadsheet.js\");\nconst GoogleSpreadsheetWorksheet = __webpack_require__(/*! ./lib/GoogleSpreadsheetWorksheet */ \"./node_modules/google-spreadsheet/lib/GoogleSpreadsheetWorksheet.js\");\nconst GoogleSpreadsheetRow = __webpack_require__(/*! ./lib/GoogleSpreadsheetRow */ \"./node_modules/google-spreadsheet/lib/GoogleSpreadsheetRow.js\");\n\nconst { GoogleSpreadsheetFormulaError } = __webpack_require__(/*! ./lib/errors */ \"./node_modules/google-spreadsheet/lib/errors.js\");\n\nmodule.exports = {\n  GoogleSpreadsheet,\n  GoogleSpreadsheetWorksheet,\n  GoogleSpreadsheetRow,\n\n  GoogleSpreadsheetFormulaError,\n};\n//# sourceURL=[module]\n//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiLi9ub2RlX21vZHVsZXMvZ29vZ2xlLXNwcmVhZHNoZWV0L2luZGV4LmpzLmpzIiwic291cmNlcyI6WyJ3ZWJwYWNrOi8vLy4vbm9kZV9tb2R1bGVzL2dvb2dsZS1zcHJlYWRzaGVldC9pbmRleC5qcz9kMzQwIl0sInNvdXJjZXNDb250ZW50IjpbImNvbnN0IEdvb2dsZVNwcmVhZHNoZWV0ID0gcmVxdWlyZSgnLi9saWIvR29vZ2xlU3ByZWFkc2hlZXQnKTtcbmNvbnN0IEdvb2dsZVNwcmVhZHNoZWV0V29ya3NoZWV0ID0gcmVxdWlyZSgnLi9saWIvR29vZ2xlU3ByZWFkc2hlZXRXb3Jrc2hlZXQnKTtcbmNvbnN0IEdvb2dsZVNwcmVhZHNoZWV0Um93ID0gcmVxdWlyZSgnLi9saWIvR29vZ2xlU3ByZWFkc2hlZXRSb3cnKTtcblxuY29uc3QgeyBHb29nbGVTcHJlYWRzaGVldEZvcm11bGFFcnJvciB9ID0gcmVxdWlyZSgnLi9saWIvZXJyb3JzJyk7XG5cbm1vZHVsZS5leHBvcnRzID0ge1xuICBHb29nbGVTcHJlYWRzaGVldCxcbiAgR29vZ2xlU3ByZWFkc2hlZXRXb3Jrc2hlZXQsXG4gIEdvb2dsZVNwcmVhZHNoZWV0Um93LFxuXG4gIEdvb2dsZVNwcmVhZHNoZWV0Rm9ybXVsYUVycm9yLFxufTtcbiJdLCJtYXBwaW5ncyI6IkFBQUE7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7Iiwic291cmNlUm9vdCI6IiJ9\n//# sourceURL=webpack-internal:///./node_modules/google-spreadsheet/index.js\n");

/***/ }),

**Comment by theoephraim** [comment]
Please try with the latest version. If still an issue, reopen.
