### ISSUE TITLE
How to turn off verbose axios output to console?

### ISSUE THREAD

**Issue by g-borgulya** [theoephraim/node-google-spreadsheet#383]
Sometimes I run into Google API rate limits. In this case axios raises and error. My real problem is that axios puts hundreds of lines to the console, making the output completely unreadable. As axios is used by this module under the hood, I have no idea how to turn the verbose output off. Is that possible?

**Comment by g-borgulya** [comment]
I'm sorry, it's totally controllable, my bad that I didn't realize.

**Comment by sarahkittyy** [comment]
How did you fix it? @g-borgulya
