### ISSUE TITLE
Cell does not allow recolor (.backgroundColor accept only one time)

### ISSUE THREAD

**Issue by biruelrick** [theoephraim/node-google-spreadsheet#387]
Following this example (from [https://theoephraim.github.io/node-google-spreadsheet/#/classes/google-spreadsheet-cell](https://theoephraim.github.io/node-google-spreadsheet/#/classes/google-spreadsheet-cell))....

```
cellA1.note = 'This is cell A1';
cellA1.value = 123.45;
cellA1.textFormat = { bold: true };
cellC3.formula = '=A1';
await sheet.saveUpdatedCells(); // saves both cells in one API call
console.log(cellC3.value); // 123.45
```
...this works fine... so, I added the following background color before the 'await sheet.saveUpdatedCells();' command line...

```
cellA1.backgroundColor = {'red':1, 'green':0, 'blue':0};
```
.... and the cellA1 became RED as expected... so, I run the code again but with the following object color {'red':0, 'green':1, 'blue':0}; but nothing else happens... I can close and open the google spreadsheet and the color continues red...

**Comment by theoephraim** [comment]
I'm able to change cell backgrounds multiple times without issue.

Can you provide your example code and I'll check it out?

**Comment by theoephraim** [comment]
closing for now. Please reopen if you can provide a code sample
