### ISSUE TITLE
addRows: Support for specifying per-column cell format

### ISSUE THREAD

**Issue by caesarsol** [theoephraim/node-google-spreadsheet#395]
Whenever I insert data in a spreadsheet, it would be useful to have the `numberFormat` options in the `addRows` function, that could be forced for the entire column (because that's often what everyone wants when using it, I guess).

I can think of a PR in a few days, if it could be useful to you.

Thanks for the very interesting library!

**Comment by theoephraim** [comment]
open to PRs, but the row-based methods use google's "append" functionality which unfortunately doesnt give any way to hook into formatting :( You really have to drop down to the cell methods to do anything with formatting.
