### ISSUE TITLE
Is there anyway we can fetch header values?

### ISSUE THREAD

**Issue by ramseth001** [theoephraim/node-google-spreadsheet#396]
I am trying to fetch header values. Is there anyway we can fetch header values? like sheet.getHeaderValues() ?

**Comment by Josh979** [comment]
sheet.headerValues returns an array of the header values.

**Comment by theoephraim** [comment]
There is also a function `sheet.loadHeaderRow()`
https://github.com/theoephraim/node-google-spreadsheet/blob/master/lib/GoogleSpreadsheetWorksheet.js#L289

But it is not documented, as you would normally just call getRows(). We can add to the docs too if it may be useful.
