### ISSUE TITLE
Update/save multiple rows via a single API call? 

### ISSUE THREAD

**Issue by Josh979** [theoephraim/node-google-spreadsheet#397]
This package works wonderfully, however I've found that Google's API rate limits aren't very useful when trying to do write heavy operations (ie find and replaces). Is there any way to save multiple changed rows in a sheet through a single API call?

I'm currently using the ```row.save()``` method, going row to row, spacing the save calls 1.1 seconds apart to avoid hitting the 1 write call/second rate limit. It seems like there must be a better alternative that I'm just missing?

**Comment by doublesharp** [comment]
In my code I am loaded the content from the sheet, updating in batches of 150 rows, then calling `await sheet.saveUpdatedCells();` to batch update.

**Comment by Josh979** [comment]
@doublesharp  Works for me, thanks!

**Comment by BradBailey-web** [comment]
Why are you using batches of 150?

**Comment by EskelCz** [comment]
@theoephraim Is this still possible with the latest version? I don't see the `saveUpdatedCells` method in the documentation and when I call it, the updated rows are not saved. It doesn't throw an error, so I'm left wondering what is happening and feel a bit stuck, because I really need batch saving. Thanks for any advice.

**Comment by theoephraim** [comment]
@EskelCz - There is a batch save using the _cell based API_. See https://theoephraim.github.io/node-google-spreadsheet/#/classes/google-spreadsheet-worksheet?id=fn-saveupdatedcells

For the row-based API, there is a batch insert method, but not currently a batch update method. It could certainly be added, but I don't think it's trivial.
