### ISSUE TITLE
rate limit for the api

### ISSUE THREAD

**Issue by mderazon** [theoephraim/node-google-spreadsheet#40]
This is not an issue related to this module,

Has anyone experienced rate limit problems ?
I have a spreadsheet with around 200 worksheets, I want to bring them all so I iterate the worksheets and do `getRows()`.

I quickly run into

```
HTTP error 429: Too Many Requests
```

I can limit the amount of parallel calls, but I am wondering if there's any way to lift this limit.

Thanks for the great lib :+1:

**Comment by svanderw** [comment]
I'm currently running into the too many requests/too many edits. I'm currently thinking to implement batching of edits (it seems trivial). Although this won't resolve the too many requests issue, it should reduce the number of requests necessary by a large margin (in cell based feeds at least)

**Comment by debanjanbasu** [comment]
The only way so far that I have managed to make it work is :

```
function addRow(orderstream, sheet1, doc, i) {
    // pause the stream
    orderstream.pause();
    // start adding the data
    sheet1.addRow({
        'Order ID': doc.id,
        // the other data attributes to be added
    }, (err) => {
        // callback
        if (err) {
            // log the error
            // console.log(err);
            console.log('Inventman was unable to add a row due to some Google API error');
            // start calling the addRow(orderstream, sheet1, doc, i); again recursively after 31 seconds
            setTimeout(() => {
                addRow(orderstream, sheet1, doc, i);
            }, 31000);
        } else {
            // data added successfully
            if (++i < doc.products.length) {
                // only if it does not exceed the length
                addRow(orderstream, sheet1, doc, i);
            } else {
                // resume the stream for next doc
                orderstream.resume();
            }
        }
    });
}
```
The code might seem crazy but actually works wonderfully as the addRow function uses a callback and recursively adds 1 row only after the previous row has been added. Any other way even if you send 5 requests/sec for more than 30 sec will result in 429 errors.

The above code is controlled by using a stream:

```
// spreadsheet key - the long id in sheets url
        let my_sheet = new GoogleSpreadsheet(config.spreadsheet_id);
        // With auth -- read + write
        let creds = require(config.path_gapi_key);
        my_sheet.useServiceAccountAuth(creds, (err) => {
            // getInfo returns info about the sheet and an array or "worksheet" objects
            my_sheet.getInfo((err, sheet_info) => {
                console.log(sheet_info.title + ' is loaded');
                // assign sheet1/Orders
                let sheet1 = sheet_info.worksheets[0];
                // create the cursor
                Order.collection.find({}, (err, cursor) => {
                    // once the database is connected retrieve the existing rows in memory
                    sheet1.getRows((err, rows) => {
                        if (err) {
                            console.log(err);
                        } else {
                            console.log('The rows have been fetched in memory');
                            // retrieve the actual cursor from MongoDB and add the flag
                            cursor.addCursorFlag('noCursorTimeout', true);
                            // create a mongoose stream
                            let orderstream = cursor.stream();
                            // start listening to events on the stream
                            orderstream.on('data', (doc) => {
                                // check if data already exists
                                if (!findId(rows, doc.id)) {
                                    // add some data
                                    addRow(orderstream, sheet1, doc, 0);
                                } else {
                                    orderstream.resume();
                                }
                            }).on('error', (err) => {
                                console.log(err);
                                // send success
                                res.json({
                                    'status': 'failure'
                                });
                            }).on('end', () => {
                                // the stream is ended
                                // send success
                                res.json({
                                    'status': 'success'
                                });
                            });
                        }
                    });
                });
            });
        });
```
The above code relies on stream. However, then again Mongoose seems unable to control the timeout of the MongoDB cursor so I had to use the native cursor element and process the DB.

Hope it helps. Lemme know if you need any further help :+1:

**Comment by dsifford** [comment]
For anybody still interested in a solution for this, I had success using the `async` package + `setTimeout`.

The data that I was interesed in appending to my spreadsheet was in JSON format. I needed to proceed through the array and save content from each object within the array.

Here's an example:

```js
var myJSONData = [
  {
    "name": "Tom", 
    "age": 45
  },
  {
    "name": "Bill",
    "age": 59
  }
  // .... etc
]

async.eachSeries(myJSONData, function(item, callback) {
  sheet_info.worksheets[index].addRow({
      Name: item.name,
      Age: item.age
    }, function(err) {
         if (err) {
           console.log('Too many requests');
         } else {
            setTimeout(function() {
            callback();
            }, 50);
         }
     }
});
```

Obviously, the example is much more rudimentary than the real thing. Hopefully, you get the idea.

I made ~500 or so requests using this method without any issues.

**Comment by guido4000** [comment]
@dsifford your solution worked like a charm. I just had to set the timeout to 100 ms.

**Comment by JulienDemarque** [comment]
The v4 of google sheets api says it is 100 request per user per 100 seconds. Basically 1 request per second!
It says also that with a paid plan we can ask for more. But I have a question related to that. For using node-google-spreadsheet we are enabling Google Drive API, not Google Sheets API, why is that so?
I have a hard time understanding what's going on, node-google-spreadsheet is a layer on top of the google sheets api to make it more simple, right?

**Comment by theoephraim** [comment]
FYI - I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020). **YOU MUST MIGRATE IF YOU ARE STILL USING THIS PACKAGE!**

**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

There are still rate limits, but the v4 api has many more options of how to interact.
I may add some more methods to do bulk row adding if it seems to still be a problem.

Also the v4 api is now using the "Sheets API" and not Google Drive anymore.

Thanks! 😄
