### ISSUE TITLE
sheet.getCell ERROR

### ISSUE THREAD

**Issue by WayneChang65** [theoephraim/node-google-spreadsheet#405]
Hi @theoephraim ,
Thanks for the great project.

I wrote a sample code as below which is used to test V4 api simply.
```javascript
'use strict';
const os = require('os');
const { GoogleSpreadsheet } = require('google-spreadsheet');
const g_secret = require(os.homedir() + '/client_secret.json');
const c = require('./const_def.js').init();

let gDoc;

async function main () {
	gDoc = new GoogleSpreadsheet(c.TOSMM_GSID_WTESTWATER);
	await gDoc.useServiceAccountAuth(g_secret);
	await gDoc.loadInfo();
	console.log(gDoc.title);

	const sheet = gDoc.sheetsByIndex[0]; 
	console.log(sheet.title);
	console.log(sheet.rowCount);

	const a1 = sheet.getCell(0, 0);
	console.log(a1.value);
}

main();
```
After running it, the error came out (**Error: This cell has not been loaded yet**)

<img width="1280" alt="截圖 2020-10-25 23 28 38" src="https://user-images.githubusercontent.com/33888917/97111455-d760d200-1719-11eb-9640-05b5d2aac609.png">

here is the google spreadsheet table
<img width="1218" alt="截圖 2020-10-25 23 29 53" src="https://user-images.githubusercontent.com/33888917/97111494-ffe8cc00-1719-11eb-8163-b6a04ccd9e5d.png">

To get sheet.title and rowCount seem to be correct but to call **getCell** occurs this exception.

Now I am trying to switch v3 to v4 api and need your help. Thanks.

**Comment by theoephraim** [comment]
You just need to call (`sheet.loadCells`)[https://theoephraim.github.io/node-google-spreadsheet/#/classes/google-spreadsheet-worksheet?id=fn-loadcells] first which actually fetches the cells. Then getCell tries to find the cell in the loaded cache.

**Comment by WayneChang65** [comment]
OK. Thanks a lot.
