### ISSUE TITLE
Can we use this in react native

### ISSUE THREAD

**Issue by achyuthjoism** [theoephraim/node-google-spreadsheet#406]
i am getting an error of 
Unable to resolve module `child_process` from `node_modules\google-auth-library\build\src\auth\googleauth.js`: child_process could not be found within the project.

pls help

**Comment by aymza** [comment]
Same issue, I'm quite a beginner and cannot figure out how to have it work (using expo).
"const { GoogleSpreadsheet } = require('google-spreadsheet');" gives this error.
Should I "import" something instead of require ?
Or maybe a basic example full code ?
Thanks !

**Comment by salikadave** [comment]
Can you share a code snippet of the error it throws?

Also, I maybe wrong about this, but this package is not listed in the React Native Directory (directory of packages compatible with React Native with or without Expo).  
According to the RN docs, if a package is not listed in the directory, it's not compatible with RN.

According to the Expo Team, a Node.js package may or may not work on RN. Read here [https://forums.expo.io/t/can-i-use-node-js-packages-with-expo/2906](url)

**Comment by achyuthjoism** [comment]
I believe that we need to make the react native workflow server-side.
or 
We should use get and fetch method in the react native app

Hope it helps.

**Comment by LucasBarbosaSilva** [comment]
@achyuthjoism  Could you explain better how to do this process in React Native. I'm still a beginner.

**Comment by achyuthjoism** [comment]
@LucasBarbosaSilva Sir i could not solve the issue with React native so I switched to flutter, where you have a very good package called [GSheet](https://github.com/a-marenkov/gsheets) which is very useful and immutable.
So switch to flutter.
Hope it helps.

**Comment by theoephraim** [comment]
Please try out the latest version and reopen if still having issues.
