### ISSUE TITLE
Specify headerRow

### ISSUE THREAD

**Issue by nabeards** [theoephraim/node-google-spreadsheet#407]
Is there a way we could expand `loadHeaderRow` to accept a specific row to load as the headers? I have some sheets with, e.g., the first four rows reserved and then the fifth row has the headers, with the data below that.

Looks like `loadHeaderRow` and `setHeaderRow` would have to be expanded to accept the row ID. But, since `loadHeaderRow` is run by other functions, how could we set the desired headerRow somewhere so that these other functions can see it?

**Comment by theoephraim** [comment]
I think it would be doable. You would just have to store that row index somewhere and you would have to call whatever sets it before fetching any rows. Open to PRs!

**Comment by VictorCazanave** [comment]
I think https://github.com/theoephraim/node-google-spreadsheet/issues/442 is the same issue. Hope the PR can be reviewed and merged soon, because I also need this feature 😸

**Comment by theoephraim** [comment]
This is now available in v3.2
