### ISSUE TITLE
getRows fails after empty row

### ISSUE THREAD

**Issue by mlconnor** [theoephraim/node-google-spreadsheet#41]
I have a table as follow in Google Docs.  There is only a single column and there is a blank row after "fred".  All rows after fred are suppressed.  : (

users
mike
bob
fred

jeff
john

**Comment by mlconnor** [comment]
Digging further, it appears that Google Docs does is the culprit.  There is nothing this library can do if Google docs doesn't send the right data back.

**Comment by mlconnor** [comment]
one other thought.  if I use getCells it will returns the data.  it would be possible to reImplement getRows using getCells if we really needed to get around this issues.

**Comment by theoephraim** [comment]
you are correct! its an issue with the API.
You could reimplement `getRows` using `getCells` but I think it makes sense to just pick whichever one makes more sense for your specific app and document.

The empty row thing has definitely bit me before though, especially when you are letting other people edit the doc...
