### ISSUE TITLE
How to working with border and / or styling

### ISSUE THREAD

**Issue by suryasarafe** [theoephraim/node-google-spreadsheet#411]
Hi there,

I just making some data that have some number and text, 
![image](https://user-images.githubusercontent.com/25929921/100082499-e5ba1f00-2e7a-11eb-81e3-3d0d61b700db.png)

And I want to make like this, (add border, bold text and text aligment)
![image](https://user-images.githubusercontent.com/25929921/100082613-08e4ce80-2e7b-11eb-840c-1917d2d68b9f.png)

Any documentation for this kind or something I can work with.?

**Comment by theoephraim** [comment]
Check out the docs about [cell formatting](https://theoephraim.github.io/node-google-spreadsheet/#/classes/google-spreadsheet-cell?id=cell-formatting)

You can update the formatting properties and then call `sheet.saveUpdatedCells()` and it should do the trick.
