### ISSUE TITLE
Row save is replacing formula with last calculated value

### ISSUE THREAD

**Issue by Tsopic** [theoephraim/node-google-spreadsheet#416]
I'm using this library, to update some data in my sheet. 

The problem is with row save, where formulas, in the unaffected column gets replaced with the last formula calculated value and renders these formulas into static values. 

Is anyone experiencing the same issue?

**Comment by theoephraim** [comment]
Unfortunately, this is just how the row-based api works, because it's setting the values as if you typed them into the sheets UI.

Check out the docs here - https://theoephraim.github.io/node-google-spreadsheet/#/classes/google-spreadsheet-row?id=formulas
