### ISSUE TITLE
How to merge two GoogleSpreadsheetWorksheet?

### ISSUE THREAD

**Issue by StErMi** [theoephraim/node-google-spreadsheet#420]
I have two different GoogleSpreadsheetWorksheet with the same content format. I would like to create a third one that will be as a result GoogleSpreadsheetWorksheet1 + GoogleSpreadsheetWorksheet2.

Is it possible to do it with the current API?

**Comment by theoephraim** [comment]
I dont think there is a way to do this using google's api. YOud have to just fetch the data and then write it into another.

You could start by using the [copy worksheet](https://theoephraim.github.io/node-google-spreadsheet/#/classes/google-spreadsheet-worksheet?id=fn-copytospreadsheet) method for the first sheet and then reading/writing the data from the second sheet.
