### ISSUE TITLE
TypeError: sheet.copyToSpreadSheet is not a function

### ISSUE THREAD

**Issue by StErMi** [theoephraim/node-google-spreadsheet#421]
I'm using `"google-spreadsheet": "^3.0.14"` with `"@types/google-spreadsheet": "^3.0.2"` and when I try to do `await sheet.copyToSpreadSheet(targetDocData.id);` I get that error.

**Comment by theoephraim** [comment]
looks like the method is called `copyToSpreadsheet`
https://theoephraim.github.io/node-google-spreadsheet/#/classes/google-spreadsheet-worksheet?id=fn-copytospreadsheet
