### ISSUE TITLE
sheet.saveUpdatedCells() is not working

### ISSUE THREAD

**Issue by garbagefactory** [theoephraim/node-google-spreadsheet#422]
Hello, I am trying to write data into the spreadsheet on a row basis. `data[i].save()` (row array) is not updating the row, nor is `sheet.saveUpdatedCells()`. It's not that it's not recognizing it as a function, it just isn't doing anything it seems. Am I doing it wrong?

``` 
await doc.loadInfo();
sheet = doc.sheetsByIndex[0];
data = await sheet.getRows().then((q) => {
  return q.map((v) => v._rawData);
});

console.log(data)

voterID = message.author.id //using discord.js :)

for (i = 0; i < data.length; i++) {
  if (data[i][5].includes(voterID)) {
    data[i][5].replace(`${voterID}, `, "")
  }

  data[earned - 1] += `${voterID}, ` // earned - 1  is the selected row that the user is voting on, appends their id to the total ID string
  await sheet.saveUpdatedCells();
}
```

**Comment by theoephraim** [comment]
You must interact with the SpreadsheetRow objects if you want to be able to save updates. Your data array is not an array of those rows but just an array of the `_rawData` objects that is used by them internally.

Also, the row and cell based apis are very different and do not interact like this. You have to make updates and save them using one or the other.
