### ISSUE TITLE
Cannot get Google Sheet author's email as in last version

### ISSUE THREAD

**Issue by ariestav** [theoephraim/node-google-spreadsheet#423]
Hello,

Thank you for updating this to support v4 of Google Sheets API.  In the previous version we were able to get the Sheet author and email address.  I'm using the `.loadInfo()` method, but there are only basic details about the sheet.  Is there any way to retrieve author information about the sheet?

Thanks!

**Comment by theoephraim** [comment]
Unfortunately, I don't think this is supported anymore in the v4 api. I assume you could get that info using the Drive API?
If you do find a way in the v4 api from google's docs, please let me know!

Also if you do want to implement a feature in this tool that would fetch that data using the drive API, I'd definitely want to include it!

Thanks

**Comment by ariestav** [comment]
Thanks, yes I see that now.  And yeah, we would probably need to use the Drive API to gather that information.  Thank you for the guidance.
