### ISSUE TITLE
[Not Issue] How is the docs accessed when using in VS Code

### ISSUE THREAD

**Issue by akaShivam** [theoephraim/node-google-spreadsheet#427]
When using this library in VS Code we get description for functions and parameters. But I don't see any JSDoc comment in any of the js files downloaded for the project by npm.
Could someone explain where is the docs accessed from?

**Comment by theoephraim** [comment]
Are you using typescript? Are you using the type files from https://www.npmjs.com/package/@types/google-spreadsheet

**Comment by akaShivam** [comment]
Yup, it was there in the files in @types directory. I will close the issue.
Thanks :)
