### ISSUE TITLE
row.delete() not deleting row, instead is just formatting row

### ISSUE THREAD

**Issue by Betanoir** [theoephraim/node-google-spreadsheet#430]
I am attempting to delete a row from my sheet entirely using the index from sheet.getRows(), instead of just clearing the values and clearing colour format. A little information: I am not using a form, instead, I am using a Discord bot to get responses from users, and posting their responses to the sheet using this library. I need the row to be deleted entirely as for this remove function, you are able to remove any rows, even ones with values on both sides of them.

Here is my code, please tell me if I have made a mistake, I have gone over all the documentation already, in attempt to check if I have missed another method I could use instead.

![image](https://user-images.githubusercontent.com/30844254/104133457-5ca86a00-538c-11eb-9dff-5b09f38bcf71.png)

What I get after the function is run:

![image](https://user-images.githubusercontent.com/30844254/104133553-f7a14400-538c-11eb-8a14-f662f45ca19a.png)

vs what I need: (The last row being deleted entirely)

![image](https://user-images.githubusercontent.com/30844254/104133536-dfc9c000-538c-11eb-81ef-0ffd4814ed38.png)

**Comment by theoephraim** [comment]
The cell-based methods and row-based methods are not really designed to be used together.
If you stick with row-based method calls, it should do the trick.

If you absolutely need to interact the the cell based methods (for example to deal with formatting) then after you delete the row, you must reload the cell data.

**Comment by Betanoir** [comment]
Apologies for the delay in response, but how would I reload the cell data
correctly?

**Comment by theoephraim** [comment]
So when you call sheet.loadCells, it loads a range of cells into a cache.
Using the row-based API doesn't use or affect that cache - so if the rows have the data you need, you wouldnt even need to load the cells at all.

But if you do really need the cells, you can reload them by calling loadCells again, or potentially calling [`sheet.resetLocalCache()`](https://theoephraim.github.io/node-google-spreadsheet/#/classes/google-spreadsheet-worksheet?id=fn-resetlocalcache) which would clear out that cache completely and then call loadcells again.

**Comment by Betanoir** [comment]
So basically, after I delete a row, I should reset the cache and then load
the cells to do certain things?

**Comment by Betanoir** [comment]
I'm using the cell-based method to load the values of specific cells so I
can loop through them to see which one has, let's say, got the formula of
'= 1+1', and if it has that formula, I push it to an array.
Here is the code:
[image: image.png]

**Comment by Betanoir** [comment]
I tried using what you said to me, or at least what I understood, and
weirdly enough, it still doesn't delete the row properly and instead just
formats it...
[image: image.png]

**Comment by theoephraim** [comment]
What happens if you dont call any cell-based methods, just load rows, and then delete one?

**Comment by Betanoir** [comment]
It still didn't delete the row entirely, here is the updated code.
[image: image.png]

**Comment by theoephraim** [comment]
Not sure why, but your images aren't coming through :(

**Comment by Betanoir** [comment]
That's weird-
Here's links for them:

1st: https://i.imgur.com/Ssaw29V.png
2nd: https://i.imgur.com/Csin2QC.png
3rd: https://i.imgur.com/ft9CQ0h.png

**Comment by theoephraim** [comment]
Generally just one tip - if you set the first row in your sheet with meaningful headers ("userid", "username", "reason", "staff"), then when youre reading rows you get properties with those names (ex: `row.userid`)

To be honest, I'm really not sure what is going on. I just wrote a simple example to load rows and delete one and I do see it being removed completely. Are you sure there aren't some concurrent requests happening at the same time?

Also I'm not sure why youre calling loadInfo right before the delete - although it shouldn't affect anything.

**Comment by Betanoir** [comment]
That's interesting as mine doesn't-
I am 100% sure that there aren't concurrent requests occurring at the same
time.

I will try something tomorrow to see if it does, by chance, work then,
although I highly doubt it will with my luck :(

Also, I added that as after loading the cells and getting what I required
from them and resetting the cache, I had to call loadInfo again after doing
that, in order to get the rows in the doc.

**Comment by Betanoir** [comment]
One thing I do feel the need to ask you is if there are multiple requests
at once, but all are to do actions of different spreadsheets, would it be
able to do this, or not? This is a requirement for me, so I am really
hoping it's a yes..

**Comment by theoephraim** [comment]
Very odd. You can see that the row delete call internally is calling `deleteRange`
- see https://github.com/theoephraim/node-google-spreadsheet/blob/master/lib/GoogleSpreadsheetRow.js#L55
- see https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/request#deleterangerequest

You could try calling that directly to the google API and see what happens.
I'm also curious what would happen if calling `deleteDimension` instead - although deleting a "range" that is a full row I'd think should should be equivalent to deleting a "dimension".

As for making concurrent requests, if they are on different sheets, no problem. If they are on the same sheets, I dont think there's anything stopping you but it could cause issues, as your local cache of the sheet data can get out of sync with the remote version.

Generally the handling of row deletion needs work, as right now I dont think the row number of the other loaded rows gets updated. Should be relatively easy to fix that though.

When working with cells it can get tricky because we can't always infer what google's reply will be. For example when updating a formula, we dont know what the value will be.

**Comment by theoephraim** [comment]
One thing - if you want to give me access to the doc (or a copy of it with any sensitive info removed) I can take a look?

share with `theozero@gmail.com`

**Comment by Betanoir** [comment]
Alright, much obliged, I'll look into calling the google API in a bit!

As for giving you access, I have given you access to a sheet called "Copy
of Initial Backend (Do not share)"

**Comment by theoephraim** [comment]
Closing for now - please reopen if you are still stuck!

**Comment by jack-glenn** [comment]
This is happening to me, I'm running .del() on a row but it just clears the values in each cell, it doesn't actually completely remove that row from the sheet...
