### ISSUE TITLE
Unable to create spreadsheet object in serverless production environment

### ISSUE THREAD

**Issue by SamDesmondKing** [theoephraim/node-google-spreadsheet#433]
Hi @theoephraim, I've been using your package to help me save data to a google sheet and just thought I'd raise something with you in case I've discovered an issue, it's possible that I've overlooked something though. 

I'm using your package in a react application, and it's working great when running locally with npm start, but does not work in a deployment environment. I'm deploying using the serverless framework's [website component](https://github.com/serverless-components/website), which essentially allows you to host SPAs on s3. 

In a nutshell, when running `const doc = new GoogleSpreadsheet('my-spreadsheet-id');` and logging the doc object it's creating, this is my result running locally:

![google-sheets-working](https://user-images.githubusercontent.com/43866616/105108345-226a6580-5b0e-11eb-9deb-fc15ac7c856d.PNG)

And this is my result after deployment:

![google-sheets-not-working](https://user-images.githubusercontent.com/43866616/105108359-27c7b000-5b0e-11eb-884c-c086da4e71d8.PNG)

Presumably the 'TypeError: g is null' you see there is from when my program tries to call useServiceAccountAuth() on a non-existent spreadsheet object. 

This is the first time I've encountered a package that behaves differently after deployment (serverless or otherwise) and was hoping you might be able to shed some light on this if possible.

Thanks in advance :)

**Comment by theoephraim** [comment]
Hard for me to know for sure without seeing more of your code, so feel free to share.

I have not used this package at all in SPAs and have not really designed it for that kind of usage, but I do believe some folks have used it that way - so it should be possible if you work out the details of compiling code meant for node to be used in the browser, which is totally possible using webpack/babel/etc - basically stubbing out calls to things that are not supported in the browser, like reading from the filesystem.

Regardless, more generally I would suggest that you do not use service account auth in a deployed SPA - as this would require you to expose those credentials to your users - or anyone who downloads your js files! You'd either want to deploy some kind of api (could be serverless functions) that actually handle the API calls to google and inject your service account credentials there - so as to hide them from the client.

If you really want to connect directly to the google API from the front-end (and you need more than read only access to  public sheets) then you'd probably want to use oauth credentials for the user who is using your front-end. In this case I'd say the more common flow would still be to have an api server and db, where you handle the oauth exchange and store the refresh token... But if you really wanted to avoid having a backend altogether, which could certainly be desirable in some cases, you could store the refresh token in localstorage/cookies and force the client to go through the oauth flow each time as a way of authenticating. In the case, still be careful not to expose your oauth client secret.

**Comment by SamDesmondKing** [comment]
Hey @theoephraim thanks for the quick response, this is all very reasonable advice. In truth, I'm trying to wire up a very quick solution with as little impact on users as possible (my original implementation was using an embedded google form, I'm essentially just trying to replace that) which is why I went with the service account auth. If I could get this working, we have a workflow file which injects the service account credentials from github secrets so as to keep it abstracted away from the user as you rightly point out, I'm only passing the sheet ID as a string here to eliminate the possibility that some configuration issue with that is causing the problem. In any case it seems like using your package in this way it outside it's intended use, I think I'll go with an s3 bucket or something to store inputs rather than a google sheet. Thanks again for getting back to me!

**Comment by theoephraim** [comment]
If I understand you correctly, that github workflow would still inject your secret creds into the compiled code sent to the client, so you may have avoided committing the creds into git (yay!) but youre still sending them to end users (boo!)

For this kind of use case (simple form handling) I'd just set up a super simple serverless function that takes in the form response and sends it off to the google sheet. Should be pretty trivial and then your SPA doesnt need to know anything about where the data is going.

Good luck!
