### ISSUE TITLE
webpack: unable to compile

### ISSUE THREAD

**Issue by rrrepos** [theoephraim/node-google-spreadsheet#436]
I am able to successfully use the library under the NodeJS environment and works very well. But I do have a use-case where I would like pure-browser access to google sheets without using gapi auth but the service-account auth like you recommend in NodeJS

However, when I try to compile using webpack, I get a series of errors staring with
```
Module not found: Error: Can't resolve 'buffer' in {path}/node_modules/buffer-equal-constant-time'
```
The source js is
```
//index.js in src
const { GoogleSpreadsheet } = require('google-spreadsheet');
```

I even tried with import
```
import GoogleSpreadsheet  from 'google-spreadsheet';
```
I am aware of the security limitations of my approach but I wonder why webpack is throwing errors. Thanks

**Comment by AbhinavRajesh** [comment]
Any updates on this @rrrepos ? I too am facing this issue when trying to use the package with React

**Comment by theoephraim** [comment]
Please try the latest version and report open a new issue if you run into problems.
