### ISSUE TITLE
doc.useServiceAccountAuth has "octect is too long" error?

### ISSUE THREAD

**Issue by ConnorVO** [theoephraim/node-google-spreadsheet#437]
Not sure what is happening but below is throwing a "ReportingError: length octect is too long at: (shallow)"

```
// Config variables
const SPREADSHEET_ID = process.env.REACT_APP_SPREADSHEET_ID;
const SHEET_ID = process.env.REACT_APP_SHEET_ID;
const CLIENT_EMAIL = process.env.REACT_APP_GOOGLE_CLIENT_EMAIL;
const PRIVATE_KEY = process.env.REACT_APP_GOOGLE_SERVICE_PRIVATE_KEY;

const doc = new GoogleSpreadsheet(SPREADSHEET_ID);

const signUp = async (email) => {
  const row = { email: email, date: new Date() };
  // try {
  await doc.useServiceAccountAuth({
    client_email: CLIENT_EMAIL,
    private_key: PRIVATE_KEY,
  });
  // loads document properties and worksheets
  await doc.loadInfo();

  const sheet = doc.sheetsById[SHEET_ID];
  const result = await sheet.addRow(row);
  console.log(result);
  // } catch (e) {
  // console.error('Error: ', e);
  // }
};

```

**Comment by theoephraim** [comment]
I'm guessing something something weird with how your env vars are being saved/loaded. Maybe some weird invisible chars in there or something? Or just the private key not quite the right format?

**Comment by ConnorVO** [comment]
@theoephraim I've tried messing around with the private key. What should be included in it? I currently have the PRIVATE_KEY as -----BEGIN PRIVATE KEY-----\nMIIEv<<<LOTS_OF_OTHER_STUFF>>>WfHs=\n-----END PRIVATE KEY-----

I've tried a bunch of different times but when I don't have it like the above I get a 'TypeError: Cannot get property '2' of null'

**Comment by ConnorVO** [comment]
Ah, it appears you are right that it is some .env problem because if I hardcode the values it works.

**Comment by FungusGaming** [comment]
You may try this solution,
In your .env file the all the value of the key put double quote "
Example : REACT_APP_GOOGLE_SERVICE_PRIVATE_KEY="value"
This solved my same problem
