### ISSUE TITLE
GoogleSpreadsheetWorksheet.loadCells() really slow!

### ISSUE THREAD

**Issue by LuisDev99** [theoephraim/node-google-spreadsheet#439]
I'm currently working on reading data from a spreadsheet but when I try to load 108 rows, each with 43 columns, it takes alot of time to load the cells into the application.

```ts
async readSpreadsheetData() {
  await this.authenticateGoogleSpreadsheet();
  await this.googleSpreadsheet.loadInfo(); 

  const sheet = this.googleSpreadsheet.sheetsByIndex[MAIN_SPREADSHEET_INDEX]; 

  console.time('loadCells benchmark');

  // For some reason, loadCells is too SLOW
  await sheet.loadCells({
    startRowIndex: 1,
    startColumnIndex: 0,
    endRowIndex: 108,
    endColumnIndex: 43,
  });

  console.timeEnd('loadCells benchmark'); // Logs 8.5+ seconds on average
}
```

Time results:

![image](https://user-images.githubusercontent.com/30758539/106563347-4310c300-64f1-11eb-9b22-bf09407e01d2.png)

As you can see, I'm just calling loadCells but it is taking a bit of time to load the cells (above 8 seconds on average).

Is there a way to make loadCells faster? Am I doing something wrong, or is this how it is supposed to be?

I really need to load all the cells. I know that the docs says that if speed is crucial, I better go off and use the googleapi but speed isn't crucial here and I *think* there might be a quick workaround on this simple loadCell use case (hopefully).  Maybe just by checking the amount of rows and doing a batchGet if passed a certain limit?

Anyways, thank you for this beautiful library! I would be happy to help on this.

**Comment by kintut4** [comment]
hey at least you get something... i just cant get around the fucking undefined...

**Comment by LuisDev99** [comment]
Maybe I can help you. Do you still have the error?

If you do, did you set the environment variables?

**Comment by theoephraim** [comment]
I dont think theres much that can be done for this, since the loadCells call is just calling google's API.
