### ISSUE TITLE
set defaultFormat

### ISSUE THREAD

**Issue by macasas** [theoephraim/node-google-spreadsheet#440]
I would like to set verticalAlignment and wrapStrategy

defaultFormat is in GoogleSpreadsheet

```
GoogleSpreadsheet.defaultFormat = {
   verticalAlignment: 'TOP',
   wrapStrategy: 'WRAP'
};
```

Says not to try and set directly, fair enough,but

```
GoogleSpreadsheet.updateProperties({ 
     defaultFormat: {
          verticalAlignment: 'TOP',
          wrapStrategy: 'WRAP'
     }
});
```
does nothing, doesn't complain, but doesn't set anything either.

As you can see, I'm trying to set verticalAlignment and wrapStrategy, and so I have drilled down to the cell in an attempt to set these, but nothing is making the change. Even setting cell backgroundColor does not do anything.

Is this broken, can this module actually make these changes?  If so, how?

**Comment by theoephraim** [comment]
I just tried this as well, and it seems defaultFormat is read-only - see Google's docs https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets#SpreadsheetProperties
