### ISSUE TITLE
Unable to use with Pivot tables (when the header is on the second row)

### ISSUE THREAD

**Issue by alelk** [theoephraim/node-google-spreadsheet#442]
![image](https://user-images.githubusercontent.com/8504448/107960007-24accc00-6fb5-11eb-82ac-2587e5c6a26c.png)

It's impossible to delete the first row in Google pivot table and we can't configure `node-google-spreadsheet` to use another row as header.

**Comment by theoephraim** [comment]
pushing up custom header row functionality shortly
