### ISSUE TITLE
tags / releases are missing on Github

### ISSUE THREAD

**Issue by booya2nd** [theoephraim/node-google-spreadsheet#443]
Hey guys,

it is super strange to have no tags/releases in git(hub) at all whereas this project seems to be versioned fine for npm  🤯 
How do you guys track the changes between versions?

Maybe you have all the tags locally already as the `npm version` command would actually create those if not explicitly suppressed.
In case I would very much appreciate a `git push --follow-tags` ❤️ 

And in case you do manual bumps of the version - I highly recommend using `npm version` instead 🙃 

Thanks guys and keep up the good work.

**Comment by theoephraim** [comment]
Yeah sorry I usually just spend a couple hours every once in a while merging PRs and fixing bugs, and then manually bump the version and publish. Getting a better setup built into CI is on the to-do list.

Other than big breaking changes during v2 > v3, there hasn't been anything too major.

In the meantime, is there a specific problem that I can help with?

**Comment by theoephraim** [comment]
closing for now. Will start using `npm version` going forward.
This package was started so long ago, I dont even think `npm version` was a thing...
