### ISSUE TITLE
Module not found: Can't resolve 'child_process'

### ISSUE THREAD

**Issue by dieudonneAwa** [theoephraim/node-google-spreadsheet#448]
I am trying to save form data to a spreadsheet in Next.js but I keep getting this error which appears as soon as I import `google-spreadsheet`

Error
<img width="992" alt="Screenshot 2021-03-20 at 11 03 40" src="https://user-images.githubusercontent.com/29434750/111866186-f4699c00-896b-11eb-9f37-b3fe6f0fd456.png">

Bellow is what I have that is causing the error.

```javascript
// The error appears when I do this import
import { GoogleSpreadsheet } from "google-spreadsheet";

const SPREADSHEET_ID = process.env.NEXT_PUBLIC_SPREADSHEET_ID;
const SHEET_ID = process.env.NEXT_PUBLIC_SHEET_ID;
const CLIENT_EMAIL = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_EMAIL;
const PRIVATE_KEY = process.env.NEXT_PUBLIC_GOOGLE_SERVICE_PRIVATE_KEY;

const doc = new GoogleSpreadsheet(SPREADSHEET_ID);

const appendSpreadsheet = async (row) => {
    try {
      await doc.useServiceAccountAuth({
        client_email: CLIENT_EMAIL,
        private_key: PRIVATE_KEY,
      });
      // loads document properties and worksheets
      await doc.loadInfo();

      const sheet = doc.sheetsById[SHEET_ID];
      const result = await sheet.addRow(row);
      return result;
    } catch (e) {
      console.error("Error: ", e);
    }
  };
```

Help will be highly appreciated.

**Comment by WenderMrn** [comment]
It may not work because the google-auth-library (https://www.npmjs.com/package/google-auth-library) is for nodejs, I have same problem :|

**Comment by C-E-Rios** [comment]
Try this :) 

https://github.com/theoephraim/node-google-spreadsheet/issues/374#issuecomment-761547527

**Comment by AarooneyFarr** [comment]
It would appear that NextJS does not support running google-spreadsheet in the client. as long as you only try to run these methods server-side you should be good.

**Comment by theoephraim** [comment]
google-auth-library is now an optional peer dependency and you can pass in a raw token. Please give it a try and reopen if you run into any problems.
