### ISSUE TITLE
Way to clear entire sheet?

### ISSUE THREAD

**Issue by zachdini** [theoephraim/node-google-spreadsheet#45]
I'm working on a node app that reads data from a Mongo database and writes to a Google spreadsheet using this package. The task is going to happen every night. Is there a way to overwrite the rows that were created the previous night? It appears like new rows added using my_sheet.addRows gets added to the bottom.

I was looking into deleting the rows from the previous night but it looks like I can only delete on at a time. Is there a way to delete/clear the entire sheet? Thanks for this package! It's just what I need.

Zach

**Comment by theoephraim** [comment]
If you look in the tests, I am clearing the sheet there, but it's just using `getRows` and then [async](https://github.com/caolan/async) to call `.del()` on each row. If you had a huge sheet, you could end up hitting some limits, or it may just be too slow.

To clear the sheet in a single call, it looks like you would need to use a batch request, which is only available on cell-based feeds. More info here: https://developers.google.com/google-apps/spreadsheets/data#update_multiple_cells_with_a_batch_request

Currently, the module does not support batch requests on cell-based feeds, but I'm happy to merge in a PR!

**Comment by zakyg** [comment]
getting errors when attempting to delete all rows asynchronously with bluebird's Promise.all. As OP said, it seems that you'll have to chain and delete them one by one somehow, otherwise you'll get errors that the "row_id" you're trying to delete isn't valid.

**Comment by theoephraim** [comment]
Batch updates for cells is now supported! So you could make cells request, clear all the values, and then do a bulk update.
