### ISSUE TITLE
Get latest row with data

### ISSUE THREAD

**Issue by Porkechebure** [theoephraim/node-google-spreadsheet#450]
I need to get the latest cell in a column with data. So if I have this sheet:
   A
1 XXX 
2 YYY
3 SSS
4 (empty cell)

I need some function telling me indes of my last populated cells (not empty). In the example before it should return 3.
Based on #72 and documentation I tried:

`sheet.rowCount` -> it gets all the rows even empty ones
`sheet.getRows().count` gets populated rows, but loads all the rows. Quite inefficient

How to do it?

**Comment by Ramonivandy** [comment]
I tried this if your column has a header:

```
const rows = await sheet.getRows();
const lastColumnValue = rows[rows.length - 1].<'your header name'>; 
```

**Comment by HugoLiconV** [comment]
@Ramonivandy the problem with that approach is that first, you fetch all the data, and then you get the last item, and this could affect the performance, especially when you have a lot of rows.
I tried to use `offset` but it didn't work, I get an empty array
```javascript
  const numberOfRows = await sheet.rowCount;
  const rows = await sheet.getRows({ offset: numberOfRows - 2 }).catch((e) => {
    return res
      .status(500)
      .json({ error: "Error getting rows", message: e.message });
  });
```
In my case, I have 1000 rows but only the first 700 have data, so the offset is not really a solution, I don't know if there is any other thing or filter we could use?

**Comment by theoephraim** [comment]
as you discovered, `sheet.rowCount` is the size of the entire sheet.

If you are using the row-based methods, then you have to fetch the data before you can figure out which data is the last non-empty row. There are likely other ways to figure it out with the google API, but I'm not positive what they are.

One workaround is to use a formula somewhere else in the sheet (or another sheet) that gets the value you need (the index of the last non-empty row) and then fetch that cell.

**Comment by Porkechebure** [comment]
> as you discovered, `sheet.rowCount` is the size of the entire sheet.
> 
> If you are using the row-based methods, then you have to fetch the data before you can figure out which data is the last non-empty row. There are likely other ways to figure it out with the google API, but I'm not positive what they are.
> 
> One workaround is to use a formula somewhere else in the sheet (or another sheet) that gets the value you need (the index of the last non-empty row) and then fetch that cell.

Well, I like that one. Using a formula is a clever hack, I will try to use it.
Thanks
