### ISSUE TITLE
I try to implement cache on site to avoid quota exceeded

### ISSUE THREAD

**Issue by pszyrek** [theoephraim/node-google-spreadsheet#451]
Hi everyone!
I have a problem with quota limits in google api, i was hoping that if i will use your solution to manage google sheet i will be able to load my entire sheet once and i can use it without recalling it for new changes. Is there a way to use(offline) your package without redownloading google sheet every time when i need to get some data from it? 

I was searching for solution in yout docs but without effect, help please. : c

**Comment by theoephraim** [comment]
I'm not quite sure I follow. You can always use this module to fetch the data and then store it however you want (database, json file, redis, etc...)
