### ISSUE TITLE
addRows is adding row after several blank rows

### ISSUE THREAD

**Issue by mkloar** [theoephraim/node-google-spreadsheet#452]
I'm calling function `addRows` to insert a new row after the last row, but the problem is that row is inserted after several blank lines (always the first line after the last line of the right data ----> in the picture below: addRows will insert a row at line 77).

**Code:**
```
await doc.useServiceAccountAuth({...});
await doc.loadInfo();
const sheet = doc.sheetsByTitle["someSheetName"];
const rowToInsert = {
  "someValue": 100,
  "someValue2": 150
  ...
}

await sheet.addRows([rowToInsert]);
```

The version of the library: ^3.1.15

![image](https://user-images.githubusercontent.com/17946736/114604996-e45a8900-9c99-11eb-9cb8-b26d3652f1c6.png)

Is there any way how to solve this?

**Comment by theoephraim** [comment]
addRows is using google "append" functionality which adds rows after the first non-empty row.
Put that extra data in another sheet and you should be good to go.
