### ISSUE TITLE
row.update affects formatting

### ISSUE THREAD

**Issue by konser80** [theoephraim/node-google-spreadsheet#453]
<img width="350" alt="CleanShot 2021-04-15 at 17 23 41@2x" src="https://user-images.githubusercontent.com/43511083/114854851-746e0f00-9e0f-11eb-9221-16263ef2058b.png">

if i change B3 (i mean rows[2].value) and then rows[2].save - then it's ok.
but if i change B4 (only value!!!)
```
rows[3].value = NEW_VALUE;
rows[3].save;
```

...then formatting of A4 is gone.

**Comment by theoephraim** [comment]
please reopen with some more info if still a problem!
