### ISSUE TITLE
TypeError: sheet.copyToSpreadSheet is not a function

### ISSUE THREAD

**Issue by ankur46** [theoephraim/node-google-spreadsheet#455]
Hello,
I really appreciate the work that you have done in this project... working with google spreadsheets and with much less code is really commendable.

But  actually, I was trying to use the **copyToSpreadSheet** function of the sheet to copy the data of the already created sheet into a new sheet 
link to func - https://theoephraim.github.io/node-google-spreadsheet/#/classes/google-spreadsheet-worksheet?id=fn-copytospreadsheet

But I was facing the below error while hitting this function 
-----------------------
`(node:21979) UnhandledPromiseRejectionWarning: Error: Request faild with error: TypeError: sheet.copyToSpreadSheet is not a function
    at /Users/adeshwal/Documents/local/dei_targeting/app.js:1006:15
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:21979) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:21979) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
------------------------------------------

**I am using the "google-spreadsheet": "^3.1.15" version in my node project.**

and my function which I have written is mentioned below
---------------------
**const creds = require('./client_secret.json');
    const doc = new GoogleSpreadsheet('worksheet-Id');
    await doc.useServiceAccountAuth(creds);
    await doc.useServiceAccountAuth({
        client_email: creds.client_email,
        private_key: creds.private_key,
    });
    await doc.useServiceAccountAuth(creds, '<email-id>');
    await doc.loadInfo();
    const sheet = doc.sheetsByIndex[0];
    const newSheet = await sheet.copyToSpreadSheet('worksheet-Id');
    console.log(newSheet);**
    ------------------------------------

Please let me know what I am doing wrong as currently I am blocked because of this...

Quick help will be really appreciated.

Thank you

**Comment by theoephraim** [comment]
Looks like youre calling `copyToSpreadSheet` when it should be `copyToSpreadsheet`
https://github.com/theoephraim/node-google-spreadsheet/blob/master/lib/GoogleSpreadsheetWorksheet.js#L817
https://theoephraim.github.io/node-google-spreadsheet/#/classes/google-spreadsheet-worksheet?id=fn-copytospreadsheet

**Comment by spassvogel** [comment]
Yeah.. the types in `@types/google-spreadsheet` are wrong and/or outdated..
