### ISSUE TITLE
Insert row at the top?

### ISSUE THREAD

**Issue by lilsweetkara** [theoephraim/node-google-spreadsheet#456]
Hello there,

I am using addRow() successfully. Quick question... is ti possible for me to add a row at the TOP? That would mean shift everything down and add the new row at the very top of the spreadsheet.

If your API doesn't, do you know if this is possible with the "original" API?

Thank you!!!

Kara

**Comment by lilsweetkara** [comment]
Oh dear... did I ask as stupid question?

**Comment by NitoBa** [comment]
I'm want to do this too  Someone to knows how to do this?

**Comment by DanielBailey-web** [comment]
@NitoBa @lilsweetkara see issue #366 and then waiting on #428 to be checked and merged...

**Comment by manishgkasera** [comment]
any update on this? looking to insert the row at top desperately.

**Comment by theoephraim** [comment]
I have now added insertDimension functionality in the latest release - see https://theoephraim.github.io/node-google-spreadsheet/#/classes/google-spreadsheet-worksheet?id=fn-insertdimension

**Comment by pguardiario** [comment]
Can we add instructions for inserting a row at the top?
