### ISSUE TITLE
Is it possible to update formatting options of google sheet?

### ISSUE THREAD

**Issue by ramseth001** [theoephraim/node-google-spreadsheet#460]
I know this is a very far fetched question. But still, I would like to know. 

I want to do Formatting -> Text Wrapping -> Wrap through the code. Is it possible to do using this library? I looked around the code. But I couldn't find any functionalities regarding this. Thanks in advance.

**Comment by theoephraim** [comment]
you can change wrapStragey on individual cells. Applying bulk formatting on a range is doable but just not implemented yet.

**Comment by theoephraim** [comment]
closing for now. You should be able to set this on individual cells.
