### ISSUE TITLE
is there any to upload image file (png, jpg) to cell

### ISSUE THREAD

**Issue by Wolke** [theoephraim/node-google-spreadsheet#468]
because I can use google sheets website to do job, 
but I can't do this by calling any function.
thx for your reply

**Comment by theoephraim** [comment]
doesn't look to be possible using google's sheets v4 api, but rather only with google app script :(

That said, it looks like using the `=IMAGE(...)` formula might work for some use cases?
see https://support.google.com/docs/answer/3093333?hl=en
