### ISSUE TITLE
Adding a worksheet to a spreadsheet

### ISSUE THREAD

**Issue by svanderw** [theoephraim/node-google-spreadsheet#47]
I think it would be very useful to be able to add worksheets to an existing sheet.  The HTML looks to be fairly trivial according to 
https://developers.google.com/google-apps/spreadsheets/worksheets#add_a_worksheet

Does anyone else need/want this functionality?

**Comment by drorzp** [comment]
look at the pull request no 1  i have committed it but no one responded yet.
it works great for me.I am also working on a Delete worksheet

**Comment by theoephraim** [comment]
Sorry guys! Will merge ASAP! Thanks for the good work :)

**Comment by theoephraim** [comment]
Thanks again!
