### ISSUE TITLE
TypeError: sheet.getCell is not a function

### ISSUE THREAD

**Issue by Rexogamer** [theoephraim/node-google-spreadsheet#471]
Hello! I'm trying to edit a specific cell with the following code:
```js
await sheet.loadInfo(); // Load sheet's info
await sheet.loadCells("A1:E10"); // Load cells

const a1 = sheet.getCell(0, 0); // Grab the specific cell
// Update the cell's contents and formatting
a1.value = 123.456;
a1.textFormat = { bold: true };
await sheet.saveUpdatedCells(); // Save the changes
```

but upon running the code, I get this error:

`TypeError: sheet.getCell is not a function`

However, [looking at the docs](https://theoephraim.github.io/node-google-spreadsheet/#/?id=working-with-cells) it appears this code should work...?

Thanks!

**Comment by nixON232** [comment]
You need to use ` await doc.loadInfo()` not sheet
```JS 
await doc.loadInfo()
...
const sheet = doc.sheetsByIndex[0]

**Comment by Rexogamer** [comment]
I apologise if I'm confused but `sheet.loadInfo` works fine for actually getting the sheet's name, it's just cells that don't work?

**Comment by nixON232** [comment]
`const sheet = new GoogleSpreadsheet(...)` is class of doc, but sheet is class of `GoogleSpreadsheetWorksheet`

**Comment by Rexogamer** [comment]
Ahh. I've tested your fix and it appears to be working, thanks!
