### ISSUE TITLE
Column name with space - how to access its value 

### ISSUE THREAD

**Issue by satishmarathe** [theoephraim/node-google-spreadsheet#472]
I am not sure if this api supports column names with spaces ?
Example : 
![image](https://user-images.githubusercontent.com/19884075/120101714-b5856d00-c18a-11eb-8a41-ae71b7604ea7.png)
can access the value of column : **dob**
`row.dob`

However cannot access the value of column: **date of birth**
`row.date of birth`

Are column names with spaces not supported ?
Apologies if this is already stated in documentation ?

**Comment by theoephraim** [comment]
its just a regular javsacript object with the column values as keys.

so you can do `row.someKeyWithoutSpaces` or `row['some key with spaces']`
