### ISSUE TITLE
SCRIPT1028: Expected identifier, string or number

### ISSUE THREAD

**Issue by coffeebank** [theoephraim/node-google-spreadsheet#473]
I was fiddling with an old device and noticed my site wasn't loading in Microsoft Edge Legacy (EdgeHTML).

The error in the console says `SCRIPT1028: Expected identifier, string or number`, and when I click the "chunk-vendors" link, it points me to `webpack:///node_modules/google-spreadsheet/lib/GoogleSpreadsheetCell.js` as the issue:

![MS Edge Legacy, Console tab, The error above is output in the console](https://cdn.discordapp.com/attachments/818822855349239809/849244929011089428/unknown.png)
![MS Edge Legacy, Debugger tab, Error pointing to Line 193 of /lib/GoogleSpreadsheetCell.js](https://cdn.discordapp.com/attachments/818822855349239809/849241040086499358/unknown.png)

I did some digging, and it seems the issue could be a trailing comma:

> https://stackoverflow.com/questions/12675622/script1028-expected-identifier-string-or-number

```
193    const format = {
194      // have to pass the whole object or it will clear existing properties
195      ...this._rawData.userEnteredFormat,
196      ...this._draftData.userEnteredFormat, // <- The extra comma that is here
197    };
```

I do not expect this project to be compatible with an outdated browser, but on the off chance that a trailing comma is the fix that is needed, I'd like to ask if I can go ahead with a pull request to remove the extra comma on Line 196?

**Comment by theoephraim** [comment]
This package is really meant for use with nodejs (backend). That said I think some folks have gotten things to work ok in browsers, but you'll need to set things up in a way that builds/compiles all your dependencies into a format that is compatible with whatever browsers you are expecting - ie webpack + babel
