### ISSUE TITLE
Sheet name does not update internally after sheet.updateProperties

### ISSUE THREAD

**Issue by stam** [theoephraim/node-google-spreadsheet#476]
I have a sheet which I rename after copying it (to the same document) 

```
await sourceSheet.copyToSpreadsheet(this.doc.spreadsheetId);

<find copiedSheet>

    copiedSheet.updateProperties({
      index: 0,
      title: targetTabName,
    });
```

Afterwards I also refresh the document info:
```
    await this.doc.loadInfo();
```

But at this point, the internal sheet name is wrong. This is causing errors as the api calls still use the wrong internal sheet name.

To give an example:
I have a document with a sheet for every week, and I want to use sheet "Week 23" as a reference for "Week 24".

I copy Week 23, and now it is called "Kopie van Week 23". (dutch)
I want to rename that copied sheet to "Week 24" and place it at the first index so I call updateProperties.
Then I call this.doc.loadInfo, but at this point ```this.doc.sheetsByTitle``` still thinks the sheet is called "Kopie van Week 23", and every operation I do in this sheet afterwards fails, because some internal call still uses the old "Kopie van Week 23" name:

 data: `{"includeGridData":true,"dataFilters":[{"a1Range":"'Kopie van Week 23'!A1:Z100"}]}`,

**Comment by theoephraim** [comment]
@stam - I'm having trouble recreating this bug. After I call `sheet.updateProperties`, I see the sheet now has the correct title set, and `doc.sheetsByTitle` also appears to be correct. I'm not calling loadInfo again though, so maybe there is some kind of race condition happening?

Can you provide a more complete code example / reproduction?

**Comment by theoephraim** [comment]
@stam - closing this now. Please reopen with more info if you can recreate the issue!
