### ISSUE TITLE
How do I delete a complete spreadsheet?

### ISSUE THREAD

**Issue by ua834** [theoephraim/node-google-spreadsheet#478]
hi,

I'm not sure which api to use to delete a complete spreadsheet, I only noticed deleting worksheets.
Maybe I missed it.

Thanks.

**Comment by theoephraim** [comment]
Messing with documents (sharing, deleting) is part of the Drive api and not the sheets API and is therefore not supported at this time. Hopefully I'll add some basic drive functionality at some point...

**Comment by theoephraim** [comment]
this is now supported - https://theoephraim.github.io/node-google-spreadsheet/#/classes/google-spreadsheet?id=deletion
