### ISSUE TITLE
google-spreadsheet error: cannot read property of undefined

### ISSUE THREAD

**Issue by edohkodjo** [theoephraim/node-google-spreadsheet#48]
hi!
i am newer with sailsJs. And now i want to modify a google spreadsheet with nodeJs(using sailsJs). This is my code:
    
    var GoogleSpreadsheet = require("google-spreadsheet");
    var my_sheet = new GoogleSpreadsheet('<1Oaxk4rq2W6EhpE0sIP2ZLDcqeBIm-c7RB1Cb5Jyst44>');
    /*
    var creds = {
    client_email: '716006945997-26pdbtn44rnop358e6qn7i8i4ucdbonv@developer.gserviceaccount.com',
    private_key: ''
     }
    */
    var creds = require('google-generated-creds.json');

    my_sheet.useServiceAccountAuth(creds, function(err){
    // getInfo returns info about the sheet and an array or "worksheet" objects
    my_sheet.getInfo( function( err, sheet_info ){
      if(err)
        res.send(err);
        console.log( sheet_info.title + ' is loaded' );
        // use worksheet object if you want to stop using the # in your calls

        var sheet1 = sheet_info.worksheets[0];
        sheet1.getRows( function( err, rows ){
            rows[0].colname = 'new val';
            rows[0].save(); //async and takes a callback
            rows[0].del();  //async and takes a callback
        });
     });

     // column names are set by google and are based
     // on the header row (first row) of your sheet
    my_sheet.addRow( 2, { colname: 'col value'} );

    my_sheet.getRows( 2, {
        start: 100,          // start index
        num: 100,              // number of rows to pull
        orderby: 'name'  // column to order results by
     }, function(err, row_data){
        // do something...
      });
      })

But i have this error: Cannot read property 'title' of undefined. Please, is there anyone who can help me to fix my problem? Thanks in advance

**Comment by edohkodjo** [comment]
i saw my error. That is due to way i used the spreadsheet key. 
    var my_sheet = new GoogleSpreadsheet('1Oaxk4rq2W6EhpE0sIP2ZLDcqeBIm-c7RB1Cb5Jyst44');
rather than
    var my_sheet = new GoogleSpreadsheet('<1Oaxk4rq2W6EhpE0sIP2ZLDcqeBIm-c7RB1Cb5Jyst44>');

**Comment by edohkodjo** [comment]
So i fixed my problem

**Comment by theoephraim** [comment]
oh good! sorry i didnt catch it and get back to you.

**Comment by edohkodjo** [comment]
it's not a problem. Can you please help me for this: i want to add new row to a spreadsheet but a row that contain anything. In fact i have already a spreadsheet that is filled but i want to add content to i want to shift some row and add row between two row that are already filled in order to avoid to overwrite my row. Can you help me please on this?

**Comment by jtarre** [comment]
Hi @theoephraim, reposting my question here because it makes more sense to put with this issue. I'm having difficulty starting up your basic example from the readme.

```javascript
 var GoogleSpreadsheet = require("google-spreadsheet");

// spreadsheet key is the long id in the sheets URL
var my_sheet = new GoogleSpreadsheet('1nTXIS1dEZ2__J82F3L_9_YOaHvIyKLhwYVweKvhEzaU');

// With auth -- read + write
// see below for authentication instructions
var creds = require('./node-sheets-eb6c52d15956.json');

my_sheet.useServiceAccountAuth(creds, function(err){

    // getInfo returns info about the sheet and an array or "worksheet" objects
    my_sheet.getInfo( function( err, sheet_info ){
        console.log( sheet_info + ' is loaded' );
});
})
'console.log( sheet_info + ' is loaded' );' outputs "undefined is loaded."
```
I think my Google Spreadsheet ID key may be incorrect, although all I did was copy and paste from the url.

Thanks for any advice. Love this module and love Breather!

**Comment by jtarre** [comment]
could it have to do that it's a work account and not a regular @gmail.com account?

**Comment by debanjanbasu** [comment]
I am facing the same problem here too. With both the accounts. I don't have the original json file. Is it possible to still make it work?

**Comment by theoephraim** [comment]
The example provided is using what is called a "service account" - meaning a special google account created just for accessing the sheet. I set it up the easiest way possible which is to just use the json file they give you. If you dont have the original, you should be able to generate a new one! Just follow the instructions again!

**Comment by Syedayesha** [comment]
Eventhough I am getting the same error any help how to fix this..

**Comment by omkarsk98** [comment]
@Syedayesha 
Please share the sheet with your service account. The code like @jtarre will start working.
