### ISSUE TITLE
Error Duplicate Header Detected

### ISSUE THREAD

**Issue by mado-bohsali** [theoephraim/node-google-spreadsheet#480]
Duplicate header detected: "If other, indicate where". Please make sure all non-empty headers are unique

**Comment by theoephraim** [comment]
That means what it says - two of you header cells had the same value in it, in this case `If other, indicate where`
The row-based methods us the header row as object keys, so there can be no duplicates.

**Comment by Makstorm** [comment]
is there any ways to use first column as headers?

**Comment by theoephraim** [comment]
@Makstorm do you mean instead of making everything based on rows, use columns instead? Like the first column is the headers and adding each "row" would add a column instead?

**Comment by Makstorm** [comment]
Yep, I have google sheets that use colums like you sad and i need to fetch data from it

**Comment by theoephraim** [comment]
well it's certainly possible... but would take quite a few changes to restructure things in the codebase. Can you just flip your sheet? You could also probably have a second read-only sheet that flips the data just for viewing (from rows back to columns)
