### ISSUE TITLE
No values in the header row

### ISSUE THREAD

**Issue by nullZheng** [theoephraim/node-google-spreadsheet#483]
When I try to get the rows from a google sheet  with the getRows() function, I encounter the following error:
`UnhandledPromiseRejectionWarning: Error: No values in the header row - fill the first row with header values before trying to interact with rows`
I'm not the owner of this sheet nor was I given editing access, so it's not possible for me to set any kind of header values for the sheet.
Is there any way around this?

**Comment by rizkiandrianto** [comment]
I also got that error when try to `addRows` after I clear my sheets.
Tried to `setHeaderRow` before adding rows, got another error: `TypeError: Cannot read property '0' of undefined`.

**Comment by baptisteArno** [comment]
I get the same error:

```
No values in the header row - fill the first row with header values before trying to interact with rows
    at GoogleSpreadsheetWorksheet.loadHeaderRow (/workspace/node_modules/google-spreadsheet/lib/GoogleSpreadsheetWorksheet.js:292:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by theoephraim** [comment]
if the sheet is not set up like a database (first row being header values) then you can use the cell-based methods to fetch data instead.

Otherwise if any of you are still having problems - please open up another issue with some code samples and example sheets and I can help debug.
