### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by chrisjensen** [theoephraim/node-google-spreadsheet#485]
Just wanted to say thank you for this library. It's been really useful in a number of different small scale projects where a database would be overkill and we just needed a simple interface for lay users to make updates.
I shudder to think how much harder it would've been if we had to interface with the Google API directly 😬

**Comment by theoephraim** [comment]
Thanks @chrisjensen!

This project came about (in 2013!) trying to do exactly that. Google's v3 api was SO much worse than the new v4 one so it used to be even more critical, but it's definitely still much better developer experience compared to google's libs and docs.

To be honest, these days when I need a simpler-than-a-db backend for something, I often reach for https://airtable.com, but it's still nice to to have google sheets as an option!
