### ISSUE TITLE
addRow type is not properly defined in @types/google-spreadsheet

### ISSUE THREAD

**Issue by ghost** [theoephraim/node-google-spreadsheet#488]
TS Error: Property addRow does not exist on type GoogleSpreadsheet

**Comment by theoephraim** [comment]
I have not been keeping the types up to date.

I will rewrite this whole codebase in TS at some point, which will then give us much better types without the manual work of keeping them up to date.

In the meantime, feel free to update the types!

**Comment by theoephraim** [comment]
new TS rewrite is now live. Please check it out :D
