### ISSUE TITLE
spreadsheet add new line

### ISSUE THREAD

**Issue by edohkodjo** [theoephraim/node-google-spreadsheet#49]
i want to add a new row, between two rows that have already contents.In fact i am adding content to a spreadsheet that is already filled. So i want to shift the rows and and add a new row between two rows that are already filled.  Is there anyone who can help me to do this? Thanks

**Comment by theoephraim** [comment]
Google's API doesnt give an easy way to do it. so you would basically have to read all of the sheets data and edit the rows to insert your new one. If you have tons and tons of rows, this may be a bit of a problem.

**Comment by theoephraim** [comment]
You could also consider just inserting the row normally (at the end), and using a structured query to pull the data out in the order you need it, or if the table is small enough, pulling all the data and sorting it later.

**Comment by edohkodjo** [comment]
https://docs.google.com/spreadsheets/d/1gxCqJLnUsclQW9X0F18-tzucdLKwxstCPVKWZOBa3ek/edit?usp=sharing
 i copy this file to show you a kind of what i want to do. For example i want to add content to the line 15 but this row is already filled so i want to insert a new row  and add my content in order to avoid overwriting. Can you please write a piece of code for me, because really i am a newer with coding especially with sailsJs and nodeJs. thanks in advance

**Comment by edohkodjo** [comment]
Please did you find something for me? I am on a project and really i need your help to continue with that. Today i tried to read the Google's API but i did not understand anything. Best !
