### ISSUE TITLE
addRow using API Key Auth not working

### ISSUE THREAD

**Issue by jeffpohlmeyer** [theoephraim/node-google-spreadsheet#490]
I have set up an API Key that I'm using for authentication and the process of fetching rows to display on my page is working properly with said key.  As soon as I try to run await sheet.addRow, though, I get a Google API error:
[401] Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential.

I can use the .json file that is created for a service account and this works (although trying to manually use the client_email and private_key doesn't seem to be working) but I'm trying to implement this functionality using serverless Netlify functions and this is causing a problem.

**Comment by theoephraim** [comment]
using the API key based auth only works for **read-only** usage

see https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication?id=api-key

There should be a way to get the service account auth working in netlify functions - youll just need to set the email and key in env vars through netlify's UI. There may be some slight trial and error to get things working, depending on how netlify treats some characters in their env vars, which I can't remember off the top of my head. Something like this:
```
await doc.useServiceAccountAuth({
  client_email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
  private_key: process.env.GOOGLE_PRIVATE_KEY.replace(/\\n/g, "\n"),
});
```
