### ISSUE TITLE
is there a way to color an entire row

### ISSUE THREAD

**Issue by aster2709** [theoephraim/node-google-spreadsheet#493]
we can color cell, but can we color entire row?

**Comment by theoephraim** [comment]
Looks to be doable with either of these update types:
- https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/request#repeatcellrequest
- https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/request#copypasterequest

but neither of these are supported yet

For now, you can just load the full range of cells, update each cell, and then save.

**Comment by theoephraim** [comment]
merged into #629
