### ISSUE TITLE
Google API error - [403] The request is missing a valid API key.

### ISSUE THREAD

**Issue by yamnyk** [theoephraim/node-google-spreadsheet#497]
Having such an error every time I try to use `doc.loadInfo()` or any other API method.

My code is fully copied from the documentation. 
```
      const doc = new GoogleSpreadsheet('MY-SHEETS-ID')
      await doc.useServiceAccountAuth(creds) //this works fine, creds variable contains all the info
      await doc.loadInfo(creds) //error happens here
```

Doc's instructions are fully completed.
1 - created project
2 - sheets API is enabled for the project, also enable domain-wide access
3 - shared my sheets with an email from the service account
4 - created JSON key
5 - downloaded JSON key
6 - code from docs 

And it works wrong every time. 

Authentication with the OAuth key works in the same way. I'm still getting the same error with such a response.
```
{
 error: {
     code: 403, 
     message: "The request is missing a valid API key.", 
     status: "PERMISSION_DENIED"
     }
}
```

**Comment by htadashi** [comment]
I had the same problem. I think this is a CORS issue (not a node-google-spreadsheet problem)

**Comment by theoephraim** [comment]
Also you have to remember to share the doc in question with the service account you've created.

Closing this for now...
