### ISSUE TITLE
No Issue, but a feature request

### ISSUE THREAD

**Issue by invalidcpp** [theoephraim/node-google-spreadsheet#498]
I'm not sure if this is already a feature, or if you're looking to implement it in the future.
It would be really good, if you were able to edit sheet permissions. Hide sheets, protect it, etc.

Other than that, this is a beautiful module, easy to use. Good job!

**Comment by theoephraim** [comment]
see https://github.com/theoephraim/node-google-spreadsheet/issues/432

It's definitely on my radar, but it would require hitting a totally different google API (drive) - so it's not necessarily a simple thing to add.
