### ISSUE TITLE
getrows() fails when there is an empty row in between 

### ISSUE THREAD

**Issue by sanjivkrish** [theoephraim/node-google-spreadsheet#50]
getRows() function returns the array of rows in the spreadsheet. But if there is an empty row in the spreadsheet (for example, take 3rd row as an empty one). then the rows present below (i.e., from 4th row) are not returned by getRows() function.

**Comment by theoephraim** [comment]
This unfortunately is part of Google's API when using row-based feeds.

In the past, I've made this work by putting a single `-` character in the first column of the "empty" row and detecting it in my code.

I think I used to mention it in the docs, but it must have gotten lost in the documentation rewrite. Thanks for the heads up.
