### ISSUE TITLE
For Docs - Service Account Auth - Heroku

### ISSUE THREAD

**Issue by 0xRyN** [theoephraim/node-google-spreadsheet#504]
Just wanted to note that if you have connected your project to Github (no Heroku CLI), you can use heroku config variables BUT if so, you need to sanitize the output like so :
```js
await doc.useServiceAccountAuth({
        client_email: process.env.LOG_GOOGLE_EMAIL,
        private_key: process.env.LOG_GOOGLE_PRIVATE_KEY.replace(/\\n/g, "\n"),
});
```
Would be cool to add that to documentation (I don't know how that works so I added an issue).

**Comment by theoephraim** [comment]
added to new docs, deploying shortly
