### ISSUE TITLE
Not sure if this is a bug with the module or AWS

### ISSUE THREAD

**Issue by invalidcpp** [theoephraim/node-google-spreadsheet#506]
I'm using AWS Lambda with API gateway to do some googlesheet editing. Pretty simple stuff, but when useServiceAccountAuth is run, any code after doesn't get executed. The lambda finishes, no error messages. I thought maybe I'm just not handling the error messages or something. So I did:
```
console.log("Before Authentication")
doc.useServiceAccountAuth(credentials)
.then(() => { console.log("Authenticated") })
.catch((err) => { console.log(`Failed to Authenticate\n${err}`) })
console.log("After Authentication")
```
Only "Before Authentication" Is logged. Nothing else is logged. I'm really confused by this weird behaviour. So I was hoping someone had a similar issue that they fixed, or if it is a bug, the dev's could be informed.

**Comment by theoephraim** [comment]
Did you try wrapping that whole thing in a try catch to see if there are any other errors?

**Comment by theoephraim** [comment]
gonna close this out for now. Please reopen with more details if you're still having issues.
