### ISSUE TITLE
Why Obfuscate Your Documentation?

### ISSUE THREAD

**Issue by machineghost** [theoephraim/node-google-spreadsheet#507]
This:

```
await doc.useServiceAccountAuth({
  client_email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
  private_key: process.env.GOOGLE_PRIVATE_KEY,
});
```

is just cruel.  It's like writing documentation like this:

    myFunction(I, BET, YOUD, LIKE, TO, KNOW, WHAT, ARGS, TO, PASS, HUH);

That is no way to document a library :(  If I'm going to use `myFunction`, I need to know the types of its args, and documentation like:

     myFunction(5, true, { day: 'Tuesday' })

tells me how to do that.  But when you just say `process.env.GOOGLE_PRIVATE_KEY`, are you talking about the key itself, the ID of the key, the path to the key file, the name of the key file ... I have no clue.

Please, just say what args your functions expect, don't be coy and not document your code just because devs should be using ENV variables.

**Comment by GirkovArpa** [comment]
When I created my credentials, Google had me download a JSON file containing `client_email` and `private_key` properties.  I just loaded the JSON file (e.g. `const credentials = require('./credentials.json')` and then:

```javascript
await doc.useServiceAccountAuth(credentials);
```

**Comment by theoephraim** [comment]
If you follow [the instructions](https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication?id=service-account) and download a credential file from google, it should be pretty clear.

Or better yet, you can even try [reading the docs](https://theoephraim.github.io/node-google-spreadsheet/#/classes/google-spreadsheet?id=fn-useserviceaccountauth) which clearly document the types of the args it is expecting.

When I get around to rewriting this all in typescript, we'll get some types and nice hinting, but for now, I think the extensive documentation usually does the trick for most people.

**Comment by machineghost** [comment]
>it should be pretty clear

I mean, do you really want your documentation standard to be "what seems clear to me, the author"?

Why would it be so terrible to just add a single sentence saying something like:

> Pass the entire credentials object provided by Google (ie. the object with `GOOGLE_SERVICE_ACCOUNT_EMAIL` and `GOOGLE_PRIVATE_KEY` keys) to doc.useServiceAccountAuth

**Comment by theoephraim** [comment]
I'm all for making things more clear.

There are already explanations to that effect in the the [Authentication guide](https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication?id=service-account) and in the [`useServiceAccount` function docs](https://theoephraim.github.io/node-google-spreadsheet/#/classes/google-spreadsheet?id=fn-useserviceaccountauth)

Is it just in the inline comments on ["The Basics" in the readme](https://github.com/theoephraim/node-google-spreadsheet#the-basics) that you feel it is missing?

**Comment by machineghost** [comment]
Yes; just a single sentence would be all it takes to make it clear that the two environmental variables should be coming directly as two keys from the Google-provided `'./config/myapp-1dd646d7c2af.json' (or similar) file.  Without them, it's like "here's these two environmental vars: you figure out exactly where they come from".

I applaud the great documentation on this project, but rather than sending people looking for this detail in two (obscure ... at least compared to "The Basics") pages, it seems like a one sentence addition to The Basics would save effort and add clarity.
