### ISSUE TITLE
Insert Datetime value with timezone

### ISSUE THREAD

**Issue by baptisteArno** [theoephraim/node-google-spreadsheet#508]
I have several users from different time zones.

Currently, my server script is sending: `date.toUTCString()` to the spreadsheet but it will add a cell with the timezone of my server.

Is there a way to directly send the Date so that it will be formatted with the spreadsheet viewer timezone?

**Comment by theoephraim** [comment]
I'm really not sure, but I don't think google sheets has great support for this. If you can figure out how to handle this in the raw google sheets api, then I'm sure we can add support if something is missing on this end.

**Comment by theoephraim** [comment]
combining into #630
