### ISSUE TITLE
axios@0.21.1: Security Vulnerability

### ISSUE THREAD

**Issue by willguitaradmfar** [theoephraim/node-google-spreadsheet#513]
# Bug Report
latest 3.1.* of google-spreadsheet depends on axios@0.21.1 which has a known CVSS with score 7.5: https://snyk.io/vuln/SNYK-JS-AXIOS-1579269

Can we get another 3.1.* release fixing this?

**Comment by theoephraim** [comment]
bumping in next release shortly
