### ISSUE TITLE
Possible security issue?

### ISSUE THREAD

**Issue by swarad07** [theoephraim/node-google-spreadsheet#515]
Is it normal that the keys and tokens are visible under the GoogleSpreadSheetRow object that you get from the response?

What is the way to avoid these details in response.

We can see this in `[_sheet][_spreadsheet][jwtClient]`

![Screenshot 2021-10-14 at 8 20 49 PM](https://user-images.githubusercontent.com/421882/137342980-d046179f-5fe6-4db8-9afd-5c354a6e712c.png)

```
export const getGoogleDoc = async (sheetTitle, savedTournament) => {
  // Initialize the sheet - doc ID is the long id in the sheets URL
  const sheetId = getTournamentSheet(savedTournament);
  const doc = new GoogleSpreadsheet(sheetId);
  await doc.useServiceAccountAuth({
    private_key: process.env.APP_KEY.replace(/\\n/g, '\n'),
    client_email: process.env.APP_EMAIL,
  });

  // loads document properties and worksheets.
  await doc.loadInfo();
  // Load sheet.
  const resultsSheet = doc.sheetsByTitle[sheetTitle];
  const rows = await resultsSheet.getRows();
  console.log(rows);
  return rows;
};
```

**Comment by theoephraim** [comment]
This library was really designed to be used in the backend, where this doesn't matter.

While it _might_ work in the front-end, anything being exposed you'd need to have available already in which case it is already being exposed.

Let me know if I'm missing something, or maybe describe your use case a bit more and I can try to help.
