### ISSUE TITLE
Error: Google API error - [404] Requested entity was not found.

### ISSUE THREAD

**Issue by eduoliveira85** [theoephraim/node-google-spreadsheet#522]
I'm deploying a project @ Vercel using Next.js to read this sheets pages and load tables with contents. 
It works locally, where I've dealt with all values using env variables (spreadsheets IDs, service account email and private key), but not remotely with the same env vars set.

It returns this message in the log:
```
16:41:38.033 | Error: Google API error - [404] Requested entity was not found.
-- | --
16:41:38.033 | at createError (/vercel/path0/node_modules/google-spreadsheet/node_modules/axios/lib/core/createError.js:16:15)
16:41:38.033 | at settle (/vercel/path0/node_modules/google-spreadsheet/node_modules/axios/lib/core/settle.js:17:12)
16:41:38.034 | at IncomingMessage.handleStreamEnd  (/vercel/path0/node_modules/google-spreadsheet/node_modules/axios/lib/adapters/http.js:269:11)
16:41:38.034 | at IncomingMessage.emit (events.js:412:35)
16:41:38.034 | at endReadableNT (internal/streams/readable.js:1334:12)
16:41:38.034 | at processTicksAndRejections (internal/process/task_queues.js:82:21) {

```
My IDs are ok. Do I need a secondary private key to run it remotely?

**Comment by theoephraim** [comment]
Are you sure your IDs are ok? Can you recreate the same error locally by messing up the doc id?

**Comment by eduoliveira85** [comment]
Taking your suggestion @theoephraim I've messed up the ids in the .env file and then the page wouldn't load the tables locally, same way it would happen remotely. So I dropped the env vars method and hard coded the IDs within my api files. It worked locally but once again, it didn't worked remotely. Same error. 

I believe it's something else. I've just checked the logs for previous deploy and the IDs are being loaded properly.

**Comment by eduoliveira85** [comment]
I've found the error. It was indeed a problem with the ID. That test that I've described in my previous comment was wrongly done, because I've made an modification to my custom api and the content fetching was coming from another file. Did not saw that.

Hard coded the ID again and now it works properly. Thanks for your suggestion @theoephraim

**Comment by theoephraim** [comment]
No worries! Happy to have helped. Depends on what youre building for if it's a real problem or not, but I wouldn't recommend checking your creds into git if you can figure out how to avoid it.

**Comment by hasnainCN** [comment]
getting  the same issue although i have added the keys correctly.
