### ISSUE TITLE
Unknown name "headerValues" at 'requests[0].update_sheet_properties.properties'

### ISSUE THREAD

**Issue by kbariotis** [theoephraim/node-google-spreadsheet#523]
However I tried to add header values to a sheet, I get this error.

```
{
  code: 400,
  message: `Invalid JSON payload received. Unknown name "headerValues" at 'requests[0].update_sheet_properties.properties': Cannot find field.`,
  status: 'INVALID_ARGUMENT',
  details: [
    {
      '@type': 'type.googleapis.com/google.rpc.BadRequest',
      fieldViolations: [Array]
    }
  ]
}
```

I searched around and found this [issue](https://github.com/theoephraim/node-google-spreadsheet/issues/300) which seems to be resolved but even with the latest version (3.2.0) I get the same.

Thank you :)

**Comment by theoephraim** [comment]
Can you please post a code sample of what you are doing to trigger this error?

**Comment by theoephraim** [comment]
please try the latest version and re-open with more details if still having issues.
