### ISSUE TITLE
Is it possible to freeze the header row?

### ISSUE THREAD

**Issue by CodeForcer** [theoephraim/node-google-spreadsheet#528]
This is a very common user need for spreadsheets, would be awesome if this library could support it!

**Comment by theoephraim** [comment]
Looks like you can do this via
`sheet.updateGridProperties({ frozenRowCount: 1 });`

which is internally just calling `sheet.updateProperties({ gridProperties: ... })`

**Comment by Strajk** [comment]
If you are getting `can't delete all the rows on the sheet.` or `can't freeze all visible rows on the sheet.`

```js
await sheet.updateGridProperties({
  frozenRowCount: 1, // to avoid "can't delete all the rows on the sheet.", we have to set also rowCount and columnCount
  rowCount: 2, // header row + placeholder row -> to avoid "You can't freeze all visible rows on the sheet."
  columnCount: COLUMNS.length,
})
```
