### ISSUE TITLE
Entity not found error

### ISSUE THREAD

**Issue by scepterus** [theoephraim/node-google-spreadsheet#529]
Hey, I've been tasked with updating an old code that used the previous version of this software, and I've found a video on YouTube that got me 90% there, except I get the entity not found error. I tried getting the credentials directly from the JSON of the service account, and I tried setting them up in a .env file as well. Both yield the same result.

There's no “official” guide for creating the service account, so that might be where the problem lies, also the video said to use the Google Drive API instead of the Google sheets API, it made no difference.

I also tried replacing the \n with line breaks. Am I missing something obvious here?

Thanks for the help!

**Comment by theoephraim** [comment]
Did you try following the instructions [here](https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication?id=service-account)?

You have to make sure the library is getting the right creds, and you also have to make sure you have shared the doc with teh service account.

**Comment by scepterus** [comment]
Hey and thanks for replying, I ended up solving this as it was a wrong syntax if I remember correctly, something to do with the credentials being in quotation marks. We can close this issue, but a list of possible errors and their causes would have been helpful.
