### ISSUE TITLE
Load content of the sheet as JSON

### ISSUE THREAD

**Issue by HuyAms** [theoephraim/node-google-spreadsheet#540]
Hi, 

How could I load the content of a specific sheet as JSON data? 

```
 const doc = new GoogleSpreadsheet(xxx);

    await doc.useServiceAccountAuth({
        client_email:,
        private_key: 
    });

    await doc.loadInfo()
   // how to get the content
 
```

Many Thanks

**Comment by theoephraim** [comment]
What do you mean load as json? What would you expect the format to be?

If you want something simple, I suggest using the row-based methods to fetch an array of row objects that use the header row as object keys. Then you can serialize to json as you like.
