### ISSUE TITLE
No values in the header row & Duplicate header detected

### ISSUE THREAD

**Issue by Marcuzzz** [theoephraim/node-google-spreadsheet#544]
I'm trying to read some sheets but I'm getting some errors:

```
const doc = new GoogleSpreadsheet('id-of-sheet');
doc.useOAuth2Client(oauthClient);
await doc.loadInfo();

for (const sheet of doc.sheetsByIndex) {    
    const allrows = await sheet.getRows();
    console.log(Object.keys(allrows[0]));
}

```

But I get some errors on:
await sheet.getRows();

The errors are self-explanatory but not sure what to do about them. 
I don't want to change the sheets...
Is there another way to get the contents of the sheet?

```
Javascript: Error: No values in the header row - fill the first row with header values before trying to interact with rows
Javascript: Error: Duplicate header detected: "options overrides". Please make sure all non-empty headers are unique
```

**Comment by theoephraim** [comment]
you can use the cell based methods and just read the cells directly.

The row based methods try to simplify and treat the sheet like a very simple db, which means it needs unique headers to use as column names.
