### ISSUE TITLE
Is there a way to fetch a row based on its data, like if there are 5 rows with a unique id in each row , can i find the row based on that unique id

### ISSUE THREAD

**Issue by amrit-2006** [theoephraim/node-google-spreadsheet#545]

**Comment by theoephraim** [comment]
unfortunately, google removed their row-based api in their last major update. This module tries to recreate it as much as possible, but fetching filtered rows isn't possible :(

The one workaround I can suggest is to use formulas on a second sheet. So lets say you have one sheet of rows set up like a database. On a second sheet, use a formula to find the thing you want - for example, the row based on some condition, or just the row number, etc... You can either update the formula itself, and read the result, or you could have the formula take inputs from other cells and update those cells. It's a bit clunky but it can definitely work in some scenarios.
