### ISSUE TITLE
Edit an existing row by sending the row number

### ISSUE THREAD

**Issue by JoakoV3** [theoephraim/node-google-spreadsheet#550]
I have been searching about editing fields of an existing row by sending the row number. I know this can be done with cells by sending the specific cell but is there a way to send an array or object to edit a row completely? 

Apprecciate your help. Thanks in advance.

**Comment by theoephraim** [comment]
This module is not really set up for that at the moment, but you might be able to do something hacky
- load a single row
- clone it
- change the `_rowNumber` property to the row in question (A1 style row, ie first row is 1, not 0)
- update the values, call save
