### ISSUE TITLE
Suddenly Getting 403 Errors ... on a Public Spreadsheet

### ISSUE THREAD

**Issue by machineghost** [theoephraim/node-google-spreadsheet#562]
I have a publicly shared spreadsheet (I can open it up in Incognito Mode just fine).  I have a script, written with google-spreadsheet, which updates that spreadsheet.  It used to work great.

Now however when I try to use the library I get 403 errors:

```
Error: Google API error - [403] The caller does not have permission
    at createError (/home/me/project/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/me/project/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/me/project/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

... which makes no sense, because again the spreadsheet is public: no one should get a 403 when accessing it.  Plus, I *am* giving access to the script when I access the sheet:

    const doc = new GoogleSpreadsheet(spreadsheetUrl);
    const credentials = JSON.parse(await readFile(CREDENTIALS_PATH, 'utf8'));
    await doc.useServiceAccountAuth(credentials);
    await doc.loadInfo(); // loads document properties and worksheets

(where CREDENTIALS_PATH is a working path to a credentials JSON file from Google).

Is there any possibility this library could be reporting false 403 errors, because again it shouldn't even possible to get legitimate ones on a public spreadsheet.

**Comment by theoephraim** [comment]
It's definitely just returning the message from the actual error returned from google, so must be some other issue.

I think it may just be how google's api works - even if the sheet is public, I'd try explicitly giving access to the service account email.

**Comment by machineghost** [comment]
Thanks, but despite being public *and* despite me adding the service account's email address in Sharing, that address doesn't show up on the list, and I get: 

    {
      code: 403,
      message: 'The caller does not have permission',
      status: 'PERMISSION_DENIED'
    }

So I really thought the library might be responsible.

**Comment by Productivix** [comment]
Hi, 
I made tests today with this very clear lib, thanks to Theo, and I have only access in reading (no adding, update) on a full shared GGsheet.

**Comment by theoephraim** [comment]
Hmm I'm not quite sure what to tell you. My tests are passing which involve writing to a sheet.

Perhaps if you make a copy of the sheet and share it with me (theozero@gmail.com) I can try to poke around and see what's going on?

I would also try running through the service account setup instructions again to create a new service account and see if that resolves it. Also make sure you enable to google sheets API for your project / api key.

**Comment by Productivix** [comment]
Hi Theo, nice concrete proposal, thanks.
I beg your pardon ,your program works well : I made a mistake in my sheet sharing "full shared" I had selected : reading only . I made a test with "editor" and it works well as you documented (https://theoephraim.github.io/node-google-spreadsheet/#/?id=the-basics)
I have another request, it is not described, so not an issue, I will do it per email and post if necessary then.

**Comment by machineghost** [comment]
Actually Productivix, thanks, I think I might be making the same mistake.  Trying to confirm; will report back!

**Comment by theoephraim** [comment]
closing for now. If you track down the error to something specific, reopen with more details.

Cheers
