### ISSUE TITLE
Please add query option for update and delete

### ISSUE THREAD

**Issue by subhra9326** [theoephraim/node-google-spreadsheet#565]
await sheet.getRows()
reading all the rows and then finding a specific row is very bulky work for the update  & delete operation. Please add some query options for that.

**Comment by theoephraim** [comment]
If you mean bulky in that it fetches everything, google's api does not provide filtering capabilities :(

**Comment by theoephraim** [comment]
The best workaround I have found is to add a formula cell in another sheet that does the lookup you need, and then use that information to do what you need.
