### ISSUE TITLE
Use the Libary without Authentication

### ISSUE THREAD

**Issue by MrTob** [theoephraim/node-google-spreadsheet#568]
is there any possibility to use the Libary without Authentication. bcause i have a published Google Shreadsheet were i dont't have access to the client emial and the private key 

Example URL
https://docs.google.com/spreadsheets/d/e/2PACX-1vQlVDW_8b4uT445iCfl64BgNX_307pZALdxm8_Oe0mgQlTmOb4C5xJPTOx3XdT7YQheLwa7g1asS7g3/pubhtml?gid=1377365356&single=true

**Comment by theoephraim** [comment]
Read the docs on google. You need at least an API key so they can identify your application. In that case you can get read-only access to public docs. Otherwise you could use Oauth and authenticate as a person (like yourself) rather than as a service account.
