### ISSUE TITLE
For large writes axios needs a larger maxBodyLength

### ISSUE THREAD

**Issue by joshsny** [theoephraim/node-google-spreadsheet#569]
When submitting a large write operation, it can sometimes exceed the maxBodyLength setting used for axios.

This results in the following error: `Error [ERR_FR_MAX_BODY_LENGTH_EXCEEDED]: Request body larger than maxBodyLength limit`.

To get around this, either calls could be batched when the writes are too large, or `maxBodyLength` could be set to `Infinity`. Which do you think is best?

**Comment by theoephraim** [comment]
I'd say the simpler the solution the better. If setting `maxBodyLength` to infinity will work, that's definitely easy. Have you tried and verified that it works? Open a PR?

**Comment by renanwilliam** [comment]
Maybe expose axios properties in constructor or some other method?

**Comment by theoephraim** [comment]
this is now fixed.
