### ISSUE TITLE
getRows returns 0

### ISSUE THREAD

**Issue by bradders591** [theoephraim/node-google-spreadsheet#57]
Hi,

Had a look through previous issues and no one seems to be having this issue. getInfo works fine, but no combination of getRows returns anything other than "0" rows. I've looked through the code and console.logged the 'xml' variable that it looks for "entry" in and i get nothing like that in the response.

Any ideas?

thanks

**Comment by theoephraim** [comment]
Post your code and I can try to help :)

**Comment by bradders591** [comment]
my_sheet.useServiceAccountAuth(creds, function(err){
        
        my_sheet.getInfo( function( err, sheet_info ){
        
            console.log( sheet_info.title + ' is loaded' );
            var numberOfSheets = sheet_info.worksheets.length;
            console.log('numberOfSheets: ' + numberOfSheets);
        
            var sheet1 = sheet_info.worksheets[0];  

            console.log(sheet1);
        
            my_sheet.getRows( 1, function(err, row_data){
                console.log(row_data);
            });
        });
    });


getInfo returns everything i'd expect. getRows consistently returns nothing. I've tried with and without options and doing it on the whole sheet and specific worksheets within the overall spreadsheet.

**Comment by theoephraim** [comment]
Hmm things look mostly ok to me.
I would suggest adding `if (err) console.log(err);` as the first line of each function to help catch problems.

Does your sheet have data in the first row? This is the "header row" and these values are used as the keys for the data in those columns.

Does your sheet have any empty rows? Google's row API is limited in that if it sees an empty row it assumes the data stops there. Even if you have a row that is being used as empty space, make sure you put at least something in one of the columns. You can filter that row out in your application code.

**Comment by bradders591** [comment]
I did put them in but removed them to minimise what you had to read through. The 1st cell of the first row is empty, I'll remove the empty rows as well and see what i get. Thanks for your help so far

**Comment by bradders591** [comment]
Well i restructured things so the first cell wasn't blank and it now works! Thanks!

**Comment by theoephraim** [comment]
Glad I could help :)
You may notice google mangles the column names a bit, so I usually try to use all lower case letters so nothing is unexpected.

And remember the gotcha about blank rows in the middle of the sheet.
