### ISSUE TITLE
Better release workflow

### ISSUE THREAD

**Issue by EndBug** [theoephraim/node-google-spreadsheet#575]
There are currently a couple of issues with your release workflow:

- There is no changelog, neither in a file nor from releases
- There are no tags in the repo, so we can't even compare versions without having to look up the commit SHAs

This could be solved by simply creating releases on GitHub, which has an "auto-generate" feature for the changelog.  

This can be further improved by setting up a workflow to publish the package to both NPM and GPR, see this for reference: https://github.com/EndBug/overwatch-stats-api/blob/b7c29e5ac8e52c16e70342671326018a0862837d/.github/workflows/release.yml

**Comment by theoephraim** [comment]
fixed this finally!
- added a changelog,
- added tagging and releases
- backfilled the tags
- lots of tooling to make it all easy

**Comment by EndBug** [comment]
Nice! 💖
