### ISSUE TITLE
loadCells then getRows?

### ISSUE THREAD

**Issue by Frankusky** [theoephraim/node-google-spreadsheet#578]
I have an issue, lets say I have a sheet with two tables of data, for example, something like this:
![image](https://user-images.githubusercontent.com/9449735/181864593-d336f2b2-63e3-4482-bb50-b14377dabdad.png)

I just want to get A2:B3 data, so what im making is sheet.loadCells("A2:B3"), but how can I loop over each row cell? I see the only way is to use getCell or getCellByA1 manually... there is no other method that can return like an array of arrays? for example, something like
```
[
  [123, 345],
  [asd, rgt]
]
```

**Comment by theoephraim** [comment]
Sounds like you may want to use the row-based API - https://theoephraim.github.io/node-google-spreadsheet/#/classes/google-spreadsheet-worksheet?id=working-with-rows
