### ISSUE TITLE
Cannot access after creating spreadsheet by createNewSpreadsheetDocument()

### ISSUE THREAD

**Issue by bumjun-kim** [theoephraim/node-google-spreadsheet#580]
I used google-spreadsheet to create new spreadsheet.

Below is my code.
`
import { GoogleSpreadsheet } from 'google-spreadsheet';

    const doc = new GoogleSpreadsheet();

    await doc.useServiceAccountAuth({
      client_email: config.googleSheetAccount,
      private_key: config.googleApiPrivateKey,
    });

    await doc.createNewSpreadsheetDocument({ title: spreadSheetName });

    const spreadsheetId = doc.spreadsheetId;
`

so I get spreadsheetId something like  1cE2it8ZhizZWNs4~~~~~~~~~~~~~~~~~~~~~~~~~~

so I went to the link by spreadsheet Id like
https://docs.google.com/spreadsheets/d/1cE2it8ZhizZWNs4~~~~~~~~~~~~~~~~~~~~

but when I visit the link, it requires authority to access the spreadsheet.

Is there any way to create spreadsheet with public access ?

**Comment by LEGENDARY-KING** [comment]
bump, is there any info on this?

**Comment by theoephraim** [comment]
more info here - https://theoephraim.github.io/node-google-spreadsheet/#/classes/google-spreadsheet?id=creating-a-new-document
and here - https://theoephraim.github.io/node-google-spreadsheet/#/classes/google-spreadsheet?id=sharing-permissions
