### ISSUE TITLE
Deleting a row leads to error 500, internel error.

### ISSUE THREAD

**Issue by NewCoderOnTheBlock** [theoephraim/node-google-spreadsheet#582]
Hello everyone. I am trying to deleting a row with google sheet. Here's the following code:

```ts
let rows: GoogleSpreadsheetRow = getSomeRows()
let row = rows.filter(...)
await row.delete()
```

The code is very simple I would like to find a specific row & delete it with the help of .delete() but I receive this error.
So I already find a solution it is simply to delete the row in the google sheet via the browser & Add new rows  & boom now my library .delete() works. I can delete these new rows but i would like to understand what cause this problem, they are still rows I cannot delete them yet now but i need to delete them later.

I am receiving is this following error:

 

> var error = new Error(message);           ^
> Error: Google API error - [500] Internal error encountered.
>     at createError (C:\Users\USER\OneDrive\Documents\Projet\Discord\node_modules\axios\lib\core\createError.js:16:15)
>     at settle (C:\Users\USER\OneDrive\Documents\Projet\Discord\node_modules\axios\lib\core\settle.js:17:12)
>     at IncomingMessage.handleStreamEnd (C:\Users\USER\OneDrive\Documents\Projet\Discord\node_modules\axios\lib\adapters\http.js:269:11)
>     at IncomingMessage.emit (node:events:525:35)
>     at IncomingMessage.emit (node:domain:489:12)
>     at endReadableNT (node:internal/streams/readable:1359:12)
>     at processTicksAndRejections (node:internal/process/task_queues:82:21) {
>   config: {
>     url: ':batchUpdate',
>     method: 'post',
>     data: '{"requests":[{"deleteRange":{"range":{"sheetId":579234638,"startRowIndex":575,"endRowIndex":576},"shiftDimension":"ROWS"}}],"includeSpreadsheetInResponse":true}',
>     headers: {
>       Accept: 'application/json, text/plain, */*',
>       'Content-Type': 'application/json',
>       Authorization: 'Bearer ya29.c.b0AXv0zTMu2pCvEE8YndW0varxeuj2hwDXJ556uZAuuGcndvfV-uUbgQi5q3S-5CXyDMWcnbeSoEnZO143MVOxn8pKPI6Msd3Z88bksPQtE1OyBUt-WocCXSQdpz6R9ItCDHjs2jn_ObQK-AUdlF7ddXU1LaGfYHeehC5xN5cqewB-C4VSl_vhLO1TY62rJ1ulQSbAwJbn5-Wbd8eGy7A-WN4zzakXWAA...
> ............',
>     'User-Agent': 'axios/0.21.4',
>     'Content-Length': 160
>     },
>     baseURL: 'https://sheets.googleapis.com/v4/spreadsheets/1PlKHBLBKsKT4q-WtRhTVYi3GSQuPeJxzJePIshmAGAw',
>     transformRequest: [ [Function: transformRequest] ],
>     transformResponse: [ [Function: transformResponse] ],
>     paramsSerializer: [Function: paramsSerializer],
>     timeout: 0,
>     adapter: [Function: httpAdapter],
>     xsrfCookieName: 'XSRF-TOKEN',
>     xsrfHeaderName: 'X-XSRF-TOKEN',
>     maxContentLength: -1,

**Comment by theoephraim** [comment]
Closing as this is now quite old. Please reopen if still an issue
