### ISSUE TITLE
addRow() has no overwrite option

### ISSUE THREAD

**Issue by leonissenbaum** [theoephraim/node-google-spreadsheet#584]
The [addRow()](https://theoephraim.github.io/node-google-spreadsheet/#/classes/google-spreadsheet-worksheet?id=fn-addrow) function is missing an overwrite option that's [available](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/append#InsertDataOption) in google's API.

**Comment by theoephraim** [comment]
I believe overwrite is the default behaviour when nothing is passed - which is why there is only a boolean to change to "insert" mode.

**Comment by theoephraim** [comment]
closing this as it should be covered.
