### ISSUE TITLE
Minor issue with get rows

### ISSUE THREAD

**Issue by nopeless** [theoephraim/node-google-spreadsheet#587]
I was wondering why `#getRows()` was only returning two columns

Turns out that my spreadsheet looks like this

![image](https://user-images.githubusercontent.com/38830903/202844205-c893e5ee-e3e8-4df4-8317-9bc4a7f650c1.png)

https://github.com/theoephraim/node-google-spreadsheet/blob/456ce2563db894ed9db541c26dc415f7bfde01b6/lib/GoogleSpreadsheetWorksheet.js#L411-L446

Specifically, line `432` is causing the issue

I hope you can fix it soon

**Comment by nopeless** [comment]
bump

**Comment by nopeless** [comment]
bump

**Comment by theoephraim** [comment]
you can tell it which row contains your actual headers
see https://theoephraim.github.io/node-google-spreadsheet/#/classes/google-spreadsheet-worksheet?id=fn-loadheaderrow

**Comment by nopeless** [comment]
> you can tell it which row contains your actual headers see https://theoephraim.github.io/node-google-spreadsheet/#/classes/google-spreadsheet-worksheet?id=fn-loadheaderrow

I'm not sure if you are understanding the issue correctly.

Big header counts as 1 column. Therefore, only two columns are loaded. Instead, you should get the last absolute column of the last column of the header

Specifying the specific header row would fix this in this particular situation as the subheaders are not grouped, but this issue will appear in other occasions as well
