### ISSUE TITLE
insert rows instead of append to end

### ISSUE THREAD

**Issue by wptracy** [theoephraim/node-google-spreadsheet#601]
how would this line of code be changed to insert at line 2 of the spreadsheet instead of add (append) to the end of document.

  await sheet.addRow({ Date: dateTimestr, Event: req.body.event});

**Comment by rauno56** [comment]
There's no way to do that yet with this lib.

You want to use [Insertdimensionrequest](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/request#insertdimensionrequest) from the original API.

**Comment by theoephraim** [comment]
rolled into #615
