### ISSUE TITLE
TypeError: Cannot set properties of undefined (setting 'jwtClient')

### ISSUE THREAD

**Issue by KwanOPoliglota** [theoephraim/node-google-spreadsheet#604]
I was following this tutorial on [Youtube](https://www.youtube.com/watch?v=0bntGJ0bx9M)

When I came across this error:
![error](https://user-images.githubusercontent.com/109121580/213942315-3c8500b3-ee5a-4a13-b8f2-ac6ae6fd1121.png)

Does anyone know how to fix this error?
Its the first time i see this error and no one get this too
This is the code: 

```
const { GoogleSpreadsheet } = require('google-spreadsheet')
const credentials = require('./credentials.json')
const { promisify } = require("util")

const docID = '1XXAXjJva1kX00_A71dH4YU8QtAnfsFMJAKz07EakpM'

const accessSheet = async() => {
    const doc = new GoogleSpreadsheet(docID)
    await promisify(doc.useServiceAccountAuth)(credentials)
    const worksheet = info.worksheets[0]
    const info = await promisify(doc.getInfo)()
    const rows = await promisify(worksheet.getRows)({})
    console.log(rows)
}
accessSheet()
```

**Comment by vladik-Didyk** [comment]
Try this solution 
[https://stackoverflow.com/questions/64410856/react-js-and-google-spreadsheets-cannot-read-property-2-of-null]

**Comment by nopeless** [comment]
I'm writing this just in case some other person encounters this error

Do not use promisify without binding

```js
// incorrect code
promisify(doc.useServiceAccountAuth)(credentials)

// correct code
doc.useServiceAccountAuth(credentials)
// or
promiseify(doc.useServiceAccountAuth.bind(doc))(credentials)
```

**Comment by theoephraim** [comment]
I just released a new version which changes how auth is set up. Please take a look and reopen if you are still having issues.
