### ISSUE TITLE
error:1E08010C:DECODER routines::unsupported

### ISSUE THREAD

**Issue by xxCosta** [theoephraim/node-google-spreadsheet#606]
i have no clue what this means or how to fix it. im using the useServiceAccountAuth method.

**Comment by tomgallagher** [comment]
What was the answer to this @xxCosta - I've got the same thing when importing private key from .env file

**Comment by tomgallagher** [comment]
This should really be somewhere in the docs @theoephraim 

`process.env.GOOGLE_SHEETS_PRIVATE_KEY.replace(/\\n/g, "\n"),`

**Comment by Rickovald** [comment]
I have same issue .replace(/\\n/g, "\n"), doesn't help
