### ISSUE TITLE
Could not resolve module 'path'

### ISSUE THREAD

**Issue by spidercode** [theoephraim/node-google-spreadsheet#608]
After installing google-spreadsheet and running my react-native project it throws below error: 

```
error: Error: Unable to resolve module path from D:\Projects\MyProject\node_modules\google-auth-library\build\src\auth\googleauth.js: path could not be found within the project or in these directories:
  node_modules
  19 | const gcpMetadata = require("gcp-metadata");
  20 | const os = require("os");
> 21 | const path = require("path");
     |                       ^
  22 | const crypto_1 = require("../crypto/crypto");
  23 | const transporters_1 = require("../transporters");
  24 | const computeclient_1 = require("./computeclient");
```

So I manually installed path `npm i path --save`

Afterward, this error is gone and the same issue for `fs` module came. So again I installed `fs` module then it gave me the below error: 

```error: Error: While trying to resolve module `fs` from file `D:\Projects\MyProject\node_modules\google-auth-library\build\src\auth\googleauth.js`, the package `D:\Projects\MyProject\node_modules\fs\package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved ```

**Comment by nopeless** [comment]
@spidercode 

1. the `fs` you installed is not the `fs` you think it is
2. Do not install random packages without reading the npm page. You could have installed a malicious package
3. The repository says `node` and the author doesn't mention browser support. Chances are that it relies on node built in libraries such as path and fs, meaning that it wont work outside node context.

**Comment by theoephraim** [comment]
I just released a new version which decouples `google-auth-library` (makes it a peer dependency) and should make it easier to use this module in the browser or react-native. Please give it a whirl and reopen if still having problems!

**Comment by theyanniss23002** [comment]
This problem is still present! Tell me what to do about this? I use fabric, hermes

react 18
google-auth-library 9.7

google-spreadsheet 4.1.1
<img width="426" alt="Снимок экрана 2024-04-01 в 16 27 57" src="https://github.com/theoephraim/node-google-spreadsheet/assets/57316921/77800df3-d952-46cc-b578-108e972ff22f">

**Comment by StefanoCremona** [comment]
I'm having the same problem too within my react native app.
Is it because it's not meant to be a react native module?
Are you planning to build a react native integration module?
Cheers
