### ISSUE TITLE
How to call the mergeCells() method

### ISSUE THREAD

**Issue by acubick** [theoephraim/node-google-spreadsheet#617]
### Discussed in https://github.com/theoephraim/node-google-spreadsheet/discussions/616

<div type='discussions-op-text'>

<sup>Originally posted by **acubick** April  1, 2023</sup>
Help me understand how to call the mergeCells() method
Hey guys.
I can't call the .mergeCells() method
Already tried different options.
I see that in the documentation and in the code it is available. 
Can you show me an example of my code what I'm doing wrong?
Thanks.

I have this code:
  ` const doc = new GoogleSpreadsheet(<GoogleSpreadsheet_ID>)`

  ` await doc.loadInfo()`

   `const sheetSource = doc.sheetsByIndex[0]`

   ` await sheetSource.updateProperties({
        title: 'General report'
    })`  
   ` await sheetSource.loadCells({
        startRowIndex: 5, endRowIndex: 6, startColumnIndex:0, endColumnIndex: 5
    })` 
   `  const cellA1 = await sheetSource.getCell(1, 2)`  
    `await sheetSource.mergeCells() //  <=  this is not working `
<img width="740" alt="Screenshot 2023-04-01 at 13 32 11" src="https://user-images.githubusercontent.com/43810325/229281064-0ccb3b95-e522-4d9b-bb73-f423e63b5c30.png">
</div>

**Comment by theoephraim** [comment]
I just released a new version written in TypesScript so types should now be up to date!
