### ISSUE TITLE
Version 1.1.0 Not on NPM

### ISSUE THREAD

**Issue by jmar777** [theoephraim/node-google-spreadsheet#62]
It looks like the most recent version published to npm is 1.0.1.  Would you mind publishing the latest (assuming it's ready, of course)?  I'm hoping to take advantage of the bulk cell updates.

Thanks!

**Comment by theoephraim** [comment]
Oh no! that was definitely not on purpose!
I just published! hopefully it will show up shortly.

thanks for the heads up!
