### ISSUE TITLE
Create a new document with OAuth 2.0

### ISSUE THREAD

**Issue by JoaquinBeceiro** [theoephraim/node-google-spreadsheet#620]
Hi all!,
I cannot use the method `createNewSpreadsheetDocument` to create a new document if im using OAuth 2.0 auth.

The documentation:
```
const doc = new GoogleSpreadsheet();
await doc.useServiceAccountAuth(creds);
await doc.createNewSpreadsheetDocument({ title: 'This is a new doc' });
console.log(doc.spreadsheetId);
const sheet1 = doc.sheetsByIndex[0];
```

But `creds` is an object of type `{client_email, private_key}`. 
I'm using Oath 2.0 with `google-auth-library` 

Does anyone with the same issue?
Thanks!

**Comment by tmountjr** [comment]
Not sure if this is the same thing but I had it running with a service account but found that the docs were created with the service account as owner and I couldn't access those files in Drive. Domain-wide delegation is supposedly the answer but I can't use that for my org, so I couldn't tell you if/how that works.

**Comment by theoephraim** [comment]
I just released a new version which changes how auth works, adds sharing functionality, and hopefully the docs are a bit improved as well... Please take a look and reopen if you are still having problems.
