### ISSUE TITLE
`GoogleSpreadsheet.loadInfo` has an undocumented parameter

### ISSUE THREAD

**Issue by EndBug** [theoephraim/node-google-spreadsheet#622]
The [current official docs](https://github.com/theoephraim/node-google-spreadsheet/blob/456ce2563db894ed9db541c26dc415f7bfde01b6/docs/classes/google-spreadsheet.md?plain=1#L136) say that `loadInfo` doesn't accept any parameter, but the [source code](https://github.com/theoephraim/node-google-spreadsheet/blob/456ce2563db894ed9db541c26dc415f7bfde01b6/lib/GoogleSpreadsheet.js#L261-L270) shows that there's a `includeCells` option to be used.

**Comment by theoephraim** [comment]
Hi @EndBug! 

I'll take a look at the docs and get this fixed. 

PS -  Thanks so much for your work maintaining the types up until now.

I finally released a huge typescript rewrite that means the types will no longer drift...

I'd suggest we release a new version of the types repo that mentions that it is no longe needed and mark it was deprecated on NPM. Similar to what https://www.npmjs.com/package/@types/axios does.

Thanks!

**Comment by EndBug** [comment]
@theoephraim This is awesome, thanks!

I've opened a PR to deprecate DT typings as of vesion 4.0.0 🚀 
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65874

**Comment by EndBug** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65874 has been merged, closing this ✅
