### ISSUE TITLE
Instantly ratelimited when loading a document's info

### ISSUE THREAD

**Issue by DamonOnYT** [theoephraim/node-google-spreadsheet#625]
I have no clue how or why, but I've been having this issue where every time I load the sheet I'm instantly going over the max requests per minute, even when I hadn't touched the project for almost a month.

The second I go and load the doc info I am rate limited

```js
const { GoogleSpreadsheet } = require('google-spreadsheet');
const creds = require('./filenamewashere.json');e
const doc = new GoogleSpreadsheet('sheetnamewashere');
doc.useServiceAccountAuth(creds);

(async function () {

	//await doc.useServiceAccountAuth(creds);

	// wait a few seconds
	await new Promise(resolve => setTimeout(resolve, 30000));
	await doc.loadInfo()
// Instant ratelimited
}());
```

**Comment by theoephraim** [comment]
have you tried loading other sheets? Tried loading the same sheet with a different service account?

**Comment by theoephraim** [comment]
closing this for now... reopen with more details if necessary...
