### ISSUE TITLE
Can't get a title of sheet

### ISSUE THREAD

**Issue by peromina** [theoephraim/node-google-spreadsheet#64]
After updating today, 1.1.0, I can't get a title of sheets.

When I call "getInfo", the title of ws_data is undefined.

Could you fix this problem?

**Comment by sjmarshy** [comment]
:+1:

**Comment by vincentschroeder** [comment]
I have the same issue. You can switch back to version 1.0.1 there the title is working!

**Comment by theoephraim** [comment]
this is fixed thanks to https://github.com/theoephraim/node-google-spreadsheet/pull/65
thanks @seangallavan!
