### ISSUE TITLE
Gaxios Error: Google Api error [undefined] undefined 

### ISSUE THREAD

**Issue by kudo-47** [theoephraim/node-google-spreadsheet#642]
Hello sir,
I'm just trying to access the Google sheet with loadInfo() but I'm getting GaxiosError: Google Api error [undefined] undefined 

I'm just using the basic code provided in the docs

https://pastebin.com/HREkbf5P (code)
https://pastebin.com/45JM2uCL (error)

**Comment by theoephraim** [comment]
Try passing just the email, key, and scopes

**Comment by kudo-47** [comment]
> Try passing just the email, key, and scopes

same error sir

**Comment by kudo-47** [comment]
> Try passing just the email, key, and scopes

same error sir

**Comment by theoephraim** [comment]
The error "Invalid JWT Signature" makes me think that either:
- you are not getting the email and key set correctly. did you try console logging the values to make sure they look correct
- the info in that credential file was accidentally altered. Have you tried generating a new one?

**Comment by kudo-47** [comment]
> The error "Invalid JWT Signature" makes me think that either:
> 
> * you are not getting the email and key set correctly. did you try console logging the values to make sure they look correct
> * the info in that credential file was accidentally altered. Have you tried generating a new one?

oh my god thank you so much sir. i made new credential file and its working now. no idea why the previous key wasnt working. Thank you so much sir <3. Have a wonderful day/evening
