### ISSUE TITLE
Retrieve multiple hyperlinks from cell

### ISSUE THREAD

**Issue by razznblue** [theoephraim/node-google-spreadsheet#646]
Is there a way to extract the hyperlinks from a cell if it has multiple links inside of it?

```
// Cell with one link - returns the link
const cell = sheet.getCellByA1(a1Address).hyperlink

// Cell with multiple links - returns undefined
const cell2 = sheet.getCellByA1(a1Address2).hyperlink
```

**Comment by theoephraim** [comment]
I suspect this may be a limitation of the google sheets api itself. You can always pull the entire cell value and then use a regex to look for links?

**Comment by razznblue** [comment]
Thanks for the tip, I will look into that.

**Comment by razznblue** [comment]
I ended up not needing this as we got the sheet to have 1 link per cell. If anyone does happen to find a working solution, it would be helpful to put here for others to find in the future 🙏

**Comment by theoephraim** [comment]
ok thanks - I'll close for now...
