### ISSUE TITLE
got error "Module parse failed: Unexpected token"

### ISSUE THREAD

**Issue by frama21** [theoephraim/node-google-spreadsheet#647]
![image](https://github.com/theoephraim/node-google-spreadsheet/assets/22318828/6c7c397b-9ba3-4b9f-b6db-8410f2a319db)

i got error im using 
node version 14 & nuxt 2 and i got error like this
i want to migrate the package to latest version & maybe do some adjust like you documentation told

BTW thank you for your great package i love it,

**Comment by theoephraim** [comment]
seems like perhaps your setup doesn't know how to handle native module imports? Are you using import elsewhere or only `require`?

**Comment by frama21** [comment]
i make file called spreadsheet.js / .ts for make it like a helper so i just only call the method if i need the spreadsheet, this my code 
![code](https://github.com/theoephraim/node-google-spreadsheet/assets/22318828/eee55fb0-568f-4532-8ba0-95d36e5126f8)
@theoephraim

**Comment by theoephraim** [comment]
all looks ok there... I think the issue is more with however you are running this thing, ES modules, import, etc...

**Comment by frama21** [comment]
hmm the error is from google-auth-library by the way i just make the report the bug [1632](https://github.com/googleapis/google-auth-library-nodejs/issues/1632)

thanks for your support i close this issue
