### ISSUE TITLE
Google API error - [400] This operation is not supported for this document

### ISSUE THREAD

**Issue by u9g** [theoephraim/node-google-spreadsheet#651]
Hi, I'm getting the error: `Google API error - [400] This operation is not supported for this document` when opening an xlsx file that anyone can access and attempting to run `await doc.loadInfo()` on it. Here's a link to it: https://docs.google.com/spreadsheets/d/1AxzqfXfYSEiVVIdP2QYSVPr7bOG_jhOk/edit#gid=1230435171. For some reason I am unable to load the info of the spreadsheet, and am instead given this error.

**Comment by theoephraim** [comment]
Seems like the doc is still in xlsx format and you first need to fully convert it into google sheets format

**Comment by u9g** [comment]
> Seems like the doc is still in xlsx format and you first need to fully convert it into google sheets format

Is there any way to change the library to work with this format? Because I can use and manipulate the sheet completely fine from the actual sheets website

**Comment by theoephraim** [comment]
I don't think so. That is what the error is telling you. In the sheets ui, go to `File` > `Save as Google Sheets` - and then you should be able to connect to that document without any problems.
