### ISSUE TITLE
Work with current sheet?

### ISSUE THREAD

**Issue by isaacdarcilla** [theoephraim/node-google-spreadsheet#653]
I don't want to add new sheet every time I add new row. How can I work on the current available sheet in Google Sheet?

**Comment by isaacdarcilla** [comment]
Closing this:

```
const sheet = await doc.sheetsById[0];
```

**Comment by theoephraim** [comment]
Sorry that wasn’t more clear in the docs… maybe I overemphasized sheet creation. I’ll see if I can make it more clear.

**Comment by isaacdarcilla** [comment]
Yes, maybe update the docs. Thanks!
