### ISSUE TITLE
Issue with save method with getRows... 

### ISSUE THREAD

**Issue by jordanbuffaloe** [theoephraim/node-google-spreadsheet#66]
When I call this function, I can delete the row I'm referencing ( del() commented out, but works well), but the save() method on rows[2] (presumably on the Spreadsheet Row object here) is not saving my edits on the row's column values. I do see my edits after my reassignments in the console. Have used a service account for access, presumably working with delete capability. Would appreciate help. 

var updateSheet = function(){
        hotList2.useServiceAccountAuth(creds, function(err){
    	if(err){
            console.log(err);
        } else {
    	
            hotList2.getRows(worksheet_id, function( err, rows ){
              if(err){
                  console.log(err);
              } else {
              console.log(rows[2]); // accurately reflects target spreadsheet
              rows[2].githubnumber = '3';
              rows[2].submitter = 'Jordan';
              console.log(rows[2]); // can see changes here
              rows[2].save();  // this does not update the spreadsheet
            //   rows[2].del();   // this will work
            }
                
            });
        }
        });
        };

**Comment by theoephraim** [comment]
Looks like the change to add the Gdata-version header at 3.0 broke this :(   Thanks google!

I just published a fix although it is quite hacky. Basically we need to send all the properties that came with the original "feed" element along with each "entry" element.
See http://stackoverflow.com/questions/23634164/google-api-update-spreadsheet-using-put-with-php-and-curl

Anyway it should be transparent to you. Just upgrade from NPM and it should work!

**Comment by theoephraim** [comment]
@jordanbuffaloe Please close this issue if things are working properly for you :zap:

**Comment by jordanbuffaloe** [comment]
excellent - works great and your response time was killer. thank you!

**Comment by vinodhreddygs** [comment]
> @jordanbuffaloe Please close this issue if things are working properly for you ⚡️

Hi,
the property rowCount in SpreadsheetWorksheet object provides an whole row count in a google spread sheet. In our sheet we have only 300 odd rows populated.
I need to get rows length of where data is present. Is there any way to achieve it?
@theoephraim
