### ISSUE TITLE
[BUG] THE RGBA COLOR FORMAT IS GIVING WRONG COLORS

### ISSUE THREAD

**Issue by iamrishan** [theoephraim/node-google-spreadsheet#663]
```
var redColor = { red: 255, green: 0, blue: 0, alpha: 1 };

const cell1 = sheet1.getCell(1, 1);

cell1.backgroundColor = redColor;

await sheet1.saveUpdatedCells();
```

this should give the corresponding cell a red color instead of it a black color

![image](https://github.com/theoephraim/node-google-spreadsheet/assets/52799367/cbd72952-d9ea-4c9f-ba55-885457262486)

**Comment by DennisSnijder** [comment]
@iamrishan you should provide RGBA colors between 0 and 1. 

Try this: https://www.rapidtables.com/convert/color/hex-to-rgb.html

**Comment by iamrishan** [comment]
Oh, that's why... Thanks, i think it doesn't mention anywhere that the package uses RGB 0-1 values

**Comment by iamrishan** [comment]
[](https://rgbcolorpicker.com/0-1) this is cool if you wanna grab specific colors RGB 0-1 values

**Comment by theoephraim** [comment]
its definitely not obvious in google's docs. Would probably be good to clarify on the docs site and in the jsdoc type comments... Always open to PRs! otherwise will add in my next round of improvements...

Thanks
