### ISSUE TITLE
Ability to pass in `GOOGLE_FEED_URL` for the spreadsheet

### ISSUE THREAD

**Issue by lynnaloo** [theoephraim/node-google-spreadsheet#68]
It would be nice if there was an easy way to pass in a url for `GOOGLE_FEED_URL`. I'm trying to fetch a spreadsheet that's public, but only within a certain network so the url is more like "https://docs.google.com/a/somecompany.com/spreadsheets"

**Comment by theoephraim** [comment]
oh! I didn't realize that was a possibility. I'll see if I can get that implemented soon.
Also, pull requests welcome :D

**Comment by lynnaloo** [comment]
@theoephraim I'm going to close this because we discovered that the real issue was that our sheet required auth. Thanks!
