### ISSUE TITLE
getCells options

### ISSUE THREAD

**Issue by Umayalmuthupalaniappan** [theoephraim/node-google-spreadsheet#69]
when i was trying to use optional data like min_row,max_row,return_empty under getCells function .I am not successful doing so.can anyone say me the syntax for using options under getCells function

This is the snippet i tried
  my_sheet.getCells(1,{minRows: 2,maxRows: 3,returnEmpty: true},function(err,data) {
       console.log(data.length);
       // console.log(data);
       
    });

and also i need to read the empty cells inbetween too

**Comment by theoephraim** [comment]
Just released a big update! I hope that I fixed the docs too. Please upgrade to the latest version and let me know if you are still having problems. Thanks :)
