### ISSUE TITLE
Is there a way to filter rows based on cell values when requesting them?

### ISSUE THREAD

**Issue by Andriy-Kulak** [theoephraim/node-google-spreadsheet#690]
Hey Peeps! just curious if it's possible when fetching rows to filter them by specific values (i.e `price column >= 100`). The reason is that I have sheet with tons of rows so loading all of them would not make sense

If not, is this a limitation of the google sheets API or are there other approaches I an look into?  Looking through this repo I didn't find anything relevant so wanted to ask here. 

Cheers :-)

**Comment by theoephraim** [comment]
Google's previous (now deprecated) API had some features to do this, but the newer version doesn't.

One possible solution is to create a second sheet in your document that has the filter you need, and then fetch rows from _that_ sheet instead of the source data sheet.
