### ISSUE TITLE
useServiceAccountAuth PEM error

### ISSUE THREAD

**Issue by asci** [theoephraim/node-google-spreadsheet#70]
I got this error on my local machine (mac os)
`[Error: error:0906D06C:PEM routines:PEM_read_bio:no start line]`
How can I fix it?

**Comment by asci** [comment]
I created wrong type of key

**Comment by coloradude** [comment]
@asci Could you go into more detail on how you solved this? I'm running into the same issue.

**Comment by mmmavis** [comment]
@coloradude I just encountered the same issue. If you store the private key as env var, when that var gets read `\n` doesn't get interpreted as "new line". Massaging it with `.replace(/\\n/g, '\n')` fixed the problem for me. Hopefully this info helps. :bowtie:

**Comment by chadwithuhc** [comment]
@coloradude I followed @mmmavis's advice along with re-create the right type of key at https://console.developers.google.com/apis/credentials

The key should be a Service Account Key.

**Comment by joshbuchea** [comment]
@mmmavis & @chadwithuhc:

**App Engine default service account** or **Compute Engine default service account**?
