### ISSUE TITLE
Get Table support

### ISSUE THREAD

**Issue by SebastianAviles** [theoephraim/node-google-spreadsheet#709]
Please add Table support.

![image](https://github.com/user-attachments/assets/e96ec649-ae17-4f10-80b8-e4c9613150b7)

**Comment by theoephraim** [comment]
what exactly would you like to do with tables?

**Comment by SebastianAviles** [comment]
Insert rows inside tables, I tried to insert data, but only insert after all data, not inside.

**Comment by sputnik-liam** [comment]
@SebastianAviles I've encountered this myself and discovered a workaround.

If you delete all rows in the worksheet (so only the 1st empty row of the table remains) you can do the following
- Select `Adjust Table Range`
- By default the range will be something of the form `YourSheetName!A1:K1`
- Change it to not include specific row numbers `YourSheetName!A:K` where `A` is the starting column and `K` is the last column in your table. Going off of your screenshot assuming your sheet is called IpData it would be `IpData!A:C`

When you insert data using the package now, it will correctly expand the table to include your new data.

<img width="413" alt="image" src="https://github.com/user-attachments/assets/ac41bae5-9648-4e00-82d9-3b5ac4334295">
<img width="366" alt="image" src="https://github.com/user-attachments/assets/580a5f38-21f3-464c-8285-3b6a4c78c31b">

**Comment by theoephraim** [comment]
@sputnik-liam - thanks for your input!
