### ISSUE TITLE
The docs can't be accessed

### ISSUE THREAD

**Issue by avarik-kevin** [theoephraim/node-google-spreadsheet#710]
hi thanks for sharing

I can't seem to access the docs:
https://theoephraim.github.io/node-google-spreadsheet/

**Comment by theoephraim** [comment]
Nothing has changed on my end, so I suspect some larger dns/cloud issue… will take a look tomorrow! You can clone the repo and run the docs locally if you need them ASAP.

**Comment by avarik-kevin** [comment]
oh sure, I forgot that I can run the doc locally

was just checking, turns out that zod doc also stuck in Loading on my end,  probably only me then

thank you so much for answering!! you rock sir

**Comment by sbichenko** [comment]
Nope, the docs really are not working, and just showing "Loading..."

**Comment by theoephraim** [comment]
@sbichenko - hm, everything working just fine for me - both on the live site, and locally.

Do you see any JS errors?

**Comment by sbichenko** [comment]
Huh, works now. Very strange indeed!
