### ISSUE TITLE
rowCount length

### ISSUE THREAD

**Issue by karlstanton** [theoephraim/node-google-spreadsheet#72]
Hi there,

Noticing that the rows returned from the worksheet.getRows is different to the value returned from logging the worksheet object.

```
spreadsheet.useServiceAccountAuth(creds, function (err) {
		// Return the spreadsheet
		spreadsheet.getInfo(function (err, info) {
			// Loop through all the worksheets
			async.eachSeries(info.worksheets, function (worksheet, cb) {

				console.log(worksheet);
				// ... worksheet.rowCount = 49 here ...

				// Loop through the rows
				worksheet.getRows({'max-results': 300}, function (err, rowData) {
					if (err) return next(err);

					console.log(rowData.length);
					// ... rowData.length = 16 here ...

					cb();
				});
			}, function (err) {
				db.end(function(err) {
					return next(null, sheetData);
				});
			});
		});
	});
```

Any thoughts?

**Comment by karlstanton** [comment]
I dug into this more. The getRows method (or somewhere within) halts when it finds a row that is empty. Since my sheet has empty rows (to help format visually), this breaks. Looking into it and may have a PR soon.

**Comment by karlstanton** [comment]
Blergh.

**Comment by vinodhreddygs** [comment]
Hi, 
the property rowCount in SpreadsheetWorksheet object provides an whole row count in a google spread sheet. In our sheet we have only 300 odd rows populated.
I need to get rows length of where data is present. Is there any way to achieve it?
