### ISSUE TITLE
Add header colnames dinamically

### ISSUE THREAD

**Issue by piranna** [theoephraim/node-google-spreadsheet#75]
Allow to add more colnames on the header row directly from the API instead of require to do so manually directly on the spreadsheet.

**Comment by theoephraim** [comment]
It's possible to add a convenience method to add the header column, but internally it would just use the getCells method to fetch the first row and then add the new fields

**Comment by piranna** [comment]
But `getCells()` would only return the current ones with data, isn't it? If I request more cells than the currently available in the header, will it not give me just the available ones? How do I add the new headers, duplicating a currently available entry and modifying it?

**Comment by piranna** [comment]
Ok, I've test it and just by calling `getCells()` with `max-row` equal to 1 return all the cells on the header. Since I currently only have one it return a one-item array, I'm going to try to duplicate it to add a new one. Problem will be if I want to add headers on an empty spreadsheet, since the `SpreadsheetCell` constructor is not public... Do you mind doing so?

**Comment by piranna** [comment]
According to https://developers.google.com/google-apps/spreadsheets/#changing_contents_of_a_cell cells can't be directly added, but instead I'll need first to change the dimensions of the worksheet.

**Comment by theoephraim** [comment]
I'll take a look. It's definitely possible to grab a range of cells, including the empty ones, and save values to them.

Regardless, a helper fn to add row headers would definitely be useful!

**Comment by piranna** [comment]
I'm already taking a look on it, I can be able to get all the cells on the header row without problems. I've found that `Cell.save()` don't work. both because the save URL was wrong (didn't have the spreadsheet key and ID, only placeholders), and also when trying to update a cell I get the next error:

```
Error: HTTP error 403: Forbidden "If-Match or If-None-Match header or entry etag attribute required"
```

Seems it's required some headers...

**Comment by piranna** [comment]
I have been able to fix the update of single cells by fetching them first, grab its etag and adding it to the update request, you have it on my fork. I not able to write content on empty cells, I get the next error:

```
Error: HTTP error 400: Bad Request "No se puede actualizar una posición de celda."
```

Pretty generic... I'm going to see if I can be able to fetch it although is empty so I can be able to grab its etag too.

**Comment by piranna** [comment]
I can't be able to figure out why It give error when updating an empty cell, and also I'm not able to fetch it :-( Do you have any idea? You have my code uploaded on my repo, there's a lot of clean-ups and code organization too. I'm going to try to implement the spreadsheet size today or the monday.

**Comment by piranna** [comment]
I have been working on the ability to change the worksheet dimensions but I get the next error:

```
HTTP error 403: Forbidden "If-Match or If-None-Match header or entry etag attribute required"
```

I don't understand what's happening here, since I'm sending it... :-(

```xml
<entry xmlns="http://www.w3.org/2005/Atom"
       xmlns:gd="http://schemas.google.com/g/2005"
       xmlns:gs="http://schemas.google.com/spreadsheets/2006">
       gd:etag='"IRMQFEUYWyt7ImA."'>
  <title type="text">Hoja 1</title>
  <gs:rowCount>998</gs:rowCount>
  <gs:colCount>2</gs:colCount>
</entry>
```

I've uploaded the changes to my repo too.

**Comment by piranna** [comment]
I've managed to update the worksheet dimensions by sending the request with a `'If-Match': '*'` header as [node-edit-google-spreadsheet](https://github.com/jpillora/node-edit-google-spreadsheet) does. It's not as clean as the etag, but at least it does the job... :-)

**Comment by piranna** [comment]
Ok, finally got it! :-D Worksheet.setHeader() properly working :-) It automatically adjust the worksheet to the number of header columns and set the colnames in one step. I've also fixed bulkCellsUpdate() to allow literal objects so the cells can be easily added,  and as you can see there's a lot of clean-up and refactoring... :-P

**Comment by theoephraim** [comment]
Just released a big update! 
It includes a convenience method for setting the header row on a sheet. (and lots of other good stuff)

Please take a look! Some of your other changes may still be useful, but would probably have to be redone as this was a lot of changes.

The big thing I added was a full test suite so now we can make changes more confidently.
