### ISSUE TITLE
Implement Promise interface

### ISSUE THREAD

**Issue by slavafomin** [theoephraim/node-google-spreadsheet#77]
Hello!

Thank you for this great library.

However, it will be much easier to use with [Promise](http://bluebirdjs.com/docs/getting-started.html) interface. I've tried to promisify it using Bluebird, but stumbled upon some weird issues.

**Comment by theoephraim** [comment]
Can you post some sample code so I know what issues you ran into?

-- 
--------------------
Theo Ephraim
http://theoephraim.com
514.998.8436

**Comment by slavafomin** [comment]
I've managed to promisify the instance of the module, but it's not very practical because this module uses different objects, i.e. rows, sheets, etc. and all of them needs promisification. I think this better be done in the library itself. Without the promise interface this would be a callback hell to implement a complex usage scenario.

**Comment by seanodell** [comment]
Use Promise.promisifyAll on the sheet created with new GoogleSpreadsheet(...).

**Comment by ilyador** [comment]
+1

**Comment by ilyador** [comment]
@seanodell can you elaborate?

**Comment by seanodell** [comment]
A bit pseudo, but this is roughly what I did (based on README.md example):

`var Promise = require("bluebird");
var GoogleSpreadsheet = require("google-spreadsheet");

var my_sheet = Promise.promisifyAll(new GoogleSpreadsheet('<spreadsheet key>'));

my_sheet.getRowsAsync(1).then(function(row_data){
    console.log( 'pulled in '+row_data.length + ' rows');
}).catch(function(err){
});`

**Comment by theoephraim** [comment]
Thanks @seanodell. If it's that easy, it doesn't really seem necessary to build it into this module?

Thoughts folks?

**Comment by mrgoos** [comment]
I also did promisifyAll, it's pretty straight forward.
If you do implement it we wouldn't have to require bluebird but it's negligible IMO.

**Comment by odub** [comment]
Keen for a Promise interface to this library! 👍

**Comment by peter-mouland** [comment]
A promise interface would be excellent.
I didn't want to include a new library, so i manually wrapped them myself - but it's clunky.

```js

const setAuth = () => new Promise((resolve) => doc.useServiceAccountAuth(creds, resolve));

function getInfoAndWorksheets() {
  return new Promise((resolve, reject) => {
    doc.getInfo((err, info) => {
      if (err) reject(err);
      log(`Loaded doc: ${info.title} by ${info.author.email}`);
      resolve(info);
    });
  });
}

function addNewStatsSheets() {
  return new Promise((resolve, reject) => {
    doc.addWorksheet({
      title: new Date(),
      headers: [
        ...headers
      ],
      rowCount: 650,
      colCount: 20
    }, (err, sheet) => {
      if (err) reject(err);
      resolve(sheet);
    });
  });
}

const buildRow = (player) => {
  return {
    ...player
  };
};

const addrowsSync = (sheet, rows, cb) => {
  if (!rows.length) {
    cb();
  } else {
    const player = buildRow(rows[0]);
    sheet.addRow(player, (err) => {
      if (err) {
        log('err', err);
        throw new Error(err);
      } else {
        log(`${rows.length}`, player.player);
        rows.shift();
        addrowsSync(sheet, rows);
      }
    });
  }
};

// google to slow so didn't work
// const addrowsASync = (sheet, rows) => {
//   let completed = 0;
//   const promises = rows.map((row) => {
//     new Promise((resolve, reject) => {
//       const player = buildRow(row);
//       sheet.addRow(player, (err) => {
//         if (err) reject(err);
//         log(`${completed}`, player.player);
//         resolve(player);
//       });
//     });
//   });
//   return Promise.all(promises);
// };

function addStats(sheet, players) {
  return new Promise((resolve) => {
    addrowsSync(sheet, players, resolve);
  });
}

export default (data) => {
  return setAuth()
    .then(getInfoAndWorksheets)
    .then(addNewStatsSheets)
    .then((sheet) => addStats(sheet, data))
    .then(() => log('done.'))
    .catch(e => log(e));
};


```

**Comment by peter-mouland** [comment]
for anyone interested in a promised version, i've roughly come up with an altered code base to the above.  My approach was to : 

 1.  promisify the api : 
 2. create a class interface for new api
 3. ensure all class functions return `this` to allow for more functional programming
 4. ensure all class functions wait for required promises to finish before starting
 5. expose all 'queues' and a 'whenFinished' option to turn output into a promise.

This approach has allowed me to write the following code (which I find very concise):
```js

const spreadsheet = new GoogleSpreadsheet('---sheet-id---', credentials);
spreadsheet
    .addWorksheet({ title, headers, rowCount, colCount })
    .addRowsBulk(dataArray, { 'return-empty': true, 'min-row': 2, 'max-row': 6 })
    .whenComplete
    .then(() => log('done.'))
    .catch(e => log(e));
```

happy to contribute if this repo is accepting PR's?

**Comment by dzaman** [comment]
`Promise.promisifyAll(new GoogleSpreadsheet('key'))` only adds async methods to the GoogleSpreadsheet instance. If you want to use SpreadsheetWorksheet instances with promises you'll need to call promisifyAll again on that instance, too.

It would be nice to be able to promisify the entire library upfront instead of on an instance-by-instance basis which is currently required because the definitions of GoogleSpreadsheet and SpreadsheetWorksheet are inaccessible.

**Comment by yamsellem** [comment]
I've been struggle with the code for a while, so, if someone comes here later, here's what I end with:

```javascript
var Spreadsheet = require('google-spreadsheet');
var Promise = require('bluebird');

var credentials = require('./google-generated-creds.json');
var spreadsheet = '<spreadsheet key>';

var doc = Promise.promisifyAll(new Spreadsheet(spreadsheet));

doc.useServiceAccountAuthAsync(credentials)
.bind(this)
.then(function() {
  return doc.getInfoAsync()
  .then(function(info) {
    return info.worksheets[0];
  });
})
.then(function(sheet) {
  sheet = Promise.promisifyAll(sheet);
  
  return sheet.clearAsync()
  .then(function() {
    return sheet.setHeaderRowAsync(['Mail', 'Name'])
  })
  .then(function() {
    return sheet.addRowAsync({'Mail': 'paul@mail.com', 'Name': 'Paul'});
  });
});
```

**Comment by rustanacexd** [comment]
@yamsellem this code works?

**Comment by yamsellem** [comment]
@rustanacexd I've end with something working, yep. If I end up in a dead end, I don't really the point of posting some broken code here without a notice ;-). Have you tried it? Is something wrong with it?

**Comment by ksenzee** [comment]
Thanks, @yamsellem. That was really helpful. I needed Promises to work so I could use async/await. Here's what it looks like if you do that:

```javascript
var Spreadsheet = require('google-spreadsheet');
var Promise = require('bluebird');

var credentials = require('./google-generated-creds.json');
var key = '<spreadsheet key>';

var doc = Promise.promisifyAll(new Spreadsheet(key));

await doc.useServiceAccountAuthAsync(credentials);

var info = await this.doc.getInfoAsync();
var sheet = Promise.promisifyAll(info.worksheets[0]);

// Now do whatever you like with your sheet:
var rowData = await worksSheet.getRowsAsync({offset: 1, limit: 10});
// If you really can do something asynchronously, no need to use await:
sheet.setHeaderRowAsync(['Mail', 'Name']);
```

**Comment by jesperorb** [comment]
Thanks @ksenzee, built on from your example and got my implementation to work. Some `await`s may be unnecessary but it's working fine.

```js
const Promise = require("bluebird");
const Spreadsheet = require("google-spreadsheet");
const { SPREADSHEET_ID } = require("./config");
const credentials = require("./config/service_account_config.json");
const doc = Promise.promisifyAll(new Spreadsheet(SPREADSHEET_ID));

main();

async function main() {
  try {
    await connectToSpreadSheet();
    await getInfoAboutSpreadSheet();
  } catch (e) {
    console.log(e);
  }
}

async function connectToSpreadSheet() {
  try {
    await doc.useServiceAccountAuthAsync(credentials);
  } catch (e) {
    console.log("Connection error", e);
  }
}

async function getInfoAboutSpreadSheet() {
  try {
    const info = await doc.getInfoAsync();
    console.log(`\x1b[34mLoaded document: \x1b[35m${info.title}`);
  } catch (e) {
    console.log("Get information error", e);
  }
}
```

**Comment by gregorskii** [comment]
This works for me, but with Node 8.7.0 I get this error:

```
(node:16759) Warning: a promise was created in a handler at PROJECT/node_modules/thunks/index.js:225:19 but was not returned from it, see http://goo.gl/rRqMUw
    at GoogleSpreadsheet.ret [as useServiceAccountAuthAsync] (eval at makeNodePromisifiedEval (PROJECT/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:8:21)
(node:16759) Warning: a promise was created in a handler at events.js:210:7 but was not returned from it, see http://goo.gl/rRqMUw
    at SpreadsheetWorksheet.ret [as getRowsAsync] (eval at makeNodePromisifiedEval (PROJECT/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:8:21)
```

**Comment by jesperorb** [comment]
@gregorskii Have you read the link in the error? And checked all your `return`s?

>This usually means that you simply forgot a return statement somewhere, which will cause a runaway promise that is not connected to any promise chain.

[bluebirdjs - Warning  Explanations](http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-created-in-a-handler-but-was-not-returned-from-it)

**Comment by gregorskii** [comment]
Yep. It seems to happen outside my code.

**Comment by gregorskii** [comment]
I can double check again tomorrow. But I was using this same code on another project previously with no error.

**Comment by gregorskii** [comment]
Its erroring out early on:

```
const Spreadsheet = require('google-spreadsheet');
const Promise = require('bluebird');

module.exports = () => {
  class Spreadsheet {
    constructor(key) {
      this.creds = require('../../../key.json');
      this.doc = Promise.promisifyAll(new Spreadsheet(key));
    }

    authorize() {
      return this.doc.useServiceAccountAuthAsync(this.creds)
        .then(() => {
          return this.doc.getInfoAsync()
            .then((res) => {
              this.sheet = res.worksheets[0];
              Promise.promisifyAll(this.sheet);
              return null;
            })
          ;
        })
      ;
    }

    loadRows() {
      return this.sheet.getRowsAsync();
    }
  }

  return Spreadsheet;
};

```

I did find some other rogue promises that were creating a couple of those. This last one errors out with this simple implementation:

```
const Sheet = require('../helpers/sheet')();
const sheet = new Sheet(SHEET_ID);


sheet.authorize().then(
  () => {
    console.log('done');
  }
);
```

Output:

```
(node:16759) Warning: a promise was created in a handler at PROJECT/node_modules/thunks/index.js:225:19 but was not returned from it, see http://goo.gl/rRqMUw
    at GoogleSpreadsheet.ret [as useServiceAccountAuthAsync] (eval at makeNodePromisifiedEval (PROJECT/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:8:21)
```

**Comment by FranciscoG** [comment]
+1 for implementing Promises

Can I suggest using native Promises instead of BlueBird though? [Node has had Promises natively for a while](https://node.green/#ES2015-built-ins-Promise), [Browsers as well](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise). For the browser we can leave it up to the user to add a Polyfill.

Using native promises you might be able to drop the `async` dependency

It would be great to have Promises built into the library instead of having to wrap everything after the fact

thanks for the great library!

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020). **YOU MUST MIGRATE IF YOU ARE STILL USING THIS PACKAGE!**

**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

New version is promise based and much cleaner. Please test it out!

Thanks! 😄
