### ISSUE TITLE
Cells with "=IMAGE()" values are returned empty from API and update to row overrides the value

### ISSUE THREAD

**Issue by ctulek** [theoephraim/node-google-spreadsheet#79]
This can be because of the nature of the Google Sheet API but when I use "=IMAGE()" command for a cell, the value is not returned from API. Worse than that, when I try to change and save one other column of the row, since the whole row is saved, the column with "=IMAGE()" is set to empty string.

Possible Suggestions to Solve this Issue:
- Provide ability for partial updates through save method or so
- Provide the row number in SpreadsheetRow class so that we can get the related cell through getCells function by giving the min-max values for the row and update the cell individually

**Comment by theoephraim** [comment]
Unfortunately, I do believe this is likely a limitation of the google sheets API.
I'll take a look and see if there's a way to save without overwriting the value, but I would guess there isn't.

Providing the row number or even a `row.getCells()` method would definitely be useful though!

**Comment by theoephraim** [comment]
I looked into this a bit more.

Interestingly, you can write a formula value into a cell using the row based API, but when you read it again, you cannot detect that a formula is present - you only get the value. In the case of the an image formula, it returns an empty value, so when you save again it will clear the cell.

I thought I would be able to get the row number from the XML, or use the row ID to make a call to get the corresponding cells, but from what I can tell, it is not possible :(
