### ISSUE TITLE
SpreadsheetRow.content property has gone missing

### ISSUE THREAD

**Issue by blkeller** [theoephraim/node-google-spreadsheet#83]
I just updated from npm yesterday and noticed that my code broke that was using node-google-spreadsheet.  I traced the problem down to an undefined object property.

The SpreadsheetRow.content property that was present in v1.0.1 seems to have vanished from 1.1.0 and above.  Is this an accident or an intentional API change?

Thanks.

**Comment by theoephraim** [comment]
Im about to roll out a very large refactoring (with lots of tests!) 
What was in the `.content` property that is not missing?

**Comment by blkeller** [comment]
The entire `.content` property is missing.  Looking at old logs from my app, it looks like `.content` used to contain a _string_ of comma-separated key:value pairs where the key was a column header and the value was the value of that column, following left-to-right across the row represented by the `SpreadsheetRow` object.  I'd paste my log output here for you to see, but I can't because the spreadsheet in question contains confidential information.

I was able to verify that the property disappeared by comparing a `util.inspect()` dump of the `SpreadsheetRow` object from v1.0.1 to v1.1.0 (also missing from v1.1.4).  The property appears in the former but not in the latter.  In case it matters, the `SpreadsheetRow` object was created by `SpreadsheetWorksheet.getRows()`.

**Comment by theoephraim** [comment]
Hmm doesnt sound very useful. So I think it's ok to leave out of this update. I'm guessing it was coming through from the xml directly, but all of the data is captured in other fields. Were you using it for anything that you can no longer do?

**Comment by blkeller** [comment]
Well, I'm not the original developer of this code, but I inherited it for maintenance.  I can't say for certain why this particular method of accessing row content was chosen, but it looks like the original developer was relying on `SpreadsheetRow.content` ultimately as a way to create an array containing all of the values in a given row, in the order in which they appeared in the spreadsheet, so that he could address each value by index rather than by the name generated by the header row (row[0]).

I tried looking through old versions of your API documentation to see if I could find references to this property, but I never did find it, which makes me wonder how the original developer of my code decided to use it.  Do you recall ever officially supporting it?

Regardless, what's your recommended way to retrieve this same information, namely an array of all values in a given row, in the order in which they appear in the spreadsheet?  If I'm going to have to refactor, I figure I might as well use a well-supported method.

Also, I think you're right about `.content` coming from the XML.  Looking again at my logs, I see that the value inside of `<entry><content></content></entry>` exactly matches the value of the `.content` property.

**Comment by theoephraim** [comment]
I finally released a big update. `.content` didnt make the cut as it didnt seem very useful.
So I'm going to close this out.

**Comment by blkeller** [comment]
That's fair, but then could you please provide an answer to my previous question:
> what's your recommended way to retrieve this same information, namely an array of all values in a given row, in the order in which they appear in the spreadsheet? If I'm going to have to refactor, I figure I might as well use a well-supported method.

Thanks.

**Comment by theoephraim** [comment]
sorry I missed that question. With the current functionality, you could:
- fetch the header row using getCells to get the exact header row in order
- use the cells based API instead of the row-based API to fetch cells instead of the full row

But it should be fairly simple to add new functionality to make the row headers available in the order they appear in the XML. I assume the order they appear in from the XML is the same as the sheet, but it may not be.
