### ISSUE TITLE
Can no longer authenticate with useServiceAccountAuth

### ISSUE THREAD

**Issue by TheSisb** [theoephraim/node-google-spreadsheet#84]
So I've been using this lib and a script with no issues for a couple months.  Suddenly yesterday when I tried, simply authenticating has started to give me errors.

The code:
```js
DOC.useServiceAccountAuth(CREDENTIALS, (err) => {
    if (err) {
      console.log("Auth error: ", err);
   }
});
```
The error output:
```
Auth error: [Error: invalid_grant]
```

Nothing else is spat out, not sure where to go from here.  Is anyone aware of if Google changed anything?

**Comment by theoephraim** [comment]
Everything still seems to be working on my end.
You may want to verify your service account is still active?

If you dig into the code a bit, you may be able to just call the auth methods and see what kind of errors you get?

**Comment by theoephraim** [comment]
any news here?

**Comment by TheSisb** [comment]
Tried again a day later and it worked.  /shrug.

Sorry couldn't dig deeper here
