### ISSUE TITLE
Can hidden worksheets be flagged somehow?

### ISSUE THREAD

**Issue by mrgoos** [theoephraim/node-google-spreadsheet#85]
Hi,
Is there any way to flag hidden worksheets? Currently all the worksheets are returned without the possibility to know which ones are hidden and which are not.

Thanks.

**Comment by theoephraim** [comment]
Not sure if this info is available when fetching the sheets. I've never made a sheet hidden, but I'll try it out!

**Comment by mrgoos** [comment]
:+1:

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020). **YOU MUST MIGRATE IF YOU ARE STILL USING THIS PACKAGE!**

**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

New version has `sheet.hidden` as a property

Thanks! 😄
