### ISSUE TITLE
Only getting 5 rows on public sheet

### ISSUE THREAD

**Issue by seanodell** [theoephraim/node-google-spreadsheet#86]
Per the title, I've got a sheet document with about 150 rows, and I can pull down about 5 of them. On first call to getRows, I pass offset of zero and it pulls down 4 rows. Then I call again with offset of 4 and I get 1 row. Call again with offset of 5 and I get zero rows.

**Comment by theoephraim** [comment]
Do you have an empty row in your sheet?
Google's row based API doesn't like empty rows - it just thinks your data stops :\

**Comment by seanodell** [comment]
Yes, but I can't control that.

It sounds like this is a bug in the Google API, not this project?

**Comment by theoephraim** [comment]
yes this is a limitation of google's row-based API. The cell-based API doesnt have this limitation, so you could use that instead.

http://stackoverflow.com/questions/6831857/how-to-read-rows-after-empty-row-in-the-google-spreadsheet

**Comment by seanodell** [comment]
Good to know! I guess this issue will stand as a reference for anyone else with this issue in the future. Thanks for your help!
