### ISSUE TITLE
getRows not parsing all rows?

### ISSUE THREAD

**Issue by elloboblanco** [theoephraim/node-google-spreadsheet#91]
The `rowCount` is 648 but `getRows` only returns 580. Am i missing something? I expected all my rows to be returned but I only get a subset.

**Comment by elloboblanco** [comment]
Figured this out, looks like this library will stop parsing on an empty row! Removed my empty row and it worked as expected.

**Comment by theoephraim** [comment]
You are correct! Although it is not the library. It's the Google row
based API.

-- 
--------------------
Theo Ephraim
http://theoephraim.com
514.998.8436

**Comment by elloboblanco** [comment]
Bummer! Well glad I figured it out, pressing `⌘+a` in the Google Sheet showed me what was going on :)
