### ISSUE TITLE
Authentication using user's Drive

### ISSUE THREAD

**Issue by asantos00** [theoephraim/node-google-spreadsheet#92]
I've been using this lib and it's pretty cool, good job!

It would be awesome if there is a possibility for it to use user credentials (without the service account) as you listed in README... Do you have it in your "roadmap"?

If you want, I can try to implement that!

_Note_: I think the way the lib "assumes" the header title is not very flexible, it would be cool if it was possible to set the row to be used as "header" (as it's not always the first one).

**Comment by theoephraim** [comment]
I have not explored much into the other auth options. I did set it up so you can pass in an existing auth token, but I'm not sure how it would handle renewing the token... Feel free to submit a PR!

For the header row, this is how google's "row-based API" works. It is quite limiting actually :\

**Comment by asantos00** [comment]
From what I read https://github.com/google/google-api-nodejs-client#oauth2-client and have tried in other libs, what we can do is like:
- Require CLIENT_ID, CLIENT_SECRET, REDIRECT_URL in the app and return a url (which is the permissions url, where the user will have to confirm)
- User confirms and then Google returns a code that the user will have to insert in the app
- With that code we can have a token and access user's drive (probably reusing the method you have where you are expecting an existing token)

Oh, I didn't know that about the header, it's a shame but we can't do much I see. 
The only solution was something like "parsing" the cells but it can be awful for performance.

**Comment by theoephraim** [comment]
So it seems to me that you could do this auth flow in your code, and then call `GoogleSpreadsheet.setAuthToken` with the token? The only issue is that tokens can expire and need to be renewed (at least the JWT ones we use for service accounts do) and the library handles renewing it for you. So maybe there is some additional code needed to renew tokens or at least to catch the error of it needing to be renewed.

**Comment by asantos00** [comment]
Ok, so we should have the lib supporting an external callback or event when
it gets the expired token error so the user can renew the token and pass it
again, right?

**Comment by theoephraim** [comment]
that sounds right!

**Comment by asantos00** [comment]
I found that with the authentication library you are using from Google it
is possible to access user files. It happens that you will have to show a
url to the user, the user has to open his browser accept your app's
permissions and then copy the code back in the application.

With that code we can get a token for us to use and access his files, does
it sounds nice as a feature?

*Alexandre Miguel Portela dos Santos*

*e-mail:*      alexandre.santozz@gmail.com
*tel:   *           (+351) 913429823
*skype: *       santosalexandre21
*website: *    http://alexandrempsantos.com

that sounds right!

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/theoephraim/node-google-spreadsheet/issues/92#issuecomment-197915487>

**Comment by asantos00** [comment]
It's an alternative to use the service account

**Comment by asantos00** [comment]
I've implemented an oAuth2 working version to access the user spreadsheets, take a look, if you agree I will do the testing and the PR.

https://github.com/asantos00/node-google-spreadsheet/commit/0f1ec47dd5374c8745dd779418684d02eec93532

**Comment by theoephraim** [comment]
Oauth support coming soon :)

FYI - I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020). **YOU MUST MIGRATE IF YOU ARE STILL USING THIS PACKAGE!**

**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

Thanks! 😄

**Comment by asantos00** [comment]
Amazing! I completely forgot I've created this issue before 😄
