### ISSUE TITLE
Document major changes + tag release?

### ISSUE THREAD

**Issue by voxpelli** [theoephraim/node-google-spreadsheet#93]
Great to see a new major version of this module! I'm loving it, makes working with Google Spreadsheet as a datastore wonderfully simple and if something I've made much use for on a big new project.

I would love to know what breaking changes there might be in 2.0? Especially as a major version according to SemVer more or less means that there are some breaking changes in there and I rather deal with them upfront rather than have degradations be found later on.

So if you could make a changelog along the lines of http://keepachangelog.com/ + maybe add the relevant changes as release notes in a tagged release, then that would be super!

Adding the related changelog to ones tags eg. makes them easy to find when subscribing to a projects releases feed while having something like a `CHANGELOG.md` in ones top project makes it easy for people visiting a project to see how it has changed over time and whether an update will be a big or a small task.

That will also benefit you as a maintainer as people are more likely to update to new major versions if they can estimate how big of a task it would be and you would get your users less spread out amongst legacy releases and can have them benefit from and contribute to all of your new awesome fixes and tweaks.

Thanks again for a great module!

**Comment by theoephraim** [comment]
You are absolutely correct and thanks for the encouragement to do things the right way.

But I'm not sure when I'll get to it in the short term. So until I do, just wanted to let you know that there are _very_ few breaking changes. Mostly just fixing things that were broken or half-implemented. But I figured a 2.0 release as a clean start would make sense in case anyone was using something undocumented or expecting weird behaviour.

Off the top of my head:

- `cell.inputValue` doesnt exist anymore. Instead you can access `value`, `numericValue` and `formula`
- removed `bulkUpdateCells` from the main doc object and it now only exists on the worksheet

I'll leave this issue open until I set something proper up!

**Comment by theoephraim** [comment]
NEW BREAKING CHANGE ALERT!

Once this new version stabilizes I'll see about adding a changelog

I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020). **YOU MUST MIGRATE IF YOU ARE STILL USING THIS PACKAGE!**

**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

I do believe this issue should be fixed in the new version.
Please test it out and if you find that there is still a problem, reopen the issue.

Thanks! 😄
