### ISSUE TITLE
"undefined is not a function" upon calling cell.save

### ISSUE THREAD

**Issue by johndifini** [theoephraim/node-google-spreadsheet#99]
Upon calling cell.save() in the [Basic Usage](https://github.com/theoephraim/node-google-spreadsheet#basic-usage) example, I get "undefined is not a function" from google-spreadsheet/index.js:629:7.  Should the call to cell.save() pass an argument to the save function?  Thanks.

**Comment by theoephraim** [comment]
Yes it takes a callback. See: https://github.com/theoephraim/node-google-spreadsheet#spreadsheetcellsavecallback

The basic usage example is just a quick overview. But I should probably change it to make it more clear!

Thanks
